Repository eclipse-edc/Connector, pull requests merged in 2022-11, with the labels that each got.

#2139 feat(api): adds @ApiTest tag for controller integration tests
  .github/workflows/verify.yaml
  core/common/util/src/testFixtures/java/org/eclipse/edc/util/testfixtures/annotations/ApiTest.java
  core/federated-catalog/federated-catalog-core/build.gradle.kts
  core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheEndToEndTest.java
  extensions/common/http/jersey-core/build.gradle.kts
  extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/mapper/ExceptionMappersIntegrationTest.java
  extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/validation/integrationtest/ValidationIntegrationTest.java
  extensions/control-plane/api/data-management-api/asset-api/build.gradle.kts
  extensions/control-plane/api/data-management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/asset/AssetApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management-api/catalog-api/build.gradle.kts
  extensions/control-plane/api/data-management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management-api/contract-agreement-api/build.gradle.kts
  extensions/control-plane/api/data-management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/contractagreement/ContractAgreementApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management-api/contract-definition-api/build.gradle.kts
  extensions/control-plane/api/data-management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management-api/contract-negotiation-api/build.gradle.kts
  extensions/control-plane/api/data-management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management-api/policy-definition-api/build.gradle.kts
  extensions/control-plane/api/data-management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/policy/PolicyDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management-api/transfer-process-api/build.gradle.kts
  extensions/control-plane/api/data-management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/control-plane/provision/provision-http/build.gradle.kts
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpProvisionerWebhookApiControllerIntegrationTest.java
  extensions/data-plane-selector/data-plane-selector-api/build.gradle.kts
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataplaneSelectorApiControllerIntegrationTest.java
  extensions/data-plane/data-plane-api/build.gradle.kts
  extensions/data-plane/data-plane-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlaneApiIntegrationTest.java
Labels: enhancement, build

#2145 feat(oauth2): adds configuration of TOKEN_EXPIRATION
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2Configuration.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2Extension.java
Labels: enhancement

#2158 chore(README): restore logo
  README.md
  resources/media/logo.png
Labels: documentation

#2153 docs: correct port of the file transfer process for the data consumer (9192)
  samples/05-file-transfer-cloud/README.md
Labels: documentation

#2156 feat: improve catalog request error detail
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/message/FutureCallback.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/edc/protocol/ids/message/FutureCallbackTest.java
  extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/mapper/EdcApiExceptionMapper.java
  extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/mapper/EdcApiExceptionMapperTest.java
  extensions/control-plane/api/data-management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/datamanagement/catalog/CatalogApiController.java
  extensions/control-plane/api/data-management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/BadGatewayException.java
Labels: enhancement, api

#2151 docs: service layer DR
  docs/developer/decision-records/2022-10-31-aggregate-service-layer/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#2135 feat: implement oauth2 provision module
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/provision/ProvisionManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
  extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/AwsSecretToken.java
  extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/edc/aws/s3/AwsTemporarySecretToken.java
  extensions/common/azure/azure-blob-core/src/main/java/org/eclipse/edc/azure/blob/AzureSasToken.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/edc/gcp/common/GcpAccessToken.java
  extensions/common/vault/vault-filesystem/src/main/java/org/eclipse/edc/vault/filesystem/FsVault.java
  extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3BucketProvisionedResource.java
  extensions/control-plane/provision/provision-blob/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectContainerProvisionedResource.java
  extensions/control-plane/provision/provision-gcs/src/main/java/org/eclipse/edc/connector/provision/gcp/GcsProvisionedResource.java
  extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/webhook/SimpleSecretToken.java
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/SimpleSecretTokenTest.java
  extensions/control-plane/provision/provision-oauth2/README.md
  extensions/control-plane/provision/provision-oauth2/build.gradle.kts
  extensions/control-plane/provision/provision-oauth2/docs/diagram.png
  extensions/control-plane/provision/provision-oauth2/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ConsumerResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-oauth2/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2DataAddressSchema.java
  extensions/control-plane/provision/provision-oauth2/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2DataAddressValidator.java
  extensions/control-plane/provision/provision-oauth2/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProviderResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-oauth2/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtension.java
  extensions/control-plane/provision/provision-oauth2/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionedResource.java
  extensions/control-plane/provision/provision-oauth2/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2Provisioner.java
  extensions/control-plane/provision/provision-oauth2/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ResourceDefinition.java
  extensions/control-plane/provision/provision-oauth2/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2SecretToken.java
  extensions/control-plane/provision/provision-oauth2/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/provision/provision-oauth2/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ConsumerResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-oauth2/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProviderResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-oauth2/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtensionTest.java
  extensions/control-plane/provision/provision-oauth2/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionerTest.java
  extensions/control-plane/provision/provision-oauth2/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ResourceDefinitionTest.java
  extensions/control-plane/provision/provision-oauth2/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2SecretTokenTest.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpExtension.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSinkRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSourceRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpRequestParamsSupplierTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSinkRequestParamsSupplierTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSourceRequestParamsSupplierTest.java
  settings.gradle.kts
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/DataAddress.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/HttpDataAddress.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/ProvisionedDataAddressResource.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/SecretToken.java
  system-tests/e2e-transfer-test/backend-service/build.gradle.kts
  system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/edc/test/e2e/BackendServiceTestExtension.java
  system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/edc/test/e2e/Oauth2TokenController.java
  system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/edc/test/e2e/ProviderBackendApiController.java
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/e2e-transfer-test/data-plane/build.gradle.kts
  system-tests/e2e-transfer-test/runner/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferPostgresqlTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
Labels: enhancement

#2167 fix(build): fix provision-oauth2 module build after junit refactor merge
  extensions/control-plane/provision/provision-oauth2/build.gradle.kts
Labels: build

#2173 fix: remove usages of Apache Commons Lang
  system-tests/tests/src/test/java/org/eclipse/edc/test/system/remote/FileTransferAsClientSimulation.java
Labels: refactoring

#2172 feat(Readme): add badges to the README
  README.md
Labels: documentation

#2154 chore(build): change groupId to org.eclipse.edc
  build.gradle.kts
  docs/swaggerui/swagger-spec.js
  extensions/control-plane/provision/provision-oauth2/README.md
  gradle.properties
  resources/openapi/openapi.yaml
  resources/openapi/yaml/api-observability.yaml
  resources/openapi/yaml/asset-api.yaml
  resources/openapi/yaml/catalog-api.yaml
  resources/openapi/yaml/contract-agreement-api.yaml
  resources/openapi/yaml/contract-definition-api.yaml
  resources/openapi/yaml/contract-negotiation-api.yaml
  resources/openapi/yaml/control-plane-api.yaml
  resources/openapi/yaml/data-plane-api.yaml
  resources/openapi/yaml/data-plane-selector-api.yaml
  resources/openapi/yaml/data-plane-transfer-sync.yaml
  resources/openapi/yaml/federated-catalog-core.yaml
  resources/openapi/yaml/policy-definition-api.yaml
  resources/openapi/yaml/provision-http.yaml
  resources/openapi/yaml/provision-oauth2.yaml
  resources/openapi/yaml/transfer-process-api.yaml
Labels: refactoring

#2130 build: move build configuration out into plugin
  .github/workflows/verify.yaml
  build.gradle.kts
  docs/swaggerui/favicon-16x16.png
  docs/swaggerui/favicon-32x32.png
  docs/swaggerui/index.css
  docs/swaggerui/index.html
  docs/swaggerui/oauth2-redirect.html
  docs/swaggerui/swagger-initializer.js
  docs/swaggerui/swagger-ui-bundle.js
  docs/swaggerui/swagger-ui-bundle.js.map
  docs/swaggerui/swagger-ui-es-bundle-core.js
  docs/swaggerui/swagger-ui-es-bundle-core.js.map
  docs/swaggerui/swagger-ui-es-bundle.js
  docs/swaggerui/swagger-ui-es-bundle.js.map
  docs/swaggerui/swagger-ui-standalone-preset.js
  docs/swaggerui/swagger-ui-standalone-preset.js.map
  docs/swaggerui/swagger-ui.css
  docs/swaggerui/swagger-ui.css.map
  docs/swaggerui/swagger-ui.js
  docs/swaggerui/swagger-ui.js.map
  gradle/wrapper/gradle-wrapper.properties
  resources/openapi/openapi.yaml
  resources/openapi/yaml/http-provision.yaml
  settings.gradle.kts
Labels: build

#2165 refactor(apiExtensions): removes duplicated code when configuring an API extension
  core/control-plane/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/ControlPlaneApiExtension.java
  core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
  data-protocols/ids/ids-api-configuration/src/main/java/org/eclipse/edc/protocol/ids/api/configuration/IdsApiConfigurationExtension.java
  data-protocols/ids/ids-api-configuration/src/test/java/org/eclipse/edc/protocol/ids/api/configuration/IdsApiConfigurationExtensionTest.java
  extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyExtension.java
  extensions/control-plane/api/data-management-api/data-management-api-configuration/src/main/java/org/eclipse/edc/connector/api/datamanagement/configuration/DataManagementApiConfigurationExtension.java
  extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/HttpWebhookExtension.java
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpWebhookExtensionTest.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/WebServer.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfiguration.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfigurer.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfigurerImpl.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceSettings.java
  spi/common/web-spi/src/test/java/org/eclipse/edc/web/spi/configuration/WebServiceConfigurerImplTest.java
Labels: refactoring

#2176 docs: Update maven badge to the new group id
  README.md
Labels: documentation

#2174 feat: add retry mechanism to oauth2 service
  extensions/common/iam/oauth2/oauth2-core/build.gradle.kts
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2Extension.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImpl.java
  extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImplTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/Result.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/result/ResultTest.java
Labels: enhancement

#2184 docs: add decision record about refactoring the OpenAPI documentatiion process
  docs/developer/decision-records/2022-11-09-api-refactoring/README.md
  docs/developer/decision-records/2022-11-09-api-refactoring/documentation.md
  docs/developer/decision-records/2022-11-09-api-refactoring/renaming.md
  docs/developer/decision-records/README.md
Labels: documentation

#2189 feat(samples): adds consumer status checker on file for sample 4
  samples/04.0-file-transfer/README.md
  samples/04.0-file-transfer/consumer/build.gradle.kts
  samples/04.0-file-transfer/integration-tests/src/test/java/org/eclipse/edc/sample/extension/FileTransferSampleTest.java
  samples/04.0-file-transfer/integration-tests/src/testFixtures/java/org/eclipse/edc/sample/extension/FileTransferSampleTestCommon.java
  samples/04.0-file-transfer/status-checker/build.gradle.kts
  samples/04.0-file-transfer/status-checker/src/main/java/org/eclipse/edc/sample/extension/checker/SampleFileStatusChecker.java
  samples/04.0-file-transfer/status-checker/src/main/java/org/eclipse/edc/sample/extension/checker/SampleStatusCheckerExtension.java
  samples/04.0-file-transfer/status-checker/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  settings.gradle.kts
Labels: enhancement

#2159 feat(DataPlaneStore): implements SQL based storage for DataPlane flow requests
  core/data-plane/data-plane-framework/build.gradle.kts
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/edc/connector/dataplane/framework/store/InMemoryDataPlaneStoreTest.java
  extensions/data-plane/store/sql/data-plane-store-sql/README.md
  extensions/data-plane/store/sql/data-plane-store-sql/build.gradle.kts
  extensions/data-plane/store/sql/data-plane-store-sql/docs/schema.sql
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStore.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStoreExtension.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlDataPlaneStatements.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/DataPlaneStatements.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/postgres/PostgresDataPlaneStatements.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/data-plane/store/sql/data-plane-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/store/sql/PostgresDataPlaneStoreTest.java
  settings.gradle.kts
  spi/data-plane/data-plane-spi/build.gradle.kts
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/store/DataPlaneStore.java
  spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/testfixtures/store/DataPlaneStoreTestBase.java
Labels: enhancement

#2199 build: Remove issue type paragraph
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: build

#2179 refactor(controlPlaneApi): Adds usage of TranferProcessService
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/ControlPlaneApiExtension.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/TransferProcessControlApiController.java
  core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiController.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiController.java
  extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiController.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiController.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiController.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiController.java
  spi/common/web-spi/build.gradle.kts
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/ServiceResultHandler.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/transferprocess/TransferProcessService.java
Labels: refactoring, api

#2202 fix: avoid a security token in the response if the request is not valid
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/controller/MultipartController.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/message/MultipartResponse.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/MultipartControllerIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/controller/MultipartControllerTest.java
Labels: bug

#2204 refactor: use TransferProcessService in ArtifactRequestHandler
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/IdsMultipartApiServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/util/ResponseUtil.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/util/ResponseUtilTest.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/transferprocess/TransferProcessService.java
Labels: refactoring

#2212 chore: replace deprecated EdcSetting annotation
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/SqlDataPlaneInstanceStoreExtension.java
Labels: refactoring

#2213 chore: temporarily reinstate packaged SwaggerUI
  build.gradle.kts
  docs/swaggerui/favicon-16x16.png
  docs/swaggerui/favicon-32x32.png
  docs/swaggerui/index.css
  docs/swaggerui/index.html
  docs/swaggerui/oauth2-redirect.html
  docs/swaggerui/swagger-initializer.js
  docs/swaggerui/swagger-spec.js
  docs/swaggerui/swagger-ui-bundle.js
  docs/swaggerui/swagger-ui-bundle.js.map
  docs/swaggerui/swagger-ui-es-bundle-core.js
  docs/swaggerui/swagger-ui-es-bundle-core.js.map
  docs/swaggerui/swagger-ui-es-bundle.js
  docs/swaggerui/swagger-ui-es-bundle.js.map
  docs/swaggerui/swagger-ui-standalone-preset.js
  docs/swaggerui/swagger-ui-standalone-preset.js.map
  docs/swaggerui/swagger-ui.css
  docs/swaggerui/swagger-ui.css.map
  docs/swaggerui/swagger-ui.js
  docs/swaggerui/swagger-ui.js.map
Labels: bug

#2215 fix: checkstyle
  extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGeneratorTest.java
Labels: bug

#2210 refactor(ServiceResultHandler): changed ServiceResultHandler#mapToException
  core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/TransferProcessControlApiController.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiController.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiController.java
  extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiController.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiController.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiController.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiController.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/Failure.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/result/ResultTest.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/ServiceResultHandler.java
Labels: refactoring

#2203 feat(DataPlaneStore): adds Cosmos implementation for DataPlaneStore
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/README.md
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/build.gradle.kts
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStore.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStoreConfig.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStoreExtension.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/model/DataFlowRequestDocument.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStoreIntegrationTest.java
  settings.gradle.kts
Labels: enhancement

#2164 feat(DataPlaneInstanceStore): Implement CosmosDb based storage for DataPlaneInstance
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/build.gradle.kts
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStore.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStoreConfig.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStoreExtension.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/DataPlaneInstanceDocument.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/TestFunctions.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStoreIntegrationTest.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/DataPlaneInstanceDocumentSerializationTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/data-plane-selector-api.yaml
  settings.gradle.kts
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstance.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/store/DataPlaneInstanceStoreTestBase.java
Labels: enhancement, good first issue

#2221 fix(build): update openapi definitions
  docs/swaggerui/swagger-spec.js
  resources/openapi/openapi.yaml
  resources/openapi/yaml/api-observability.yaml
Labels: bug, documentation

#2217 refactor: move `management` api endpoints under `management` context
  extensions/common/api/api-observability/build.gradle.kts
  extensions/common/api/api-observability/src/main/java/org/eclipse/edc/api/observability/ObservabilityApiController.java
  extensions/common/api/api-observability/src/main/java/org/eclipse/edc/api/observability/ObservabilityApiExtension.java
  extensions/common/api/api-observability/src/test/java/org/eclipse/edc/api/observability/ObservabilityApiControllerTest.java
  extensions/common/api/api-observability/src/test/java/org/eclipse/edc/api/observability/ObservabilityApiExtensionTest.java
  extensions/common/api/management-api-configuration/README.md
  extensions/common/api/management-api-configuration/build.gradle.kts
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfiguration.java
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtension.java
  extensions/common/api/management-api-configuration/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtensionTest.java
  extensions/common/iam/decentralized-identity/identity-did-core/build.gradle.kts
  extensions/control-plane/api/management-api/asset-api/build.gradle.kts
  extensions/control-plane/api/management-api/build.gradle.kts
  extensions/control-plane/api/management-api/catalog-api/build.gradle.kts
  extensions/control-plane/api/management-api/contract-agreement-api/build.gradle.kts
  extensions/control-plane/api/management-api/contract-definition-api/build.gradle.kts
  extensions/control-plane/api/management-api/contract-negotiation-api/build.gradle.kts
  extensions/control-plane/api/management-api/policy-definition-api/build.gradle.kts
  extensions/control-plane/api/management-api/transfer-process-api/build.gradle.kts
  extensions/control-plane/provision/provision-http/build.gradle.kts
  extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/HttpWebhookExtension.java
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpWebhookExtensionTest.java
  extensions/control-plane/provision/provision-oauth2/build.gradle.kts
  extensions/data-plane-selector/data-plane-selector-api/build.gradle.kts
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtension.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/DataplaneSelectorApiController.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtensionTest.java
  launchers/dpf-selector/config.properties
  resources/openapi/openapi.yaml
  resources/openapi/yaml/identity-did-core.yaml
  resources/openapi/yaml/provision-oauth2.yaml
  settings.gradle.kts
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfiguration.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
Labels: refactoring

#2218 feat(HttpProvisioner): use TransferProcessService in the controller
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
  extensions/control-plane/provision/provision-http/build.gradle.kts
  extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/HttpWebhookExtension.java
  extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/webhook/HttpProvisionerWebhookApiController.java
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpProvisionerWebhookApiControllerIntegrationTest.java
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpWebhookExtensionTest.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/transferprocess/TransferProcessService.java
Labels: enhancement

#2230 feat(build): add shell script to invoke Discord webhook
  resources/ci/discord_webhook.sh
Labels: build

#2236 build: add workflow to explicitly trigger EDC jenkins
  .github/workflows/trigger_snapshot.yml
Labels: build

#2232 chore: use standard version property
  build.gradle.kts
Labels: refactoring, build

#2240 feat: add discord webhooks for issues, discussions and pull requests
  .github/workflows/discord-webhook.yml
Labels: no-changelog

#2241 build: update discord webhook
  resources/ci/discord_webhook.sh
Labels: build

#2239 feat(README): adds snapshot and nightly build badges
  README.md
Labels: documentation

#2247 chore: fix docs link
  README.md
  docs/developer/openapi.md
Labels: no-changelog

#2252 feat: support `/public` endpoint without trailing slash
  .github/workflows/assign-pr-to-project.yaml
  extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyRestService.java
  extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/mapper/ExceptionMappersIntegrationTest.java
  extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyService.java
  extensions/common/http/jetty-core/src/test/java/org/eclipse/edc/web/jetty/JettyServiceTest.java
  extensions/data-plane/data-plane-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlaneApiIntegrationTest.java
Labels: enhancement, api

#2243 feat: Add basic HttpDataAddress validation
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/asset/AssetServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/dataaddress/DataAddressValidatorImpl.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetServiceImplTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/dataaddress/DataAddressValidatorImplTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/transform/DataAddressDtoToDataAddressTransformer.java
  extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/transform/DataAddressDtoToDataAddressTransformerTest.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/edc/connector/dataplane/transfer/sync/proxy/DataPlaneTransferConsumerProxyTransformerTest.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactory.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactoryTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java
  spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceResult.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/dataaddress/DataAddressValidator.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/DataAddress.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/HttpDataAddress.java
Labels: enhancement, api

#2254 chore: Update references from `dataspaceconnector` to `edc`
  .github/ISSUE_TEMPLATE/adoption_request.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/assign-issue-to-project.yaml
  .github/workflows/first-interaction.yml
  .github/workflows/release-edc.yml
  .github/workflows/trigger_snapshot.yml
  .github/workflows/verify.yaml
  CONTRIBUTING.md
  NOTICE.md
  README.md
  build.gradle.kts
  contribution_categories.md
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/policy/PolicyEquality.java
  docs/developer/autodoc.md
  docs/developer/build-your-own-connector.md
  docs/developer/decision-records/2022-02-03-integration-testing/README.md
  docs/developer/decision-records/2022-02-07-micrometer-metrics/README.md
  docs/developer/decision-records/2022-04-21-dpf-blob-data-transfer/README.md
  docs/developer/decision-records/2022-08-11-versioning_and_artifacts/README.md
  docs/developer/decision-records/2022-09-18-ids-catalog-request-filtering/README.md
  docs/developer/decision-records/2022-10-20-trust-framework-adoption-repository/README.md
  docs/developer/testing.md
  docs/developer/version-catalogs.md
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformer.java
  gradle.properties
  pr_etiquette.md
  resources/azure/testing/.env.example
  resources/ci/discord_webhook.sh
Labels: documentation, refactoring, build

#2264 fix(javadoc): removed erronous tag
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java
Labels: bug

#2263 fix(ContractNegotiationApi): wrong DTO definition
  docs/swaggerui/swagger-spec.js
  docs/swaggerui/swagger-ui-bundle.js
  docs/swaggerui/swagger-ui-bundle.js.map
  docs/swaggerui/swagger-ui-es-bundle-core.js
  docs/swaggerui/swagger-ui-es-bundle-core.js.map
  docs/swaggerui/swagger-ui-es-bundle.js
  docs/swaggerui/swagger-ui-es-bundle.js.map
  docs/swaggerui/swagger-ui-standalone-preset.js
  docs/swaggerui/swagger-ui-standalone-preset.js.map
  docs/swaggerui/swagger-ui.css
  docs/swaggerui/swagger-ui.css.map
  docs/swaggerui/swagger-ui.js
  docs/swaggerui/swagger-ui.js.map
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/contract-negotiation-api.yaml
Labels: bug

#2237 refactor(TransferProcessStore): replaces create and update api with save with support of upsert
  core/control-plane/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/transferprocess/InMemoryTransferProcessStore.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/command/handlers/SingleTransferProcessCommandHandler.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/CancelTransferCommandHandlerTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/CompleteTransferCommandHandlerTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/FailTransferCommandHandlerTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplIntegrationTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpProvisionerWebhookApiControllerIntegrationTest.java
  extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStore.java
  extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStoreIntegrationTest.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/transferprocess/PostgresTransferProcessStoreTest.java
  samples/04.2-modify-transferprocess/simulator/src/main/java/org/eclipse/edc/sample/extension/transfer/TransferSimulationExtension.java
  samples/04.2-modify-transferprocess/watchdog/src/main/java/org/eclipse/edc/sample/extension/watchdog/CheckTimeoutCommandHandler.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/store/TransferProcessStore.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TransferProcessStoreTestBase.java
Labels: refactoring

#2266 fix(build): only the upstream project may trigger jenkins
  .github/workflows/trigger_snapshot.yml
Labels: bug

#2250 refactor: move `control` api endpoints under `control` context
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java
  core/control-plane/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  core/control-plane/control-plane-api/build.gradle.kts
  core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/ControlPlaneApiExtension.java
  core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/ControlPlaneApiExtensionTest.java
  core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
  extensions/common/api/control-api-configuration/README.md
  extensions/common/api/control-api-configuration/build.gradle.kts
  extensions/common/api/control-api-configuration/src/main/java/org/eclipse/edc/connector/api/control/configuration/ControlApiConfiguration.java
  extensions/common/api/control-api-configuration/src/main/java/org/eclipse/edc/connector/api/control/configuration/ControlApiConfigurationExtension.java
  extensions/common/api/control-api-configuration/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyService.java
  extensions/common/http/jetty-core/src/test/java/org/eclipse/edc/web/jetty/JettyServiceTest.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/build.gradle.kts
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/edc/connector/dataplane/transfer/sync/DataPlaneTransferSyncExtension.java
  extensions/data-plane/data-plane-api/build.gradle.kts
  extensions/data-plane/data-plane-api/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlaneApiExtension.java
  resources/openapi/openapi.yaml
  settings.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
Labels: refactoring
