Repository eclipse-edc/Connector, pull requests merged in 2022-12, with the labels that each got.

#2267 feat(dataPlane): register a different resolve strategy when working with embedded data-plane
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/README.md
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/edc/connector/dataplane/transfer/sync/DataPlaneTransferSyncExtension.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/edc/connector/dataplane/transfer/sync/proxy/EmbeddedDataPlaneTransferProxyResolve.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/edc/connector/dataplane/transfer/sync/proxy/EmbeddedPlaneTransferProxyResolverTest.java
  extensions/data-plane/data-plane-api/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlaneApiExtension.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataPlanePublicApiUrl.java
Labels: enhancement

#2262 refactor: Rename `ids` api context to `protocol`
  data-protocols/ids/ids-api-configuration/build.gradle.kts
  data-protocols/ids/ids-api-configuration/src/main/java/org/eclipse/edc/protocol/ids/api/configuration/IdsApiConfigurationExtension.java
  data-protocols/ids/ids-api-configuration/src/test/java/org/eclipse/edc/protocol/ids/api/configuration/IdsApiConfigurationExtensionTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/IdsMultipartApiServiceExtension.java
Labels: refactoring, api

#2280 feat(build): add workflow_dispatch event trigger
  .github/workflows/verify.yaml
Labels: build

#2282 refactor(httpReceiver): rename module http-receiver to transfer-pull-http-receiver
  extensions/README.md
  extensions/control-plane/transfer/transfer-data-plane/README.md
  extensions/control-plane/transfer/transfer-data-plane/build.gradle.kts
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/ConsumerPullTransferKeyPairExtension.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/ConsumerPullTransferProxyResolverExtension.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneConfig.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtension.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneDefaultServicesExtension.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/api/ConsumerPullTransferTokenValidationApi.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/api/ConsumerPullTransferTokenValidationApiController.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowController.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferEmbeddedProxyResolver.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferEndpointDataReferenceServiceImpl.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferProxyResolver.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferProxyTransformer.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferRemoteProxyResolver.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferTokenDecorator.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/security/ConsumerPullTransferKeyPair.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/security/NoopDataEncrypter.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/security/PublicKeyParser.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/validation/ContractValidationRule.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/validation/ExpirationDateValidationRule.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/ConsumerPullTransferKeyPairExtensionTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/ConsumerPullTransferProxyResolverExtensionTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtensionTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/api/ConsumerPullTransferTokenValidationApiControllerTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowControllerTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowControllerTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferEmbeddedProxyResolverTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferEndpointDataReferenceServiceImplTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferProxyTransformerTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferRemoteProxyResolverTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferTokenDecoratorTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/security/PublicKeyParserTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/validation/ContractValidationRuleTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/validation/ExpirationDateValidationRuleTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/resources/ec-pubkey.pem
  extensions/control-plane/transfer/transfer-data-plane/src/test/resources/rsa-pubkey.pem
  extensions/control-plane/transfer/transfer-pull-http-receiver/build.gradle.kts
  extensions/control-plane/transfer/transfer-pull-http-receiver/src/main/java/org/eclipse/edc/connector/receiver/http/HttpEndpointDataReferenceReceiver.java
  extensions/control-plane/transfer/transfer-pull-http-receiver/src/main/java/org/eclipse/edc/connector/receiver/http/HttpEndpointDataReferenceReceiverExtension.java
  extensions/control-plane/transfer/transfer-pull-http-receiver/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/transfer/transfer-pull-http-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/HttpEndpointDataReferenceReceiverTest.java
  samples/04.0-file-transfer/transfer-file/build.gradle.kts
  samples/05-file-transfer-cloud/transfer-file/build.gradle.kts
  settings.gradle.kts
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/runtimes/azure-data-factory-transfer-provider/build.gradle.kts
  system-tests/runtimes/azure-storage-transfer-provider/build.gradle.kts
  system-tests/runtimes/file-transfer-provider/build.gradle.kts
Labels: refactoring

#2285 docs: provide decision record for EdcHttpClient
  docs/developer/decision-records/2022-12-05-edc-http-client/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#2304 fix: jenkins badges
  README.md
Labels: documentation, build

#2297 feat(oauth): renames edc.oauth.public.key.alias to edc.oauth.certificate.alias
  extensions/common/iam/oauth2/oauth2-core/README.md
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2Extension.java
  extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/Oauth2ExtensionTest.java
  extensions/common/iam/oauth2/oauth2-daps/src/test/java/org/eclipse/edc/iam/oauth2/daps/DapsIntegrationTest.java
  launchers/ids-connector/README.md
  launchers/ids-connector/config.properties
Labels: enhancement

#2311 docs: add decision record for transaction synchronization
  docs/developer/decision-records/2022-12-07-transaction-synchronization/README.md
  docs/developer/decision-records/README.md
Labels: no-changelog

#2321 fix: remove `DataPlanePublicApiUrl`
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/ConsumerPullTransferProxyResolverExtension.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferEmbeddedProxyResolver.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferProxyResolverImpl.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/ConsumerPullTransferProxyResolverExtensionTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferEmbeddedProxyResolverTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferProxyResolverImplTest.java
  extensions/data-plane/data-plane-api/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlaneApiExtension.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataPlanePublicApiUrl.java
Labels: bug

#2312 feat: add support for transaction synchronization
  extensions/common/transaction/transaction-atomikos/src/main/java/org/eclipse/edc/transaction/atomikos/AtomikosTransactionContext.java
  extensions/common/transaction/transaction-atomikos/src/test/java/org/eclipse/edc/transaction/atomikos/AtomikosTransactionContextTest.java
  extensions/common/transaction/transaction-local/src/main/java/org/eclipse/edc/transaction/local/LocalTransactionContext.java
  extensions/common/transaction/transaction-local/src/test/java/org/eclipse/edc/transaction/local/LocalTransactionContextTest.java
  spi/common/transaction-spi/src/main/java/org/eclipse/edc/transaction/spi/NoopTransactionContext.java
  spi/common/transaction-spi/src/main/java/org/eclipse/edc/transaction/spi/TransactionContext.java
  spi/common/transaction-spi/src/test/java/org/eclipse/edc/transaction/spi/NoopTransactionContextTest.java
Labels: enhancement, core feature

#2315 fix: make negotiation api launch a `decline` command
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/EntitySendRetryManager.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/SendRetryManager.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractNegotiationCommandExtension.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandler.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/ContractNegotiationCommandQueueIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandlerTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImplTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiControllerIntegrationTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/command/DeclineNegotiationCommand.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java
Labels: bug

#2325 fix: correctly transform assetId back from IDS infomodel
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ContractAgreementHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/MultipartControllerIntegrationTest.java
  data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/edc/protocol/ids/transform/type/contract/ContractAgreementFromIdsContractAgreementTransformer.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/edc/protocol/ids/transform/ContractAgreementFromIdsContractAgreementTransformerTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
Labels: bug

#2246 chore(ContractValidationService): change return type of validateAgreement from boolean to Result
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/client/MultipartDispatcherIntegrationTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ContractValidationService.java
Labels: enhancement

#2328 chore: remove embedded swaggerUI
  docs/developer/openapi.md
  docs/swaggerui/favicon-16x16.png
  docs/swaggerui/favicon-32x32.png
  docs/swaggerui/index.css
  docs/swaggerui/index.html
  docs/swaggerui/oauth2-redirect.html
  docs/swaggerui/swagger-initializer.js
  docs/swaggerui/swagger-spec.js
  docs/swaggerui/swagger-ui-bundle.js
  docs/swaggerui/swagger-ui-bundle.js.map
  docs/swaggerui/swagger-ui-es-bundle-core.js
  docs/swaggerui/swagger-ui-es-bundle-core.js.map
  docs/swaggerui/swagger-ui-es-bundle.js
  docs/swaggerui/swagger-ui-es-bundle.js.map
  docs/swaggerui/swagger-ui-standalone-preset.js
  docs/swaggerui/swagger-ui-standalone-preset.js.map
  docs/swaggerui/swagger-ui.css
  docs/swaggerui/swagger-ui.css.map
  docs/swaggerui/swagger-ui.js
  docs/swaggerui/swagger-ui.js.map
Labels: documentation

#2338 fix(docs): resolve markdown syntax errors
  README.md
  docs/developer/architecture/README.md
  docs/developer/architecture/terminology.md
  docs/developer/decision-records/2022-02-10-code-coverage/README.md
  docs/developer/decision-records/2022-04-21-dpf-blob-data-transfer/README.md
  docs/developer/metrics.md
  extensions/common/events/events-cloud-http/README.md
  launchers/ids-connector/README.md
  samples/04.1-file-transfer-listener/README.md
  samples/04.3-open-telemetry/README.md
  samples/README.md
Labels: documentation

#2323 refactor(headers): fix checkstyle on headers and configure error for header check
  core/common/junit/src/main/java/org/eclipse/edc/junit/annotations/ApiTest.java
  core/common/junit/src/main/java/org/eclipse/edc/junit/annotations/ComponentTest.java
  core/common/junit/src/main/java/org/eclipse/edc/junit/annotations/EndToEndTest.java
  core/common/junit/src/main/java/org/eclipse/edc/junit/annotations/IntegrationTest.java
  core/common/junit/src/main/java/org/eclipse/edc/junit/annotations/OpenTelemetryIntegrationTest.java
  core/common/junit/src/main/java/org/eclipse/edc/junit/annotations/PerformanceTest.java
  core/control-plane/control-plane-api-client/src/main/java/org/eclipse/edc/connector/api/client/ControlPlaneApiClientExtension.java
  core/control-plane/control-plane-api-client/src/main/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClient.java
  core/control-plane/control-plane-api-client/src/main/java/org/eclipse/edc/connector/api/client/transferprocess/model/TransferProcessFailRequest.java
  core/control-plane/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/ControlPlaneApiExtension.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/TransferProcessControlApi.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/TransferProcessControlApiController.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/model/TransferProcessFailStateDto.java
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultServicesExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/controller/MultipartControllerTest.java
  extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/Oauth2ExtensionTest.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/store/AbstractSqlStore.java
  extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlStoreSetupExtension.java
  extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-gcs/src/test/java/org/eclipse/edc/connector/provision/gcp/GcsConsumerResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-oauth2/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProviderResourceDefinitionGeneratorTest.java
  extensions/control-plane/transfer/transfer-pull-http-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/HttpEndpointDataReferenceReceiverTest.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStore.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStoreExtension.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/model/DataFlowRequestDocument.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStoreIntegrationTest.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStore.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStoreExtension.java
  resources/edc-checkstyle-config.xml
  samples/04.0-file-transfer/status-checker/src/main/java/org/eclipse/edc/sample/extension/checker/SampleFileStatusChecker.java
  samples/04.0-file-transfer/status-checker/src/main/java/org/eclipse/edc/sample/extension/checker/SampleStatusCheckerExtension.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfiguration.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfigurer.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfigurerImpl.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceSettings.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/ServiceResultHandler.java
  spi/common/web-spi/src/test/java/org/eclipse/edc/web/spi/configuration/WebServiceConfigurerImplTest.java
  spi/control-plane/control-plane-api-client-spi/src/main/java/org/eclipse/edc/connector/api/client/spi/transferprocess/NoopTransferProcessClient.java
  spi/control-plane/control-plane-api-client-spi/src/main/java/org/eclipse/edc/connector/api/client/spi/transferprocess/TransferProcessApiClient.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/asset/AssetService.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/catalog/CatalogService.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractagreement/ContractAgreementService.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/callback/ControlPlaneApiUrl.java
  spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/testfixtures/store/DataPlaneStoreTestBase.java
Labels: refactoring, build

#2339 docs(adoption): add data tracking PoC to known friends list
  known_friends.md
Labels: documentation

#2331 refactor: remove negotiation dead code
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandlerTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
  extensions/control-plane/data-plane-transfer/build.gradle.kts
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ConsumerContractNegotiationManager.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ProviderContractNegotiationManager.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ContractValidationService.java
Labels: refactoring

#2336 fix: make logical constraint serdes work
  data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/serialization/IdsTypeManagerUtil.java
  data-protocols/ids/ids-jsonld-serdes/src/test/java/org/eclipse/edc/protocol/ids/jsonld/SerializationTest.java
  spi/common/transaction-spi/src/test/java/org/eclipse/edc/transaction/spi/NoopTransactionContextTest.java
Labels: bug

#2330 chore(EndpointDataReferenceReceiverRegistry): make the transfer process fail if no receivers are registered
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImplTest.java
Labels: enhancement

#2348 feat(api): improve error message on conflict error
  extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/mapper/EdcApiExceptionMapper.java
  extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/mapper/EdcApiExceptionMapperTest.java
  extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/AssetApiControllerTest.java
  extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiController.java
  extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiControllerTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiControllerTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiControllerTest.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/ObjectConflictException.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/ObjectExistsException.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/ServiceResultHandler.java
Labels: enhancement, api

#2324 refactor: switch DataPlaneInstance implementation to Class
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferProxyResolverImplTest.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtension.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/TestFunctions.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataplaneSelectorApiControllerIntegrationTest.java
  extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/TestFunctions.java
  extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/client/RemoteDataPlaneSelectorClientTest.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/TestFunctions.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStoreIntegrationTest.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/sql/PostgresDataPlaneInstanceStoreTest.java
  gradle.properties
  resources/openapi/openapi.yaml
  resources/openapi/yaml/management-api/data-plane-selector-api.yaml
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstance.java
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstanceImpl.java
  spi/data-plane-selector/data-plane-selector-spi/src/test/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstanceTest.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/TestDataPlaneInstance.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/TestFunctions.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/store/DataPlaneInstanceStoreTestBase.java
Labels: refactoring

#2352 fix: project url
  .github/workflows/assign-issue-to-project.yaml
  .github/workflows/assign-pr-to-project.yaml
  CONTRIBUTING.md
Labels: bug

#2358 feat(GitHub): add support for new GitHub project
  .github/workflows/add-to-project.yml
  .github/workflows/assign-issue-to-project.yaml
  .github/workflows/assign-pr-to-project.yaml
Labels: build

#2355 feat: log `Failsafe` events
  core/common/connector-core/README.md
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreDefaultServicesExtension.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/RetryPolicyFactory.java
  core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/RetryPolicyFactoryTest.java
Labels: enhancement

#2366 fix: set correct api type for transferprocess API
  extensions/control-plane/api/management-api/transfer-process-api/build.gradle.kts
  resources/openapi/yaml/management-api/transfer-process-api.yaml
Labels: bug, api

#2380 build(badges): fix build badge
  README.md
Labels: build

#2276 feat(httpProxy): add module for http dynamic receivers
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/model/TransferProcessDto.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferProcessToTransferProcessDtoTransformer.java
  extensions/control-plane/store/sql/transfer-process-store-sql/docs/schema.sql
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/TransferProcessStoreStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/DataRequestMapping.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/TransferProcessMapping.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/README.md
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/build.gradle.kts
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiver.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiverExtension.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiverTest.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/dynamic/TestFunctions.java
  settings.gradle.kts
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java
  spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcessTest.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TransferProcessStoreTestBase.java
Labels: enhancement

#2346 build: upgrade the GradleVersion to 7.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: stale, dependencies

#2371 feat(assetApi): adds endpoint for getting a DataAddress of an Asset
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApi.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiController.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiExtension.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/transform/DataAddressToDataAddressDtoTransformer.java
  extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/AssetApiControllerIntegrationTest.java
  extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/AssetApiControllerTest.java
  resources/openapi/yaml/management-api/asset-api.yaml
Labels: api
