Repository eclipse-edc/Connector, pull requests merged in 2022-04, with the labels that each got.

#1040 chore: Provisioning types cleanup
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
  core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/TestProvisionedDataDestinationResource.java
  core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
  extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketProvisionedResource.java
  extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketProvisioner.java
  extensions/aws/s3/s3-provision/src/test/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketProvisionedResourceTest.java
  extensions/aws/s3/s3-provision/src/test/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3StatusCheckerIntegrationTest.java
  extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerProvisionedResource.java
  extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageProvisioner.java
  extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerProvisionedResourceTest.java
  extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerStatusCheckerIntegrationTest.java
  extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageProvisionerTest.java
  extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderProvisioner.java
  extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderProvisionerTest.java
  samples/04.2-modify-transferprocess/simulator/src/main/java/org/eclipse/dataspaceconnector/samples/sample042/TransferSimulationExtension.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResource.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedDataAddressResource.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedDataDestinationResource.java
  spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResourceTest.java
Labels: no-changelog

#1001 DPF: share thread pool
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/micrometer/src/main/java/org/eclipse/dataspaceconnector/metrics/micrometer/MicrometerExecutorInstrumentation.java
  core/micrometer/src/main/java/org/eclipse/dataspaceconnector/metrics/micrometer/MicrometerExtension.java
  extensions/azure/data-plane/storage/src/main/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/DataPlaneAzureStorageExtension.java
  extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtension.java
  extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImpl.java
  extensions/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtensionTest.java
  extensions/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/e2e/EndToEndTest.java
  extensions/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpExtension.java
  extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/DataTransferExecutorServiceContainer.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ExecutorInstrumentation.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ExecutorInstrumentationImplementation.java
Labels: no-changelog

#1042 CI: checkstyle rule for Java file headers: additional fixes
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/util/CyclicDependencyException.java
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/util/TopologicalSort.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/message/DataRequestMessageSender.java
  extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiControllerIntegrationTest.java
  extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerTest.java
  extensions/azure/azure-test/README.md
  extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/DataTransferExecutorServiceContainer.java
  launchers/data-loader-cli/README.md
  launchers/data-loader-cli/src/test/java/org/eclipse/dataspaceconnector/examples/JsonFileGenerator.java
  samples/04.2-modify-transferprocess/simulator/src/main/java/org/eclipse/dataspaceconnector/samples/sample042/TransferSimulationExtension.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ExecutorInstrumentationImplementation.java
Labels: no-changelog

#1053 fix: Repair `InMemoryPolicyStoreExtension`
  extensions/in-memory/policy-store-memory/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
Labels: bug, no-changelog

#1064 Bug fix: Default value if the env var is null or blank
  common/util/src/main/java/org/eclipse/dataspaceconnector/common/configuration/ConfigurationFunctions.java
Labels: no-changelog

#1059 Federated Catalog Cache: fixed logging statement
  extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
Labels: no-changelog

#1062 Cleanup: Adds smaller refactorings in the `SqlContractDefinitionStore`
  extensions/sql/contract-definition/README.md
  extensions/sql/contract-definition/docs/README.md
  extensions/sql/contract-definition/docs/er.png
  extensions/sql/contract-definition/docs/schema.sql
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/ConfigurationKeys.java
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/ContractDefinitionStatements.java
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/Limit.java
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/PostgresStatements.java
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreExtension.java
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionTables.java
  extensions/sql/contract-definition/store/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/sql/contract-definition/store/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreTest.java
  extensions/sql/contract-definition/store/src/test/resources/schema.sql
Labels: no-changelog

#1018 CI: control test verbosity
  build.gradle.kts
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/runtime/BaseRuntime.java
  docs/testing.md
  extensions/catalog/federated-catalog-cache/build.gradle.kts
  extensions/data-plane/integration-tests/build.gradle.kts
  launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcExtension.java
  samples/other/custom-runtime/src/main/java/org/eclipse/dataspaceconnector/demo/runtime/CustomRuntime.java
  system-tests/e2e-transfer-test/runner/build.gradle.kts
  system-tests/tests/build.gradle.kts
Labels: no-changelog

#1069 Bug fix: Default value if the environment variable is null or blank
  common/util/build.gradle.kts
  common/util/src/main/java/org/eclipse/dataspaceconnector/common/configuration/ConfigurationFunctions.java
  common/util/src/test/java/org/eclipse/dataspaceconnector/common/configuration/ConfigurationFunctionsTest.java
Labels: no-changelog

#1081 sql: Fix sql-asset-index service descriptor (fixes #1080)
  extensions/sql/asset/index/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
Labels: no-changelog

#1010 CI: checkstyle miscellaneous rules
  resources/edc-checkstyle-config.xml
Labels: no-changelog

#1075 Contract negotiation Postgres DDL: allow null correlation id for type consumer
  extensions/sql/contract-negotiation-store/docs/ddl_postgres.sql
Labels: no-changelog

#1032 feat: add CODEOWNERS file to repository
  CODEOWNERS
  CONTRIBUTING.md
Labels: no-changelog

#1083 sql: Fix sql-policy-store service descriptor (fixes #1081)
  extensions/sql/policy/store/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
Labels: no-changelog

#1091 extensions: add custom policy field to NegotiationInitiateRequestDto
  extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/ContractOfferDescription.java
  extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformer.java
  extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/TestFunctions.java
  extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformerTest.java
  spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java
Labels: no-changelog

#1051 Cosmos DB integration tests: pick up TransferProcess after the lease expired
  docs/developer/decision-records/2022-03-30-cosmosdb-lease-mechanism/README.md
  extensions/azure/cosmos/contract-negotiation-store-cosmos/build.gradle.kts
  extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
  extensions/azure/cosmos/cosmos-common/build.gradle.kts
  extensions/azure/cosmos/cosmos-common/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/cosmos/util/StoredProcedureTestUtils.java
  extensions/azure/cosmos/transfer-process-store-cosmos/build.gradle.kts
  extensions/azure/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreIntegrationTest.java
Labels: no-changelog

#1093 CI: Add InnerAssignment checkstyle module
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionHandler.java
  data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsResourceCatalogToDataCatalogTransformer.java
  extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/HttpApiKeyAuthContainerRequestFilter.java
  resources/edc-checkstyle-config.xml
Labels: no-changelog

#1099 chore: Add missing documentation
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CancelTransferCommandHandler.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/DeprovisionRequestHandler.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/observe/TransferProcessObservableImpl.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/ProvisionCallbackDelegate.java
  extensions/iam/decentralized-identity/registration-service-api/src/main/java/org/eclipse/dataspaceconnector/samples/identity/registrationservice/api/RegistrationServiceApiExtension.java
  extensions/iam/decentralized-identity/registration-service-api/src/main/java/org/eclipse/dataspaceconnector/samples/identity/registrationservice/api/RegistrationServiceController.java
  spi/catalog-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/catalog/Catalog.java
  spi/catalog-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/catalog/CatalogRequest.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/EdcSetting.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/command/BoundedCommandQueue.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/command/CommandHandler.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/command/CommandHandlerRegistry.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/command/CommandRunner.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/iam/RegistrationService.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/monitor/MultiplexingMonitor.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/SortOrder.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/response/ResponseFailure.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/result/AbstractResult.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/result/Failure.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/result/Result.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/retry/WaitStrategy.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/security/KeyParser.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/security/PrivateKeyResolver.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/security/VaultEntry.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/security/VaultPrivateKeyResolver.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/configuration/ConfigFactory.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/configuration/ConfigImpl.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/health/LivenessProvider.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/health/ReadinessProvider.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/health/StartupStatusProvider.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/injection/EdcInjectionException.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/telemetry/TraceCarrier.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/DataAddress.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/edr/EndpointDataReferenceMessage.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/metadata/MetadataRequest.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/metadata/QueryRequest.java
Labels: no-changelog

#1100 docs: update CHANGELOG.md
  CHANGELOG.md
Labels: no-changelog

#1103 Bugfix: update `ContractAgreement`, when `ContractNegotiation` is updated
  extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/ContractNegotiationStatements.java
  extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresStatements.java
  extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
  extensions/sql/contract-negotiation-store/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java
  extensions/sql/contract-negotiation-store/src/test/resources/schema.sql
Labels: no-changelog

#1104 extensions: implement TransferProcess Data Management Api
  extensions/api/data-management/transferprocess/build.gradle.kts
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApi.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiController.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtension.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferRequestDto.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessService.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessServiceImpl.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferRequestDtoToDataRequestTransformer.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiApiControllerTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtensionTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessServiceImplTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferRequestDtoToDataRequestTransformerTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/policydefinition.yaml
  resources/openapi/yaml/transferprocess.yaml
Labels: no-changelog

#1113 datamanagement: deprecate control api
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractRequestHandler.java
  extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ClientApi.java
  extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ClientControlCatalogApi.java
  extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ClientControlCatalogApiController.java
  extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ClientController.java
  extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ControlApiServiceExtension.java
  extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/response/NegotiationStatusResponse.java
  extensions/api/data-management/api-configuration/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/configuration/DataManagementApiConfigurationExtension.java
  extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiExtension.java
  extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiExtension.java
  extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiController.java
  extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiExtension.java
  extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformer.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtension.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessServiceImpl.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessServiceImplTest.java
  launchers/basic/build.gradle.kts
  launchers/ids-connector/README.md
  launchers/ids-connector/build.gradle.kts
  launchers/ids-connector/config.properties
  resources/openapi/openapi.yaml
  resources/openapi/yaml/control.yaml
  samples/04.0-file-transfer/README.md
  samples/04.0-file-transfer/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ApiEndpointExtension.java
  samples/04.0-file-transfer/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
  samples/04.0-file-transfer/consumer/build.gradle.kts
  samples/04.0-file-transfer/consumer/config.properties
  samples/04.0-file-transfer/contractoffer.json
  samples/04.1-file-transfer-listener/README.md
  samples/04.1-file-transfer-listener/consumer/build.gradle.kts
  samples/04.1-file-transfer-listener/consumer/config.properties
  samples/04.2-modify-transferprocess/consumer/build.gradle.kts
  samples/04.2-modify-transferprocess/consumer/config.properties
  samples/04.2-modify-transferprocess/contractoffer.json
  samples/04.3-open-telemetry/README.md
  samples/04.3-open-telemetry/consumer/build.gradle.kts
  samples/05-file-transfer-cloud/README.md
  samples/05-file-transfer-cloud/consumer/build.gradle.kts
  samples/05-file-transfer-cloud/consumer/config.properties
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/e2e-transfer-test/control-plane/src/main/java/org/eclipse/dataspaceconnector/test/e2e/ControlPlaneTestController.java
  system-tests/e2e-transfer-test/control-plane/src/main/java/org/eclipse/dataspaceconnector/test/e2e/ControlPlaneTestExtension.java
  system-tests/e2e-transfer-test/control-plane/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/EndToEndTransferTest.java
  system-tests/minikube/minikube-test.sh
  system-tests/runtimes/file-transfer-consumer/build.gradle.kts
  system-tests/runtimes/file-transfer-consumer/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ApiEndpointExtension.java
  system-tests/runtimes/file-transfer-consumer/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
  system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/FileTransferIntegrationTest.java
  system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/FileTransferLocalSimulation.java
  system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/remote/FileTransferAsClientSimulation.java
  system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/utils/FileTransferSimulationUtils.java
  system-tests/tests/src/test/resources/contractoffer.json
Labels: no-changelog

#1115 CI: Report for tagged tests
  .github/actions/run-tests/action.yml
  .github/workflows/integrationtests.yaml
  .github/workflows/verify.yaml
  docs/testing.md
Labels: no-changelog

#1136 CI: add checkstyle rule for Java file headers
  .github/workflows/verify.yaml
  build.gradle.kts
  buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/DependencyRulesPlugin.java
  buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/DependencyRulesPluginExtension.java
  buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/DependencyRulesTask.java
  common/util/src/test/java/org/eclipse/dataspaceconnector/common/configuration/ConfigurationFunctionsTest.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/SendRetryManager.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessSendRetryManager.java
  core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessSendRetryManagerTest.java
  extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/exception/mappers/EdcApiExceptionMapper.java
  extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyService.java
  extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyServiceImpl.java
  extensions/api/data-management/policydefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/TestFunctions.java
  extensions/api/data-management/policydefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyServiceImplTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferRequestDtoToDataRequestTransformerTest.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/DataPlaneS3Extension.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSink.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSinkFactory.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSource.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSourceFactory.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/validation/CompositeValidationRule.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/validation/EmptyValueValidationRule.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/validation/S3DataAddressCredentialsValidationRule.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/validation/S3DataAddressValidationRule.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/validation/ValidationRule.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/DataPlaneS3ExtensionTest.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataPlaneIntegrationTest.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSinkFactoryTest.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSourceFactoryTest.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/TestFunctions.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/validation/ValidationRuleTest.java
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/S3CoreExtension.java
  extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/TestFunctions.java
  extensions/azure/cosmos/cosmos-common/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/cosmos/util/StoredProcedureTestUtils.java
  extensions/data-plane/integration-tests/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpPullIntegrationTests.java
  extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/config/ConfigParserTest.java
  extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderProvisionerTest.java
  extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderResourceDefinitionGeneratorTest.java
  extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderResourceDefinitionTest.java
  extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
  extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProvisionerRequestTest.java
  resources/edc-checkstyle-config.xml
  spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/result/ResultTest.java
  spi/policy-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/store/PolicyStore.java
Labels: no-changelog

#1114 ids: IDS policy fixes
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/policy/CustomIdsConstraintDeserializer.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/policy/IdsConstraintTest.java
  extensions/policy/ids-policy/src/main/java/org/eclipse/dataspaceconnector/ids/policy/IdsPolicyExtension.java
Labels: bug, no-changelog

#1170 fix: publish data-plane-azure-common artifact
  extensions/azure/data-plane/common/build.gradle.kts
Labels: bug, no-changelog

#1143 Feature: use @component test in sql tests
  build.gradle.kts
  extensions/sql/asset-index-sql/build.gradle.kts
  extensions/sql/asset-index-sql/src/test/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlAssetIndexTest.java
  extensions/sql/contract-definition-store-sql/build.gradle.kts
  extensions/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreTest.java
  extensions/sql/contract-negotiation-store-sql/build.gradle.kts
  extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java
  extensions/sql/policy-store-sql/build.gradle.kts
  extensions/sql/policy-store-sql/src/test/java/org/eclipse/dataspaceconnector/slq/policy/store/SqlPolicyStoreTest.java
  extensions/sql/transfer-process-store-sql/build.gradle.kts
  extensions/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStoreTest.java
Labels: no-changelog

#1167 CI: add checkstyle rule for MissingDeprecated
  extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/response/NegotiationStatusResponse.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/IdentityHub.java
  resources/edc-checkstyle-config.xml
Labels: no-changelog

#1165 CI: add checkstyle rule for StaticVariableName
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/monitor/MonitorProvider.java
  extensions/azure/vault/src/test/java/org/eclipse/dataspaceconnector/core/security/azure/AzureCertificateResolverTest.java
  extensions/iam/oauth2/oauth2-core/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/core/jwt/FingerprintTest.java
  resources/edc-checkstyle-config.xml
Labels: no-changelog

#1161 SystemTests: Use Datamanagment API to initiate file transfer
  system-tests/runtimes/file-transfer-consumer/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ApiEndpointExtension.java
  system-tests/runtimes/file-transfer-consumer/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
  system-tests/runtimes/file-transfer-consumer/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/utils/FileTransferSimulationUtils.java
Labels: no-changelog

#1191 Bugfix: Skip authentication of OPTIONS requests
  extensions/api/auth-spi/src/main/java/org/eclipse/dataspaceconnector/api/auth/AuthenticationRequestFilter.java
  extensions/api/auth-spi/src/test/java/org/eclipse/dataspaceconnector/api/auth/AuthenticationRequestFilterTest.java
Labels: bug, no-changelog

#1187 DPF: fix Maven artifact names
  extensions/data-plane-selector/selector-api/build.gradle.kts
  extensions/data-plane-selector/selector-core/build.gradle.kts
Labels: no-changelog

#1186 Azure: fix ServiceExtension file location
  extensions/azure/data-plane/storage/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
Labels: no-changelog

#1194 Samples: Use Datamanagment API to initiate file transfer
  samples/04.0-file-transfer/README.md
  samples/04.0-file-transfer/api/build.gradle.kts
  samples/04.0-file-transfer/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ApiEndpointExtension.java
  samples/04.0-file-transfer/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
  samples/04.0-file-transfer/api/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  samples/04.0-file-transfer/consumer/build.gradle.kts
  samples/04.0-file-transfer/filetransfer.json
  samples/04.1-file-transfer-listener/README.md
  samples/04.1-file-transfer-listener/consumer/build.gradle.kts
  samples/04.3-open-telemetry/README.md
  samples/04.3-open-telemetry/attachments/contract-negotiation-trace.png
  samples/04.3-open-telemetry/attachments/file-transfer-trace.png
  samples/04.3-open-telemetry/consumer/build.gradle.kts
  samples/04.3-open-telemetry/contractoffer.json
  samples/04.3-open-telemetry/docker-compose.yaml
  samples/04.3-open-telemetry/filetransfer.json
  samples/04.3-open-telemetry/input-file.txt
  settings.gradle.kts
Labels: no-changelog

#1166 CI: add checkstyle rule for RedundantModifier
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImpl.java
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/monitor/MonitorProvider.java
  core/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/ReflectiveObjectFactoryTest.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/command/ContractNegotiationCommandQueueIntegrationTest.java
  core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/AbstractDescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/AbstractMultipartControllerIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/transform/IdsTransformerRegistryImpl.java
  data-protocols/ids/ids-spi/src/test/java/org/eclipse/dataspaceconnector/ids/IdsIdParserTest.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/IdsTransformServiceExtensionTest.java
  extensions/api/auth-basic/src/main/java/org/eclipse/dataspaceconnector/api/auth/BasicAuthenticationService.java
  extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/HttpApiKeyAuthContainerRequestFilter.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSource.java
  extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/LimitClause.java
  extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/OffsetClause.java
  extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/OrderByClause.java
  extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/WhereClause.java
  extensions/azure/data-plane/storage/src/main/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/pipeline/AzureStorageDataSource.java
  extensions/azure/events/src/main/java/org/eclipse/dataspaceconnector/events/azure/AzureEventGridPublisher.java
  extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/management/PartitionManagerImplIntegrationTest.java
  extensions/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/e2e/EndToEndTest.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpDataSource.java
  extensions/data-plane/integration-tests/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpPullIntegrationTests.java
  extensions/dataloading/src/test/java/org/eclipse/dataspaceconnector/dataloading/TestEntity.java
  extensions/iam/daps/src/test/java/org/eclipse/dataspaceconnector/iam/daps/TestExtensions.java
  extensions/iam/decentralized-identity/identity-did-service/src/test/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityServiceTest.java
  extensions/in-memory/did-document-store-inmem/src/main/java/org/eclipse/dataspaceconnector/samples/identity/did/InMemoryDidDocumentStore.java
  extensions/policy/ids-policy/src/test/java/org/eclipse/dataspaceconnector/ids/policy/MockPolicyContext.java
  extensions/sql/asset-index-sql/src/main/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlConditionExpression.java
  extensions/sql/asset-index-sql/src/test/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlAssetIndexTest.java
  extensions/sql/common-sql/src/main/java/org/eclipse/dataspaceconnector/sql/datasource/PooledDataSourceConnection.java
  extensions/sql/common-sql/src/test/java/org/eclipse/dataspaceconnector/sql/SqlQueryExecutorIntegrationTest.java
  extensions/sql/lease-sql/src/test/java/org/eclipse/dataspaceconnector/sql/lease/SqlLeaseContextTest.java
  extensions/sql/pool/apache-commons-pool-sql/src/main/java/org/eclipse/dataspaceconnector/sql/pool/commons/CommonsConnectionPool.java
  extensions/transaction/transaction-local/src/main/java/org/eclipse/dataspaceconnector/transaction/local/ConnectionWrapper.java
  launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcExtension.java
  resources/edc-checkstyle-config.xml
  samples/04.0-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferDataSinkFactory.java
  samples/04.0-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferDataSource.java
  samples/other/custom-runtime/src/main/java/org/eclipse/dataspaceconnector/demo/runtime/CustomRuntime.java
  samples/other/run-from-junit/src/test/java/org/eclipse/dataspaceconnector/junit/TestExtensions.java
  spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/command/BoundedCommandQueueTest.java
  system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferDataSinkFactory.java
  system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferDataSource.java
Labels: no-changelog

#1188 DPF: add TransferRequestDto id
  extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/TransferRequestDto.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferRequestDto.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferRequestDtoToDataRequestTransformer.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferRequestDtoToDataRequestTransformerTest.java
Labels: no-changelog

#1179 core: Fix default private key parser registered in CoreServicesExtension
  core/base/build.gradle.kts
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/security/DefaultPrivateKeyParseFunction.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/CoreServicesExtensionTest.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/security/DefaultPrivateKeyParseFunctionTest.java
  core/base/src/test/resources/ec-privatekey.pem
  core/base/src/test/resources/rsa-privatekey.pem
Labels: bug, no-changelog

#1209 chore: add policy store to ids launcher
  launchers/ids-connector/Dockerfile
  launchers/ids-connector/README.md
  launchers/ids-connector/build.gradle.kts
Labels: no-changelog

#1212 fix: Prevent consumer DPF proxy to filter request arguments
  extensions/data-plane-transfer/data-plane-transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/core/proxy/DataPlaneTransferConsumerProxyTransformer.java
  extensions/data-plane-transfer/data-plane-transfer-core/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/core/proxy/DataPlaneTransferConsumerProxyTransformerTest.java
Labels: bug, dpf, no-changelog

#1199 system-test: add a test covering the http push scenario
  extensions/data-plane-selector/selector-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/api/DataplaneSelectorApiController.java
  extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImpl.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpDataSink.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/configuration/ConfigImpl.java
  spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/system/configuration/ConfigImplTest.java
  system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/dataspaceconnector/test/e2e/BackendServiceController.java
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/EndToEndTransferTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/Participant.java
Labels: no-changelog

#1225 catalog: Fix interference between Catalog API based on same path
  CHANGELOG.md
  extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
  extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/controller/FederatedCatalogApiController.java
  extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheEndToEndTest.java
Labels: bug

#1219 DPF Azure storage: Write ".complete" blob
  extensions/azure/data-plane/storage/src/main/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/pipeline/AzureStorageDataSink.java
  extensions/azure/data-plane/storage/src/test/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/pipeline/AzureDataSourceToDataSinkTest.java
  extensions/azure/data-plane/storage/src/test/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/pipeline/AzureStorageDataSinkTest.java
  extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSink.java
  extensions/data-plane/data-plane-spi/src/test/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSinkTest.java
Labels: no-changelog

#1231 Chore: Fixed some minor snags with OpenApi
  extensions/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApi.java
  extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/controller/FederatedCatalogApiController.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/catalog-api.yaml
  resources/openapi/yaml/catalog.yaml
  resources/openapi/yaml/federated-catalog-cache.yaml
  resources/openapi/yaml/selector-api.yaml
Labels: no-changelog

#1224 samples: update documentation
  samples/02-health-endpoint/README.md
  samples/02-health-endpoint/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthEndpointExtension.java
  samples/03-configuration/README.md
  samples/03-configuration/build.gradle.kts
  samples/03-configuration/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthEndpointExtension.java
Labels: no-changelog

#895 core: upgrade to Jetty 11.0.8
  gradle.properties
Labels: no-changelog

#1234 bugfix: exclude sample and system-tests modules from module name check also if edc is loaded as submodule
  buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/ModuleNamesPlugin.java
Labels: no-changelog
