Repository eclipse-edc/Connector, pull requests merged in 2022-08, with the labels that each got.

#1706 feat: introduce ids jsonld (de-)serialization library
  CODEOWNERS
  NOTICE.md
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartCatalogDescriptionRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractOfferSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/AbstractMultipartDispatcherIntegrationTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSenderTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartArtifactRequestSenderTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartEndpointDataReferenceRequestSenderTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractAgreementHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/AbstractMultipartControllerIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
  data-protocols/ids/ids-core/build.gradle.kts
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/IdsCoreServiceExtension.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/serialization/CustomIdsConstraintDeserializer.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/serialization/IdsConstraintBuilder.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/serialization/IdsConstraintImpl.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/serialization/IdsTypeManagerUtil.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/serialization/ObjectMapperFactory.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/util/CalendarUtil.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/serialization/IdsConstraintTest.java
  data-protocols/ids/ids-jsonld-serdes-lib/README.md
  data-protocols/ids/ids-jsonld-serdes-lib/build.gradle.kts
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/JsonLd.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/JsonLdModule.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/JsonLdSerializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/UriDeserializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/UriSerializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/calendar/XmlGregorianCalendarDeserializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/calendar/XmlGregorianCalendarModule.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/calendar/XmlGregorianCalendarSerializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/number/BigDecimalDeserializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/number/BigIntegerDeserializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/number/FloatDeserializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/number/LongDeserializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/main/java/org/eclipse/dataspaceconnector/ids/jsonld/type/number/NumSerializer.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/test/java/org/eclipse/dataspaceconnector/serializer/SerializationTest.java
  data-protocols/ids/ids-jsonld-serdes-lib/src/test/java/org/eclipse/dataspaceconnector/serializer/calendar/XmlGregorianCalendarModuleTest.java
  data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/ConstraintToIdsConstraintTransformer.java
  data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsConstraintToConstraintTransformer.java
  data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsProtocol.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/ConstraintToIdsConstraintTransformerTest.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/ConstraintToIdsLogicalConstraintTransformerTest.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/IdsConstraintToConstraintTransformerTest.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/IdsLogicalConstraintToConstraintTransformerTest.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/IdsPermissionToPermissionTransformerTest.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/IdsProhibitionToProhibitionTransformerTest.java
  docs/developer/modules.md
  docs/overview/extensions.md
  docs/overview/launchers.md
  gradle.properties
  settings.gradle.kts
Labels: enhancement, ids

#1753 feat: add https call enforcer, it can be enabled with a config setting
  .github/workflows/verify.yaml
  core/base/README.md
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/OkHttpClientFactory.java
  core/base/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/OkHttpClientFactoryTest.java
  gradle.properties
Labels: enhancement

#1768 fix(sql): map contractnegotiation type
  extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
  extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java
Labels: bug

#1756 feat(api): add custom validation framework
  docs/developer/README.md
  docs/developer/custom_validation.md
  docs/developer/decision-records/2022-07-27-custom-dto-validation/README.md
  extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyExtension.java
  extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyRestService.java
  extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/validation/ResourceInterceptor.java
  extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/validation/ResourceInterceptorBinder.java
  extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/validation/ResourceInterceptorProvider.java
  extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/validation/ResourceInterceptorProviderTest.java
  extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/validation/ResourceInterceptorTest.java
  extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/validation/TestObject.java
  extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/validation/integrationtest/GreetingDto.java
  extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/validation/integrationtest/RegistrationExtension.java
  extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/validation/integrationtest/TestController.java
  extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/validation/integrationtest/ValidationIntegrationTest.java
  spi/web-spi/src/main/java/org/eclipse/dataspaceconnector/spi/validation/InterceptorFunction.java
  spi/web-spi/src/main/java/org/eclipse/dataspaceconnector/spi/validation/InterceptorFunctionRegistry.java
Labels: enhancement, api

#1767 docs: add decision record about create/update timestamps
  docs/developer/decision-records/2022-08-01-entity-timestamp/README.md
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataRequest.java
Labels: documentation

#1773 chore: remove `no-changelog` label from dependabot PRs
  .github/ISSUE_TEMPLATE/adoption_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/first-interaction.yml
  CODEOWNERS
  docs/developer/decision-records/README.md
Labels: no-changelog

#1776 fix: avoid cyclic dependency
  core/base/build.gradle.kts
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/defaults/DefaultServicesExtension.java
  extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/AzureProvisionExtension.java
Labels: bug

#1777 fix: javadoc
  extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/CrawlerErrorHandler.java
  extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/PartitionManager.java
Labels: bug

#1778 chore: make JwtUtils public
  extensions/iam/decentralized-identity/identity-did-crypto/src/main/java/org/eclipse/dataspaceconnector/iam/did/crypto/JwtUtils.java
  extensions/iam/decentralized-identity/identity-did-crypto/src/test/java/org/eclipse/dataspaceconnector/iam/did/crypto/JwtUtilsTest.java
  extensions/iam/decentralized-identity/identity-did-crypto/src/test/resources/private_p256.pem
  extensions/iam/decentralized-identity/identity-did-crypto/src/test/resources/public_p256.pem
  extensions/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityService.java
Labels: enhancement

#1783 docs: add decision record about documentation automation
  docs/developer/decision-records/2022-08-04-documentation-automation/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#1788 fix: remove logging of api key from TokenBasedAuthenticationExtension
  extensions/api/auth-tokenbased/src/main/java/org/eclipse/dataspaceconnector/api/auth/TokenBasedAuthenticationExtension.java
  extensions/api/data-management/api-configuration/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/configuration/DataManagementApiConfigurationExtension.java
Labels: bug

#1772 bugfix: avoid request flood on async provisioning/deprovisioning
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/listener/TransferProcessEventListener.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
  core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
  docs/architecture/data-transfer/diagrams/transfer-states.png
  docs/architecture/data-transfer/diagrams/transfer-states.puml
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessServiceImplTest.java
  extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderProvisioner.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioningRequested.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioningRequested.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/observe/TransferProcessListener.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionResponse.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcess.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcessStates.java
  spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcessTest.java
Labels: bug

#1792 fix: Fix usage of default @Provider methods in IdentityDidCoreExtension
  docs/developer/dependency_resolution.md
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtension.java
  extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtensionTest.java
Labels: bug

#1799 fix: Fix broken link in Policy javadoc
  core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Policy.java
Labels: bug

#1782 feat: introduce sync subscribers on EventRouter
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventRouterImpl.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/event/EventRouterImplTest.java
  docs/developer/events.md
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/EventRouter.java
Labels: enhancement

#1801 fix: avoid CodeQL run for dependabot pushes
  .github/workflows/codeql-analysis.yml
Labels: no-changelog

#1800 fix: broken test
  extensions/http-provisioner/build.gradle.kts
  extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
Labels: no-changelog

#1645 fix: resolve failure in uploading files to a presigned AWS S3 upload url
  extensions/data-plane/data-plane-http/README.md
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/ChunkedTransferRequestBody.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpRequestParams.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpSinkRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpSourceRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/NonChunkedTransferRequestBody.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/ChunkedTransferRequestBodyTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpRequestParamsSupplierTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpSinkRequestParamsSupplierTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpSourceRequestParamsSupplierTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/NonChunkedTransferRequestBodyTest.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/HttpDataAddress.java
  spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/HttpDataAddressTest.java
Labels: bug

#1805 feat: DataEncrypter provided by extension
  extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncExtension.java
Labels: enhancement, java

#1816 chore(Identity): remove Identity Hub from EDC
  docs/swaggerui/swagger-spec.js
  extensions/iam/decentralized-identity/README.md
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtension.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubApi.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubApiController.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubClientImpl.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubImpl.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/jwe/AbstractJweReader.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/jwe/AbstractJweWriter.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/jwe/GenericJweReader.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/jwe/GenericJweWriter.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/jwe/WriteRequestReader.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/jwe/WriteRequestWriter.java
  extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/store/InMemoryIdentityHubStore.java
  extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtensionTest.java
  extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubImplTest.java
  extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/hub/jwe/GenericJweWriterReaderTest.java
  extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/hub/jwe/WriteRequestWriterReaderTest.java
  extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/hub/store/InMemoryIdentityHubStoreTest.java
  extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/resolution/DidPublicKeyResolverImplTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/document/DidConstants.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/IdentityHub.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/IdentityHubClient.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/IdentityHubStore.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/AbstractHubRequest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/Commit.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/CommitHeader.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/CommitQuery.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/CommitQueryRequest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/CommitQueryResponse.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/CommitStrategy.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/ErrorResponse.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/HubMessage.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/HubMessageConstants.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/HubObject.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/InterfaceType.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/JsonCommitObject.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/ObjectQuery.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/ObjectQueryRequest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/ObjectQueryResponse.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/QueryTypes.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/WriteRequest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/WriteResponse.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/CommitQueryRequestTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/CommitQueryResponseTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/CommitQueryTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/CommitTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/ErrorResponseTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/HubObjectTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/ObjectQueryRequestTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/ObjectQueryResponseTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/ObjectQueryTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/WriteRequestTest.java
  extensions/iam/decentralized-identity/identity-did-spi/src/test/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/WriteResponseTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/identity-did-core.yaml
Labels: refactoring

#1821 docs: fix link to JettyConfiguration in Tutorial 2
  samples/02-health-endpoint/README.md
Labels: documentation

#1827 fix: bump jackson to 2.13.3
  gradle.properties
Labels: dependencies

#1820 docs: add details about DI mechanism, esp. default providers
  docs/developer/default_provider_methods.md
  docs/developer/dependency_resolution.md
Labels: documentation

#1534 feat: add Hashicorp Vault secrets backend
  .github/workflows/verify.yaml
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/defaults/src/main/java/org/eclipse/dataspaceconnector/core/defaults/certificateresolver/DefaultCertificateResolver.java
  core/defaults/src/test/java/org/eclipse/dataspaceconnector/core/defaults/certificateresolver/DefaultCertificateResolverTest.java
  core/defaults/src/test/resources/testCert.pem
  docs/developer/modules.md
  extensions/azure/vault/src/main/java/org/eclipse/dataspaceconnector/core/security/azure/AzureCertificateResolver.java
  extensions/azure/vault/src/main/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVaultExtension.java
  extensions/azure/vault/src/test/java/org/eclipse/dataspaceconnector/core/security/azure/AzureCertificateResolverTest.java
  extensions/hashicorp-vault/README.md
  extensions/hashicorp-vault/build.gradle.kts
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/CreateEntryRequestPayload.java
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/CreateEntryRequestPayloadOptions.java
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/CreateEntryResponsePayload.java
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/EntryMetadata.java
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/GetEntryResponsePayload.java
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/GetEntryResponsePayloadGetVaultEntryData.java
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVault.java
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVaultClient.java
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVaultConfig.java
  extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVaultExtension.java
  extensions/hashicorp-vault/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/hashicorp-vault/src/test/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVaultIntegrationTest.java
  extensions/hashicorp-vault/src/test/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVaultTest.java
  settings.gradle.kts
Labels: enhancement

#1789 docs: Add decision record about unifying async tests
  docs/developer/decision-records/2022-08-04-async-code-testing-practices/README.md
Labels: documentation

#1818 docs: add decision record about using maven artifacts
  docs/developer/decision-records/2022-08-11-versioning_and_artifacts/README.md
Labels: documentation, build

#1828 feat: do not overwrite registered mocks in tests
  extensions/junit/src/main/java/org/eclipse/dataspaceconnector/junit/extensions/EdcExtension.java
  extensions/junit/src/main/java/org/eclipse/dataspaceconnector/junit/extensions/TestServiceExtensionContext.java
  extensions/junit/src/test/java/org/eclipse/dataspaceconnector/junit/extensions/EdcExtensionTest.java
  extensions/junit/src/test/java/org/eclipse/dataspaceconnector/junit/extensions/MockMonitorExtension.java
  extensions/junit/src/test/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.MonitorExtension
Labels: enhancement, core feature

#1830 test: e2e-transfer-test should use copied test resources
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/Participant.java
Labels: no-changelog

#1817 fix: validate offer policy equality with definition policy on negotiation
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/policy/PolicyEquality.java
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/policy/PolicyEqualityTest.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/AbstractEndToEndTransfer.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/Participant.java
Labels: bug

#1839 docs: add decision record about removing H2
  docs/developer/decision-records/2022-08-17-remove_h2_database_tests/README.md
Labels: documentation

#1841 feat: remove h2 from all tests
  extensions/sql/asset-index-sql/build.gradle.kts
  extensions/sql/asset-index-sql/src/main/java/org/eclipse/dataspaceconnector/sql/assetindex/SqlAssetIndex.java
  extensions/sql/asset-index-sql/src/test/java/org/eclipse/dataspaceconnector/sql/assetindex/AssetIndexTest.java
  extensions/sql/asset-index-sql/src/test/java/org/eclipse/dataspaceconnector/sql/assetindex/PostgresAssetIndexTest.java
  extensions/sql/contract-definition-store-sql/build.gradle.kts
  extensions/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/ContractDefinitionStoreTest.java
  extensions/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/PostgresContractDefinitionStoreTest.java
  extensions/sql/contract-negotiation-store-sql/build.gradle.kts
  extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/ContractNegotiationStoreTest.java
  extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
  extensions/sql/lease-sql/build.gradle.kts
  extensions/sql/lease-sql/src/test/java/org/eclipse/dataspaceconnector/sql/lease/LeaseContextTest.java
  extensions/sql/lease-sql/src/test/java/org/eclipse/dataspaceconnector/sql/lease/PostgresLeaseContextTest.java
  extensions/sql/lease-sql/src/test/java/org/eclipse/dataspaceconnector/sql/lease/SqlLeaseContextTest.java
  extensions/sql/policy-store-sql/build.gradle.kts
  extensions/sql/policy-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/policy/store/PolicyDefinitionStoreTest.java
  extensions/sql/policy-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/policy/store/PostgresPolicyDefinitionStoreTest.java
  extensions/sql/transfer-process-store-sql/build.gradle.kts
  extensions/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/PostgresTransferProcessStoreTest.java
  extensions/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/TransferProcessStoreTest.java
Labels: enhancement

#1825 test: fix failure of e2e-transfer-test due to unintentional reuse of asset
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/AbstractEndToEndTransfer.java
Labels: bug

#1837 feat: fluent use of `Result`
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/result/AbstractResult.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/result/Result.java
  spi/common/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/result/ResultTest.java
  spi/common/transport-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transformer/TransformerContextImpl.java
Labels: enhancement

#1831 feat: add prepare() lifecycle phase to extensions
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/ExtensionLoader.java
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/injection/lifecycle/ExtensionLifecycleManager.java
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/injection/lifecycle/PreparePhase.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ServiceExtension.java
Labels: enhancement, core feature

#1849 fix: remove Faker from DataPlane integration tests
  extensions/data-plane/integration-tests/build.gradle.kts
  extensions/data-plane/integration-tests/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpPullIntegrationTests.java
  extensions/data-plane/integration-tests/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpToHttpIntegrationTests.java
Labels: bug

#1790 chore(IdsMultipartSender): use default object mapper for data reference serialization
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartEndpointDataReferenceRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartEndpointDataReferenceRequestSenderTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/EndpointDataReferenceHandler.java
Labels: refactoring

#1862 build: updated swagger UI Dependency and regenerate static website
  build.gradle.kts
  docs/swaggerui/oauth2-redirect.html
  docs/swaggerui/swagger-spec.js
  docs/swaggerui/swagger-ui-bundle.js
  docs/swaggerui/swagger-ui-bundle.js.map
  docs/swaggerui/swagger-ui-es-bundle-core.js
  docs/swaggerui/swagger-ui-es-bundle-core.js.map
  docs/swaggerui/swagger-ui-es-bundle.js
  docs/swaggerui/swagger-ui-es-bundle.js.map
  docs/swaggerui/swagger-ui-standalone-preset.js
  docs/swaggerui/swagger-ui-standalone-preset.js.map
  docs/swaggerui/swagger-ui.css
  docs/swaggerui/swagger-ui.css.map
  docs/swaggerui/swagger-ui.js
  docs/swaggerui/swagger-ui.js.map
  resources/openapi/openapi.yaml
  resources/openapi/yaml/federated-catalog-core.yaml
Labels: build

#1853 feat: refactor s3 client providers
  extensions/aws/aws-test/src/testFixtures/java/org/eclipse/dataspaceconnector/aws/testfixtures/AbstractS3Test.java
  extensions/aws/aws-test/src/testFixtures/java/org/eclipse/dataspaceconnector/aws/testfixtures/TestS3ClientProvider.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/DataPlaneS3Extension.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSinkFactory.java
  extensions/aws/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSourceFactory.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/DataPlaneS3ExtensionTest.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataPlaneIntegrationTest.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSinkFactoryTest.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSourceFactoryTest.java
  extensions/aws/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/TestFunctions.java
  extensions/aws/s3/s3-core/README.md
  extensions/aws/s3/s3-core/build.gradle.kts
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/AwsClientProvider.java
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/AwsClientProviderConfiguration.java
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/AwsClientProviderImpl.java
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/ClientProvider.java
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/S3ClientProvider.java
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/S3ClientProviderImpl.java
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/S3CoreExtension.java
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/SdkClientBuilders.java
  extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/SdkClientProvider.java
  extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/AwsProvisionExtension.java
  extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketProvisioner.java
  extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3DeprovisionPipeline.java
  extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3ProvisionPipeline.java
  extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3StatusChecker.java
  extensions/aws/s3/s3-provision/src/test/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketProvisionerTest.java
  extensions/aws/s3/s3-provision/src/test/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3StatusCheckerIntegrationTest.java
  samples/05-file-transfer-cloud/terraform/main.tf
Labels: enhancement, refactoring

#1815 feat(Event Framework): add intermediate superclass for Asset Events
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetCreated.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetDeleted.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetEventPayload.java
Labels: enhancement, core feature

#1871 feat: oauth2: introduce CredentialsRequestAdditionalParametersProvider
  .github/workflows/verify.yaml
  data-protocols/ids/ids-token-validation/src/main/java/org/eclipse/dataspaceconnector/ids/token/validation/IdsTokenValidationServiceExtension.java
  extensions/common/iam/oauth2/daps/README.md
  extensions/common/iam/oauth2/oauth2-core/README.md
  extensions/common/iam/oauth2/oauth2-core/build.gradle.kts
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/Oauth2Extension.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/identity/CredentialsRequestAdditionalParametersProvider.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/identity/Oauth2ServiceImpl.java
  extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/core/identity/Oauth2ServiceImplTest.java
  gradle.properties
Labels: enhancement

#1880 refactor: remove deleted modules from settings.gradle
  CODEOWNERS
  settings.gradle.kts
Labels: refactoring

#1874 feat(Event Frame Work): add intermediate superclass for TransferProcess Events hierarchy
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCancelled.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCompleted.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioned.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioningRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessEnded.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessEventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessFailed.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessInitiated.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioned.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioningRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessRequested.java
Labels: enhancement, core feature

#1876 feat: enable s3 multipart upload
  extensions/data-plane/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSink.java
  extensions/data-plane/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSinkFactory.java
  extensions/data-plane/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSinkTest.java
  extensions/data-plane/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/TestFunctions.java
Labels: enhancement

#1891 fix: avoid _contractOffer_ overwrite in `OfferedAssetToIdsResourceTransformer`
  data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/type/asset/OfferedAssetToIdsResourceTransformer.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/OfferedAssetToIdsResourceTransformerTest.java
Labels: bug

#1900 chore: prepare milestone 6 release
  docs/developer/modules.md
  gradle.properties
Labels: no-changelog
