Repository eclipse-edc/Connector, pull requests merged in 2022-09, with the labels that each got.

#1907 fix: jwt-core module produces jwt-core named jar artifact
  core/common/jwt-core/build.gradle.kts
  docs/developer/modules.md
Labels: bug

#1909 docs: add decision record for GCS integration
  docs/developer/decision-records/2022-09-01-google-cloud-storage-integration/README.md
Labels: documentation

#1917 chore: update release guide and change version back to -SNAPSHOT
  docs/developer/modules.md
  docs/developer/releases.md
  gradle.properties
Labels: no-changelog

#1921 fix: map policy properties to contract request
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractOfferSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractOfferSenderTest.java
Labels: bug, ids

#1929 docs: add previous and next links to samples tutorial
  samples/01-basic-connector/README.md
  samples/02-health-endpoint/README.md
  samples/03-configuration/README.md
  samples/04.0-file-transfer/README.md
  samples/04.1-file-transfer-listener/README.md
  samples/04.2-modify-transferprocess/README.md
  samples/04.3-open-telemetry/README.md
  samples/05-file-transfer-cloud/README.md
Labels: documentation

#1922 refactor: merge AssetLoader/AssetIndex and ContractDefinitionLoader/ContractDefinitionStore
  core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/ControlPlaneCoreExtension.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/assetindex/InMemoryAssetIndex.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/assetindex/InMemoryAssetLoaderIndexTest.java
  extensions/control-plane/api/data-management/asset-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiExtension.java
  extensions/control-plane/api/data-management/asset-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImpl.java
  extensions/control-plane/api/data-management/asset-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/asset-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImplTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiExtension.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/service/ContractDefinitionServiceImpl.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/service/ContractDefinitionServiceImplTest.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/service/ContractNegotiationEventDispatchTest.java
  extensions/control-plane/provision/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
  extensions/control-plane/store/cosmos/assetindex-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexExtension.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreExtension.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/dataspaceconnector/sql/assetindex/SqlAssetIndexServiceExtension.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreExtension.java
  samples/04.0-file-transfer/README.md
  samples/04.0-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
  samples/05-file-transfer-cloud/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/transfer/CloudTransferExtension.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/asset/AssetIndex.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/asset/AssetLoader.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/store/ContractDefinitionLoader.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/store/ContractDefinitionStore.java
  system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
Labels: refactoring

#1933 refactor: Replace CountDownLatch with Awaitility
  core/common/state-machine/build.gradle.kts
  core/common/state-machine/src/test/java/org/eclipse/dataspaceconnector/common/statemachine/StateMachineManagerTest.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/command/ContractNegotiationCommandQueueIntegrationTest.java
  core/control-plane/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplIntegrationTest.java
  core/data-plane/data-plane-framework/build.gradle.kts
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  extensions/control-plane/api/data-management/asset-api/build.gradle.kts
  extensions/control-plane/api/data-management/asset-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetEventDispatchTest.java
  extensions/control-plane/api/data-management/policydefinition-api/build.gradle.kts
  extensions/control-plane/api/data-management/policydefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyDefinitionEventDispatchTest.java
Labels: refactoring

#1946 fix(docs): change broken link in styleguide.md
  styleguide.md
Labels: documentation

#1948 chore(workflows): add close-issue-reason for stale bot
  .github/workflows/close-inactive-issues.yml
Labels: no-changelog

#1945 refactor: clean up gradle dependencies in samples
  samples/04.2-modify-transferprocess/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ApiEndpointExtension.java
  samples/04.2-modify-transferprocess/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
  settings.gradle.kts
Labels: refactoring

#1897 test: S3DataPlaneIntegrationTest should be annotated with AwsS3IntegrationTest
  extensions/data-plane/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataPlaneIntegrationTest.java
Labels: bug

#1950 feat(test): harmonize ContractDefinitionStore tests to use a common te…
  core/control-plane/control-plane-core/build.gradle.kts
  core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/contractdefinition/InMemoryContractDefinitionStoreTest.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/build.gradle.kts
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreExtension.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreTest.java
  extensions/control-plane/store/sql/contract-definition-store-sql/build.gradle.kts
  extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/ContractDefinitionStoreTest.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/PostgresContractDefinitionStoreTest.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/TestFunctions.java
  spi/control-plane/contract-spi/build.gradle.kts
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/store/ContractDefinitionStore.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/contract/offer/store/ContractDefinitionStoreTestBase.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/contract/offer/store/TestFunctions.java
Labels: enhancement

#1955 fix: avoid loop on initiate transfer failure
  core/control-plane/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
  core/control-plane/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
Labels: bug

#1959 feat(test): refactor all PolicyDefinitionStore implementors tests by using a base class
  core/control-plane/control-plane-core/build.gradle.kts
  core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/policystore/InMemoryPolicyDefinitionStoreTest.java
  extensions/control-plane/store/cosmos/policy-store-cosmos/build.gradle.kts
  extensions/control-plane/store/cosmos/policy-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStore.java
  extensions/control-plane/store/cosmos/policy-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyStoreExtension.java
  extensions/control-plane/store/cosmos/policy-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/policy-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStoreTest.java
  extensions/control-plane/store/sql/policy-store-sql/build.gradle.kts
  extensions/control-plane/store/sql/policy-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/policy/store/schema/postgres/PolicyDefinitionMapping.java
  extensions/control-plane/store/sql/policy-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/policy/store/PolicyDefinitionStoreTest.java
  extensions/control-plane/store/sql/policy-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/policy/store/PostgresPolicyDefinitionStoreTest.java
  extensions/control-plane/store/sql/policy-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/policy/store/schema/postgres/PostgresDialectStatementsTest.java
  spi/control-plane/policy-spi/build.gradle.kts
  spi/control-plane/policy-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/policy/TestFunctions.java
  spi/control-plane/policy-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/policy/store/PolicyDefinitionStoreTestBase.java
Labels: enhancement

#1961 docs: update list of third party licenses
  NOTICE.md
Labels: no-changelog

#1911 feat(Event Frame Work): add intermediate superclass for ContractDefinition Events hierarchy
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractdefinition/ContractDefinitionCreated.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractdefinition/ContractDefinitionDeleted.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractdefinition/ContractDefinitionEventPayload.java
Labels: enhancement, core feature

#1913 feat(Event Frame Work): add intermediate superclass for ContractNegotiation Events hierarchy
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationApproved.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationConfirmed.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationDeclined.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationEventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationFailed.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationInitiated.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationOffered.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationRequested.java
Labels: enhancement, core feature

#1951 test: enable integration tests against real S3 (fixes #1899)
  extensions/common/aws/aws-test/README.md
  extensions/common/aws/aws-test/src/testFixtures/java/org/eclipse/dataspaceconnector/aws/testfixtures/AbstractS3Test.java
Labels: enhancement

#1952 feat(test): introduced a base class for all ContractNegotiationStore
  core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/InMemoryStatefulEntityStore.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/InMemoryContractNegotiationStore.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/transferprocessstore/InMemoryTransferProcessStore.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/InMemoryContractNegotiationStoreTest.java
  docs/swaggerui/swagger-spec.js
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/build.gradle.kts
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreExtension.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreTest.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/build.gradle.kts
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
  resources/openapi/openapi.yaml
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/persistence/Lease.java
  spi/control-plane/contract-spi/build.gradle.kts
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStoreTestBase.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/TestFunctions.java
Labels: enhancement

#1973 fix: map DataRequest properties to DataFlowRequest
  extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/flow/DataPlaneTransferFlowController.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/flow/DataPlaneTransferFlowControllerTest.java
Labels: bug

#1963 feat: avoid log azure vault
  extensions/common/vault/azure-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVault.java
  extensions/common/vault/azure-vault/src/test/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVaultExtensionTest.java
  extensions/common/vault/azure-vault/src/test/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVaultTest.java
Labels: enhancement

#1974 refactor: default providers
  core/common/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreDefaultServicesExtension.java
  core/common/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/common/base/src/main/java/org/eclipse/dataspaceconnector/core/base/OkHttpClientFactory.java
  core/common/base/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  core/common/base/src/test/java/org/eclipse/dataspaceconnector/core/CoreServicesExtensionTest.java
  core/common/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/ExtensionLoaderTest.java
  core/common/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/TestFunctions.java
  core/common/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/testextensions/ProviderDefaultServicesExtension.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/ControlPlaneDefaultServicesExtension.java
  core/control-plane/control-plane-core/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/core/DataPlaneSelectorDefaultServicesExtension.java
  core/data-plane-selector/data-plane-selector-core/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  core/federated-catalog/federated-catalog-core/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog/federated-catalog-core/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogDefaultServicesExtension.java
  core/federated-catalog/federated-catalog-core/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtensionTest.java
  extensions/common/api/api-core/build.gradle.kts
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/ApiCoreDefaultServicesExtension.java
  extensions/common/api/api-core/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/CosmosDefaultServicesExtension.java
  extensions/common/azure/cosmos-common/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtension.java
  extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/store/InMemoryDidDocumentStore.java
  extensions/common/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/store/InMemoryDidDocumentStoreTest.java
  extensions/control-plane/api/data-management/api-configuration/build.gradle.kts
  extensions/control-plane/api/data-management/api-configuration/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/configuration/DataManagementApiConfigurationExtension.java
  extensions/control-plane/api/data-management/asset-api/build.gradle.kts
  extensions/control-plane/api/data-management/catalog-api/build.gradle.kts
  extensions/control-plane/api/data-management/contractdefinition-api/build.gradle.kts
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncDefaultServicesExtension.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncExtension.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/control-plane/provision/http-provisioner/build.gradle.kts
  extensions/control-plane/provision/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpWebhookExtension.java
  spi/common/auth-spi/build.gradle.kts
Labels: refactoring

#1919 refactor: remove inheritance for multipart senders
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartRemoteMessageDispatcher.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartSenderDelegate.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/SenderDelegateContext.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartArtifactRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartCatalogDescriptionRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractAgreementSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractOfferSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractRejectionSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartDescriptionRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartEndpointDataReferenceRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSenderTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartArtifactRequestSenderTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractOfferSenderTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartEndpointDataReferenceRequestSenderTest.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/message/IdsMessageSender.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/message/IdsRemoteMessageDispatcher.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/message/RemoteMessageDispatcher.java
Labels: ids, refactoring

#1980 feat(catalog): make FederatedCatalogNode filtering extensible
  core/federated-catalog/federated-catalog-core/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/ExecutionManager.java
  core/federated-catalog/federated-catalog-core/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
  core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/ExecutionManagerTest.java
  core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtensionTest.java
  spi/federated-catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/FederatedCacheNodeFilter.java
Labels: enhancement

#1976 feat(store): remove cache on CosmosPolicyDefinitionStore
  core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/policystore/InMemoryPolicyDefinitionStoreTest.java
  extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosConditionExpression.java
  extensions/control-plane/store/cosmos/policy-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStore.java
  extensions/control-plane/store/cosmos/policy-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/policy-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStoreTest.java
  extensions/control-plane/store/sql/policy-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/policy/store/PostgresPolicyDefinitionStoreTest.java
  spi/control-plane/policy-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/policy/store/PolicyDefinitionStoreTestBase.java
Labels: enhancement

#1969 feat(store): remove cache on CosmosContractDefinitionStore
  core/common/util/src/main/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtil.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/contractdefinition/InMemoryContractDefinitionStoreTest.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreTest.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/PostgresContractDefinitionStoreTest.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/contract/offer/store/ContractDefinitionStoreTestBase.java
Labels: enhancement

#1987 refactor: remove nimbus dependency from jwt-spi
  core/common/jwt-core/src/main/java/org/eclipse/dataspaceconnector/core/jwt/TokenGenerationServiceImpl.java
  core/common/jwt-core/src/main/java/org/eclipse/dataspaceconnector/core/jwt/TokenValidationServiceImpl.java
  core/common/jwt-core/src/test/java/org/eclipse/dataspaceconnector/core/jwt/TokenGenerationServiceImplTest.java
  core/common/jwt-core/src/test/java/org/eclipse/dataspaceconnector/core/jwt/TokenValidationServiceImplTest.java
  data-protocols/ids/ids-token-validation/build.gradle.kts
  data-protocols/ids/ids-token-validation/src/main/java/org/eclipse/dataspaceconnector/ids/token/validation/rule/IdsValidationRule.java
  data-protocols/ids/ids-token-validation/src/test/java/org/eclipse/dataspaceconnector/ids/token/validation/rule/IdsValidationRuleTest.java
  extensions/common/iam/decentralized-identity/identity-did-crypto/build.gradle.kts
  extensions/common/iam/decentralized-identity/identity-did-crypto/src/main/java/org/eclipse/dataspaceconnector/iam/did/crypto/JwtUtils.java
  extensions/common/iam/oauth2/daps/build.gradle.kts
  extensions/common/iam/oauth2/daps/src/main/java/org/eclipse/dataspaceconnector/iam/daps/DapsJwtDecorator.java
  extensions/common/iam/oauth2/daps/src/test/java/org/eclipse/dataspaceconnector/iam/daps/DapsJwtDecoratorTest.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/jwt/DefaultJwtDecorator.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/rule/Oauth2ValidationRule.java
  extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/core/identity/Oauth2ServiceImplTest.java
  extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/core/jwt/DefaultJwtDecoratorTest.java
  extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/core/jwt/Oauth2ValidationRuleTest.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/proxy/DataPlaneProxyTokenDecorator.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/validation/ContractValidationRule.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/validation/ExpirationDateValidationRule.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/proxy/DataPlaneProxyTokenDecoratorTest.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/proxy/DataPlaneTransferProxyReferenceServiceImplTest.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/validation/ContractValidationRuleTest.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/validation/ExpirationDateValidationRuleTest.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/iam/ClaimToken.java
  spi/common/jwt-spi/build.gradle.kts
  spi/common/jwt-spi/src/main/java/org/eclipse/dataspaceconnector/spi/jwt/JwtDecorator.java
  spi/common/jwt-spi/src/main/java/org/eclipse/dataspaceconnector/spi/jwt/JwtRegisteredClaimNames.java
  spi/common/jwt-spi/src/main/java/org/eclipse/dataspaceconnector/spi/jwt/TokenValidationRule.java
  spi/common/oauth2-spi/build.gradle.kts
Labels: refactoring

#1995 chore: bump aws-sdk version to 2.17.278
  gradle.properties
Labels: dependencies

#1996 chore: bump swagger version to 2.2.2
  build.gradle.kts
  gradle.properties
Labels: dependencies

#1983 docs: add decision record about IDS filtering
  docs/developer/decision-records/2022-09-18-ids-catalog-request-filtering/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#1982 feat(test): introduce a base class for all TransferProcessStore
  core/control-plane/control-plane-core/build.gradle.kts
  core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/transferprocessstore/InMemoryTransferProcessStore.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/transferprocessstore/InMemoryTransferProcessStoreTest.java
  core/control-plane/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
  core/control-plane/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
  core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FccTestExtension.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
  extensions/common/iam/decentralized-identity/identity-common-test/bin/testFixtures/edc-test-keystore.jks
  extensions/common/iam/decentralized-identity/identity-common-test/bin/testFixtures/readme-keystore.txt
  extensions/control-plane/store/cosmos/transfer-process-store-cosmos/build.gradle.kts
  extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStore.java
  extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreExtension.java
  extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreIntegrationTest.java
  extensions/control-plane/store/sql/transfer-process-store-sql/build.gradle.kts
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStore.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/PostgresTransferProcessStoreTest.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/TransferProcessStoreTest.java
  spi/control-plane/transfer-spi/build.gradle.kts
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/store/TransferProcessStore.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/transfer/store/TestFunctions.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/transfer/store/TransferProcessStoreTestBase.java
Labels: enhancement

#1992 feat: add toBuilder for resource definitions
  core/control-plane/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/TestResourceDefinition.java
  extensions/control-plane/provision/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageResourceDefinition.java
  extensions/control-plane/provision/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageProvisionerTest.java
  extensions/control-plane/provision/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageResourceDefinitionTest.java
  extensions/control-plane/provision/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/AbstractHttpResourceDefinition.java
  extensions/control-plane/provision/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderResourceDefinition.java
  extensions/control-plane/provision/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderProvisionerTest.java
  extensions/control-plane/provision/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderResourceDefinitionTest.java
  extensions/control-plane/provision/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketResourceDefinition.java
  extensions/control-plane/provision/s3-provision/src/test/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketResourceDefinitionTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ResourceDefinition.java
  spi/control-plane/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TestResourceDefinition.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/transfer/store/TestFunctions.java
Labels: enhancement

#2011 refactor: replace fakes with mocks
  core/common/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/injection/lifecycle/ExtensionLifecycleManager.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationIntegrationTest.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FccTestExtension.java
  core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheEndToEndTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/AbstractMultipartDispatcherIntegrationTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/AbstractMultipartControllerIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/FakeContractNegotiationManager.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/FakeContractOfferService.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
Labels: refactoring

#2003 feat(store): implements array querying in Cosmos store
  core/common/util/src/main/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtil.java
  core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtilTest.java
  core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestGenericArrayList.java
  core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestGenericObject.java
  core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestGenericSubclass.java
  core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestObject.java
  core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestObjectWithList.java
  extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/ConditionExpression.java
  extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/ConditionExpressionParser.java
  extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosExistsExpression.java
  extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosPathConditionExpression.java
  extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/QuotedPathCollector.java
  extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/SqlStatement.java
  extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/WhereClause.java
  extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/TestCollectionDocument.java
  extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/ConditionExpressionParserTest.java
  extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosExistsExpressionTest.java
  extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosPathConditionExpressionTest.java
  extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/QuotedPathCollectorTest.java
  extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/SqlStatementTest.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/policy-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStoreIntegrationTest.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/contract/offer/store/ContractDefinitionStoreTestBase.java
Labels: enhancement

#2016 refactor: move duplicated code to `ids-core`
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSenderTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/controller/MultipartController.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/IdsCoreServiceExtension.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/DynamicAttributeTokenServiceImpl.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/util/ConnectorIdUtil.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/DynamicAttributeTokenServiceImplTest.java
  data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/DynamicAttributeTokenService.java
Labels: ids, refactoring

#2005 fix: Add missing result check in DecentralizedIdentityService
  extensions/common/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityService.java
  extensions/common/iam/decentralized-identity/identity-did-service/src/test/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityServiceTest.java
Labels: bug

#2023 feat(ServiceExtensionContext): freeze the ServiceExtensionContext before the prepare phase
  core/common/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContext.java
  core/common/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/ExtensionLoader.java
  core/common/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContextTest.java
  extensions/common/junit/src/test/java/org/eclipse/dataspaceconnector/junit/extensions/EdcExtensionTest.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ServiceExtensionContext.java
Labels: enhancement

#2025 fix(MultipartController): use message recipient as token audience
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/controller/MultipartController.java
Labels: bug, ids

#2012 feat(DataManagementApi): returns id in Assest, Policy and Contract de…
  docs/swaggerui/swagger-spec.js
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/model/IdResponseDto.java
  extensions/common/api/api-core/src/test/java/org/eclipse/dataspaceconnector/api/model/IdResponseDtoTest.java
  extensions/control-plane/api/data-management/asset-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApi.java
  extensions/control-plane/api/data-management/asset-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiController.java
  extensions/control-plane/api/data-management/asset-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/asset-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiControllerTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApi.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiController.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerTest.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApi.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiController.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/NegotiationId.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerTest.java
  extensions/control-plane/api/data-management/policydefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApi.java
  extensions/control-plane/api/data-management/policydefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApiController.java
  extensions/control-plane/api/data-management/policydefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/policydefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApiControllerTest.java
  extensions/control-plane/api/data-management/transferprocess-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApi.java
  extensions/control-plane/api/data-management/transferprocess-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiController.java
  extensions/control-plane/api/data-management/transferprocess-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferId.java
  extensions/control-plane/api/data-management/transferprocess-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/transferprocess-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/asset-api.yaml
  resources/openapi/yaml/contractdefinition-api.yaml
  resources/openapi/yaml/contractnegotiation-api.yaml
  resources/openapi/yaml/policydefinition-api.yaml
  resources/openapi/yaml/transferprocess-api.yaml
  system-tests/azure-tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferUtils.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/Participant.java
Labels: enhancement, api

#2035 fix(BaseRuntime): adds the exception messagge in the log before exit
  core/common/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/runtime/BaseRuntime.java
  core/common/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/BaseRuntimeTest.java
  core/common/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/testextensions/BaseRuntimeFixture.java
Labels: bug

#2034 docs: add DR for SQL Query Streaming
  docs/developer/decision-records/2022-09-29-sql-query-streaming/README.md
  docs/developer/decision-records/README.md
Labels: documentation
