Repository eclipse-edc/Connector, pull requests merged in 2022-03, with the labels that each got.

#778 Adds documentation about dependency resolution
  docs/developer/dependency_resolution.md
Labels: documentation

#824 ci: add action to check changelog modifications
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check-changelog.yaml
Labels: no-changelog

#847 docs: update README.md
  README.md
Labels: no-changelog

#846 Cosmos DB emulator: use latest Windows image
  .github/workflows/integrationtests.yaml
Labels: no-changelog

#860 Performance tests: Exclude some Gatling transitive dependencies
  system-tests/tests/build.gradle.kts
  system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/FileTransferLocalSimulation.java
Labels: no-changelog

#850 publish test results
  .github/workflows/verify.yaml
Labels: no-changelog

#854 chore: add issue template for feature requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: no-changelog

#852 ci: check pull request title formatting
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check-changelog.yaml
  .github/workflows/scan-pull-request.yaml
Labels: no-changelog

#869 ci: add action to auto assign issues and pull requests to project
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/issue-auto-assign-project.yaml
  .github/workflows/pull-request-auto-assign-project.yaml
Labels: no-changelog

#875 fix(ci): replace action for project assignment
  .github/workflows/issue-auto-assign-project.yaml
  .github/workflows/pull-request-auto-assign-project.yaml
Labels: no-changelog

#851 DPF Selector: add technical concept
  docs/developer/dpf_selector.md
Labels: no-changelog

#567 docs: sequence diagrams http data transfer
  docs/diagrams/data-flow/data-flow-api-endpoint.puml
  docs/diagrams/data-flow/data-flow-api-endpoint_2.png
  docs/diagrams/data-flow/data-flow-api-endpoint_2_current.png
Labels: no-changelog

#905 fix(action): add permissions to pull-request-auto-assign-project.yaml
  .github/workflows/pull-request-auto-assign-project.yaml
Labels: no-changelog

#917 refactor: Move ParticipantAgentService and PolicyEngine to core-spi
  core/base/build.gradle.kts
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/agent/ParticipantAgentServiceImpl.java
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyContextImpl.java
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImpl.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/agent/ParticipantAgentServiceImplTest.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImplScenariosTest.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImplTest.java
  core/contract/build.gradle.kts
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImpl.java
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImplTest.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImplTest.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
  extensions/policy/ids-policy/src/main/java/org/eclipse/dataspaceconnector/ids/policy/AbsSpatialPositionConstraintFunction.java
  extensions/policy/ids-policy/src/main/java/org/eclipse/dataspaceconnector/ids/policy/IdsPolicyExtension.java
  extensions/policy/ids-policy/src/main/java/org/eclipse/dataspaceconnector/ids/policy/PartnerLevelConstraintFunction.java
  extensions/policy/ids-policy/src/test/java/org/eclipse/dataspaceconnector/ids/policy/AbsSpatialPositionConstraintFunctionTest.java
  extensions/policy/ids-policy/src/test/java/org/eclipse/dataspaceconnector/ids/policy/MockPolicyContext.java
  extensions/policy/ids-policy/src/test/java/org/eclipse/dataspaceconnector/ids/policy/PartnerLevelConstraintFunctionTest.java
  spi/contract-spi/build.gradle.kts
  spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractDefinitionService.java
  spi/core-spi/build.gradle.kts
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/agent/ParticipantAgent.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/agent/ParticipantAgentService.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/agent/ParticipantAgentServiceExtension.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/AtomicConstraintFunction.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/PolicyContext.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/PolicyEngine.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/RuleFunction.java
Labels: no-changelog

#911 system-tests: avoid system-tests failure when runtimes are not fully built
  docs/testing.md
  launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcRuntimeExtension.java
  system-tests/e2e-transfer-test/runner/build.gradle.kts
  system-tests/tests/build.gradle.kts
Labels: no-changelog

#909 spi: Return the deleted ContractDefinition when deleting ContractDefinition.
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
  extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexIntegrationTest.java
  extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
  extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
  extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreTest.java
  extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FccTestExtension.java
  extensions/in-memory/contractdefinition-store-memory/src/main/java/org/eclipse/dataspaceconnector/contractdefinition/store/memory/InMemoryContractDefinitionStore.java
  extensions/in-memory/contractdefinition-store-memory/src/test/java/org/eclipse/dataspaceconnector/contractdefinition/store/memory/InMemoryContractDefinitionStoreTest.java
  spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/store/ContractDefinitionStore.java
Labels: no-changelog

#920 SQL: Design Proposal for SQL Policy Store
  extensions/sql/policy/docs/er.puml
  extensions/sql/policy/docs/schema.sql
  extensions/sql/policy/sql_policy_store_proposal.md
Labels: no-changelog

#927 Bugfix: compile error on `main` due to a signature change
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
  extensions/sql/contract-definition/store/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreTest.java
Labels: bug, no-changelog

#883 doc(decision): document use of "story" issues
  docs/developer/decision-records/2022-03-11-story-issues/README.md
Labels: no-changelog

#892 doc(decision): Decision Record for Policy Scopes
  docs/developer/decision-records/2022-03-15-policy-scopes/README.md
Labels: no-changelog

#933 Policy: Implement function scopes in the PolicyEngine
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImpl.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImplScenariosTest.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImplTest.java
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImpl.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImplTest.java
  extensions/policy/ids-policy/src/main/java/org/eclipse/dataspaceconnector/ids/policy/IdsPolicyExtension.java
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
  spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractDefinitionService.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/PolicyEngine.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/PolicyScope.java
Labels: no-changelog

#942 feature: Implement rule type bindings and scope filtering
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImpl.java
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/RuleBindingRegistryImpl.java
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/ScopeFilter.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImplScenariosTest.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImplTest.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/RuleBindingRegistryImplTest.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/ScopeFilterTest.java
  core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/AndConstraint.java
  core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/MultiplicityConstraint.java
  core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/OrConstraint.java
  core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Permission.java
  core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Prohibition.java
  core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/XoneConstraint.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/PolicyEngine.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/RuleBindingRegistry.java
Labels: no-changelog

#943 refactor: Simplify CatalogService and ConnectorService interfaces
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/controller/MultipartController.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractAgreementHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractOfferHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractRejectionHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/EndpointDataReferenceHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/Handler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/NotificationMessageHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/AbstractDescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/ArtifactDescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/ConnectorDescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/DataCatalogDescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/DescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/RepresentationDescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/ResourceDescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/message/MultipartRequest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/EndpointDataReferenceHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/NotificationMessageHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/DescriptionHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/RepresentationDescriptionRequestHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/ResourceDescriptionRequestHandlerTest.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImpl.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceImpl.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImplTest.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceImplTest.java
  data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/CatalogService.java
  data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/ConnectorService.java
Labels: no-changelog

#947 chore: Rename RegistrationTypes and remove method
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/base/src/test/java/org/eclipse/dataspaceconnector/core/CoreServicesExtensionTest.java
  core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/PolicyRegistrationTypes.java
Labels: no-changelog

#899 Proposal: technical concept for a `TransferProcessStore` based on SQL
  extensions/sql/transfer-process-store/ddl_postgres.sql
  extensions/sql/transfer-process-store/dml_postgres.sql
  extensions/sql/transfer-process-store/sql_tps_proposal.md
Labels: documentation, no-changelog

#810 IDS: Add mandatory fields to IDS RequestInProcessMessage, related #236
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractOfferHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ResponseMessageUtil.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/message/ids/IdsClientCredentialsScope.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/message/ids/IdsResponseMessageFactory.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/message/ids/exceptions/InvalidCorrelationMessageException.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/message/ids/exceptions/MissingClientCredentialsException.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/AbstractMultipartControllerIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/message/ids/IdsResponseMessageFactoryTest.java
Labels: no-changelog

#961 gradle: remove workers configuration settings
  gradle.properties
Labels: no-changelog

#970 sample 4: update permission
  samples/04.0-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
Labels: no-changelog

#950 Feature: Adds SQL-based implementation of the `TransferProcessStore`
  CHANGELOG.md
  extensions/azure/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
  extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/LeaseableCosmosDocument.java
  extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/util/CosmosLeaseContext.java
  extensions/azure/cosmos/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/util/CosmosLeaseContextTest.java
  extensions/azure/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStore.java
  extensions/azure/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/model/TransferProcessDocument.java
  extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
  extensions/sql/lease/build.gradle.kts
  extensions/sql/lease/src/main/java/org/eclipse/dataspaceconnector/sql/lease/LeaseStatements.java
  extensions/sql/lease/src/main/java/org/eclipse/dataspaceconnector/sql/lease/SqlLease.java
  extensions/sql/lease/src/main/java/org/eclipse/dataspaceconnector/sql/lease/SqlLeaseContext.java
  extensions/sql/lease/src/main/java/org/eclipse/dataspaceconnector/sql/lease/SqlLeaseContextBuilder.java
  extensions/sql/transfer-process-store/build.gradle.kts
  extensions/sql/transfer-process-store/dml_postgres.sql
  extensions/sql/transfer-process-store/doc/README.md
  extensions/sql/transfer-process-store/doc/ddl_postgres.sql
  extensions/sql/transfer-process-store/sql_tps_proposal.md
  extensions/sql/transfer-process-store/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/PostgresStatements.java
  extensions/sql/transfer-process-store/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStore.java
  extensions/sql/transfer-process-store/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/TransferProcessStoreStatements.java
  extensions/sql/transfer-process-store/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStoreTest.java
  extensions/sql/transfer-process-store/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/TestFunctions.java
  extensions/sql/transfer-process-store/src/test/resources/schema.sql
  extensions/transaction/transaction-atomikos/src/main/java/org/eclipse/dataspaceconnector/transaction/atomikos/AtomikosTransactionContext.java
  settings.gradle.kts
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/persistence/Lease.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/persistence/LeaseContext.java
Labels: enhancement

#951 feature: Implement callback command
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/commands/AddProvisionedResourceCommand.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/AddProvisionedResourceCommandHandler.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/ProvisionCompletionDelegate.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
Labels: no-changelog

#974 test: fix flaky test
  common/state-machine-lib/src/test/java/org/eclipse/dataspaceconnector/common/statemachine/StateMachineTest.java
Labels: no-changelog

#965 Data management: fix package names
  extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/transformer/DtoTransformerRegistryImpl.java
  extensions/api/api-core/src/test/java/org/eclipse/dataspaceconnector/api/transformer/DtoTransformerRegistryImplTest.java
  extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApi.java
  extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiController.java
  extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiExtension.java
  extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/model/ContractAgreementDto.java
  extensions/api/data-management/contractagreement/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/api/data-management/contractagreement/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiControllerIntegrationTest.java
  extensions/api/data-management/contractagreement/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiControllerTest.java
  extensions/api/data-management/contractagreement/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/model/ContractAgreementDtoTest.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApi.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiController.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtension.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/DataRequestDto.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferProcessDto.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferRequestDto.java
  extensions/api/data-management/transferprocess/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiApiControllerTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferProcessDtoTest.java
Labels: no-changelog

#982 feature:content addresses
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/provision/ResourceManifestGeneratorImpl.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
  core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/provision/ResourceManifestGeneratorImplTest.java
  core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplIntegrationTest.java
  core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/build.gradle.kts
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
  extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/AwsProvisionExtension.java
  extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3ConsumerResourceDefinitionGenerator.java
  extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/AzureProvisionExtension.java
  extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGenerator.java
  extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGeneratorTest.java
  samples/other/run-from-junit/src/test/java/org/eclipse/dataspaceconnector/junit/EndToEndTest.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ConsumerResourceDefinitionGenerator.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ProviderResourceDefinitionGenerator.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ResourceManifestGenerator.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResource.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcess.java
  spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResourceTest.java
  spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcessTest.java
Labels: no-changelog

#987 Unit testing: fix configuration
  .github/workflows/verify.yaml
  build.gradle.kts
Labels: no-changelog

#973 core: move extension loading logic from ServiceExtensionContext to ExtensionLoader
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContext.java
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/ExtensionLoader.java
  core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/runtime/BaseRuntime.java
  core/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContextTest.java
  core/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/ExtensionLoaderTest.java
  launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcExtension.java
  samples/other/custom-runtime/src/main/java/org/eclipse/dataspaceconnector/demo/runtime/CustomRuntime.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ServiceExtensionContext.java
Labels: no-changelog

#988 DataPlane: Introduces a client enabling to delegate data transfer to the DPF
  CHANGELOG.md
  docs/developer/dpf_selector.md
  docs/developer/dpf_transfer.md
  docs/diagrams/data-plane-transfer/data-plane-transfer-client.png
  docs/diagrams/data-plane-transfer/data-plane-transfer-sync.png
  extensions/data-plane-selector/selector-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/DataPlaneSelector.java
  extensions/data-plane-selector/selector-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/client/DataPlaneSelectorClient.java
  extensions/data-plane-transfer/data-plane-transfer-client/build.gradle.kts
  extensions/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/DataPlaneTransferClientExtension.java
  extensions/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/client/DataPlaneTransferClient.java
  extensions/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/client/EmbeddedDataPlaneTransferClient.java
  extensions/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/client/RemoteDataPlaneTransferClient.java
  extensions/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/flow/DataPlaneTransferFlowController.java
  extensions/data-plane-transfer/data-plane-transfer-client/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/data-plane-transfer/data-plane-transfer-client/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/TestFixtures.java
  extensions/data-plane-transfer/data-plane-transfer-client/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/client/EmbeddedDataPlaneTransferClientTest.java
  extensions/data-plane-transfer/data-plane-transfer-client/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/client/RemoteDataPlaneTransferClientTest.java
  extensions/data-plane-transfer/data-plane-transfer-client/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/flow/DataPlaneTransferFlowControllerTest.java
  extensions/data-plane-transfer/data-plane-transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/core/proxy/DataPlaneProxyManagerImpl.java
  extensions/data-plane-transfer/data-plane-transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/core/proxy/DataPlaneProxyTokenGeneratorImpl.java
  extensions/data-plane-transfer/data-plane-transfer-core/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/core/proxy/DataPlaneProxyManagerImplTest.java
  extensions/data-plane-transfer/data-plane-transfer-core/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/core/proxy/DataPlaneProxyTokenGeneratorImplTest.java
  extensions/data-plane-transfer/data-plane-transfer-spi/build.gradle.kts
  extensions/data-plane-transfer/data-plane-transfer-spi/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/spi/DataPlaneTransferType.java
  extensions/data-plane-transfer/data-plane-transfer-spi/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/spi/proxy/DataPlaneProxyCreationRequest.java
  extensions/data-plane-transfer/data-plane-transfer-spi/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/spi/proxy/DataPlaneProxyTokenGenerator.java
  extensions/data-plane-transfer/data-plane-transfer-sync/README.md
  extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncConfiguration.java
  extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncExtension.java
  extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/api/controller/DataPlaneTransferSyncApiController.java
  extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/api/rules/ContractValidationRule.java
  extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/flow/ProviderDataPlaneProxyDataFlowController.java
  extensions/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/api/controller/DataPlaneTransferSyncApiControllerTest.java
  extensions/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/flow/ProviderDataPlaneProxyDataFlowControllerTest.java
  extensions/data-plane/data-plane-api/build.gradle.kts
  extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/DataPlaneApiExtension.java
  extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/controller/ContainerRequestContextApiImpl.java
  extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/controller/DataPlaneControlApiController.java
  extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/controller/DataPlanePublicApiController.java
  extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/response/ResponseFunctions.java
  extensions/data-plane/data-plane-api/src/test/java/org/eclipse/dataspaceconnector/dataplane/api/controller/ContainerRequestContextApiImplTest.java
  extensions/data-plane/data-plane-api/src/test/java/org/eclipse/dataspaceconnector/dataplane/api/controller/DataPlanePublicApiControllerTest.java
  extensions/data-plane/data-plane-api/src/test/java/org/eclipse/dataspaceconnector/dataplane/api/controller/DataPlaneTransferControllerTest.java
  extensions/data-plane/data-plane-api/src/test/java/org/eclipse/dataspaceconnector/dataplane/api/response/ResponseFunctionsTest.java
  extensions/data-plane/data-plane-spi/build.gradle.kts
  extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/DataPlaneConstants.java
  extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/response/TransferErrorResponse.java
  extensions/data-plane/integration-tests/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpPullIntegrationTests.java
  settings.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/EndToEndTransferTest.java
Labels: dpf

#1030 Bugfix: adds extension to register SQL TPS
  CHANGELOG.md
  extensions/sql/transfer-process-store/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/SqlTransferProcessStoreExtension.java
  extensions/sql/transfer-process-store/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/PostgresStatements.java
  extensions/sql/transfer-process-store/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
Labels: bug

#1024 ci: add paths ignore to workflow files
  .github/workflows/codeql-analysis.yml
  .github/workflows/generate_openapi_spec.yaml
  .github/workflows/integrationtests.yaml
  .github/workflows/verify.yaml
Labels: no-changelog

#1031 sample 5: change request to get agreement id
  samples/05-file-transfer-cloud/README.md
Labels: no-changelog

#1006 Data Management API: Created TransferProcess transformers
  extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/transformer/DtoTransformerRegistryImpl.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtension.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/DataRequestToDataRequestDtoTransformer.java
  extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessToTransferProcessDtoTransformer.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtensionTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/DataRequestToDataRequestDtoTransformerTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/DataRequestTransformerTestData.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessToTransferProcessDtoTransformerTest.java
  extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessTransformerTestData.java
Labels: no-changelog

#1038 Revert "ci: add checkstyle rule for Java file headers (#997)"
  .github/workflows/verify.yaml
  build.gradle.kts
  resources/edc-checkstyle-config.xml
Labels: no-changelog
