Repository eclipse-edc/Connector, pull requests merged in 2022-01, with the labels that each got.

#504 core: generalize parser
  core/base/src/main/java/org/eclipse/dataspaceconnector/core/system/CoreServicesExtension.java
Labels: bug

#531 Feature/418 handle data flow controller exception
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/flow/DataFlowManagerImpl.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/AsyncTransferProcessManager.java
  core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/flow/DataFlowManagerImplTest.java
  extensions/inline-data-transfer/inline-data-transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/inline/core/InlineDataFlowController.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/flow/DataFlowController.java
  spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/flow/DataFlowInitiateResult.java
Labels: Milestone 2

#524 contract negotiation: add contract negotiation listener
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationIntegrationTest.java
  core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/AsyncTransferProcessManager.java
  spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/ContractNegotiationListener.java
  spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/ContractNegotiationObservable.java
  spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/Observable.java
Labels: Milestone 2

#565 Added documentation for the CommandQueue
  docs/command-queue.md
Labels: documentation
