Repository eclipse-edc/Connector, pull requests merged in 2022-10, with the labels that each got.

#2028 feat(build): add/apply autodoc plugin
  build.gradle.kts
  docs/developer/autodoc.md
  gradle.properties
Labels: documentation, build

#1971 docs(Event Framework): updating and extending doc
  docs/developer/events.md
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetCreated.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetDeleted.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetEventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCancelled.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCompleted.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioned.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioningRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessEnded.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessEventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessFailed.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessInitiated.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioned.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioningRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessRequested.java
Labels: documentation

#2015 feat: IDS catalog request filtering
  core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImplTest.java
  core/federated-catalog/federated-catalog-core/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/query/BatchedRequestFetcher.java
  core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/query/BatchedRequestFetcherTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartCatalogDescriptionRequestSender.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/util/RequestUtil.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/util/RequestUtilTest.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImpl.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceImpl.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImplTest.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceImplTest.java
  data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/CatalogService.java
  data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/ConnectorService.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/service/CatalogServiceImpl.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerTest.java
  spi/common/catalog-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/catalog/CatalogRequest.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/message/Range.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QuerySpec.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractOfferQuery.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractOfferService.java
Labels: enhancement

#2037 fix(CatalogApi): adds @NotNull to providerUrl param
  docs/swaggerui/swagger-spec.js
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApi.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiController.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/catalog-api.yaml
Labels: bug

#2045 fix(DataPlaneTransferSyncExtension): remove default value for publickey alias
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncExtension.java
Labels: bug

#2046 chore(ContractOffer): remove field assetId
  core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/query/BatchedRequestFetcherTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractOfferSenderTest.java
  docs/swaggerui/swagger-spec.js
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerTest.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/service/CatalogServiceImplTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/catalog-api.yaml
  resources/openapi/yaml/federated-catalog-core.yaml
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java
  spi/control-plane/contract-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOfferTest.java
Labels: refactoring

#2047 feat(DataSourceRegistry): provides a default impl for DataSourceRegistry
  core/common/base/build.gradle.kts
  core/common/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreDefaultServicesExtension.java
  spi/common/transaction-datasource-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transaction/datasource/DefaultDataSourceRegistry.java
  spi/common/transaction-datasource-spi/src/test/java/org/eclipse/dataspaceconnector/spi/transaction/datasource/DefaultDataSourceRegistryTest.java
Labels: enhancement

#2055 build(deps): bump azure and aws dependency version to the last releases
  gradle.properties
Labels: dependencies

#2031 fix: use IdsId as type for connector ID
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/SenderDelegateContext.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartArtifactRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartCatalogDescriptionRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractAgreementSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractOfferSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractRejectionSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartDescriptionRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartEndpointDataReferenceRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartArtifactRequestSenderTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractOfferSenderTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartEndpointDataReferenceRequestSenderTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/controller/MultipartController.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractAgreementHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractRejectionHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/EndpointDataReferenceHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/util/ResponseUtil.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/EndpointDataReferenceHandlerTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/util/ResponseUtilTest.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceSettings.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/util/ConnectorIdUtil.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceImplTest.java
  data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/domain/connector/Connector.java
  data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/types/IdsId.java
  data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/type/connector/ConnectorToIdsConnectorTransformer.java
Labels: bug, ids

#2018 fix: use the `range` to limit offers, not definitions
  core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImpl.java
  core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImplTest.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImplIntegrationTest.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImplTest.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/assetindex/InMemoryAssetIndex.java
  extensions/control-plane/store/cosmos/assetindex-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndex.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/dataspaceconnector/sql/assetindex/SqlAssetIndex.java
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/asset/AssetIndex.java
  spi/common/core-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/asset/AssetIndexTestBase.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractDefinitionService.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractOfferQuery.java
Labels: bug

#2057 docs: clean up CODEOWNERS
  CODEOWNERS
Labels: no-changelog

#2056 fix(transferprocessApi): add id field in DataRequestDTO
  docs/swaggerui/swagger-spec.js
  extensions/control-plane/api/data-management/transferprocess-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/DataRequestDto.java
  extensions/control-plane/api/data-management/transferprocess-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/DataRequestToDataRequestDtoTransformer.java
  extensions/control-plane/api/data-management/transferprocess-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/transferprocess-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferProcessDtoTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/transferprocess-api.yaml
Labels: bug

#2061 docs: document BOM usages
  docs/developer/build-your-own-connector.md
Labels: documentation

#2065 chore: set output dir of the autodoc plugin
  build.gradle.kts
Labels: documentation, enhancement

#2053 fix(ContractOffer): add asset not null check when building a ContractOffer
  core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/TestFunctions.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandlerTest.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImplTest.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/ContractOfferToIdsContractOfferTransformerTest.java
  data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/OfferedAssetToIdsResourceTransformerTest.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerTest.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/service/ContractNegotiationServiceImplTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java
  spi/control-plane/contract-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOfferTest.java
Labels: bug

#2060 feat(api): add a `POST` endpoint to request the catalog
  core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartCatalogDescriptionRequestSender.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/util/RequestUtilTest.java
  docs/swaggerui/swagger-spec.js
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/ApiCoreExtension.java
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/model/CriterionDto.java
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/query/QuerySpecDto.java
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/transformer/CriterionDtoToCriterionTransformer.java
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/transformer/CriterionToCriterionDtoTransformer.java
  extensions/common/api/api-core/src/test/java/org/eclipse/dataspaceconnector/api/transformer/CriterionDtoToCriterionTransformerTest.java
  extensions/common/api/api-core/src/test/java/org/eclipse/dataspaceconnector/api/transformer/CriterionToCriterionDtoTransformerTest.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/Oauth2DefaultServicesExtension.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/rule/Oauth2AudienceValidationRule.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/rule/Oauth2ExpirationIssuedAtValidationRule.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/rule/Oauth2NotBeforeValidationRule.java
  extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/core/rule/Oauth2NotBeforeValidationRuleTest.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApi.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiController.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiExtension.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/model/CatalogRequestDto.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/transform/CatalogRequestDtoToQuerySpecTransformer.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerTest.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/TestFunctions.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/model/CatalogRequestDtoTest.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/transform/CatalogRequestDtoToQuerySpecTransformerTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiExtension.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/model/ContractDefinitionRequestDto.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/model/ContractDefinitionResponseDto.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/transform/ContractDefinitionToContractDefinitionResponseDtoTransformer.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/model/ContractDefinitionRequestDtoTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/model/ContractDefinitionRequestDtoValidationTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/model/ContractDefinitionResponseDtoTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/transform/ContractDefinitionRequestDtoToContractDefinitionTransformerTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/transform/ContractDefinitionToContractDefinitionResponseDtoTransformerTest.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/validation/ExpirationDateValidationRuleTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/catalog-api.yaml
  spi/common/oauth2-spi/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/spi/NoopCredentialsRequestAdditionalParametersProvider.java
  spi/federated-catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/FederatedCacheNodeFilter.java
Labels: enhancement

#2078 chore: update multiple GH action versions
  .github/actions/run-tests/action.yml
  .github/actions/setup-build/action.yml
  .github/workflows/verify.yaml
Labels: build

#2068 fix(validation): avoid policy evaluation on consumer side after agreement
  core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/ContractId.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/validation/ContractValidationService.java
  spi/control-plane/contract-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/ContractIdTest.java
Labels: bug

#2080 chore(ids): remove IdsDescriptorService
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/IdsCoreServiceExtension.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/descriptor/IdsDescriptorServiceImpl.java
  data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/descriptor/IdsDescriptorService.java
Labels: ids, refactoring

#2070 docs(adoption): add EDC extension for AAS as known friend
  known_friends.md
Labels: no-changelog

#2038 feat(gcs): add provisioner for GoogleCloudStorage
  docs/developer/modules.md
  extensions/common/gcp/gcp-core/build.gradle.kts
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/common/GcpAccessToken.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/common/GcpException.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/common/GcpServiceAccount.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/common/GcsBucket.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/iam/IamService.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/iam/IamServiceImpl.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/storage/GcsStoreSchema.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/storage/StorageService.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/storage/StorageServiceImpl.java
  extensions/common/gcp/gcp-core/src/test/java/org/eclipse/dataspaceconnector/gcp/core/iam/IamServiceImplTest.java
  extensions/common/gcp/gcp-core/src/test/java/org/eclipse/dataspaceconnector/gcp/core/storage/StorageServiceImplTest.java
  extensions/common/gcp/gcp-core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  extensions/control-plane/provision/gcs-provision/README.md
  extensions/control-plane/provision/gcs-provision/build.gradle.kts
  extensions/control-plane/provision/gcs-provision/src/main/java/org/eclipse/dataspaceconnector/gcp/storage/provision/GcsConsumerResourceDefinitionGenerator.java
  extensions/control-plane/provision/gcs-provision/src/main/java/org/eclipse/dataspaceconnector/gcp/storage/provision/GcsProvisionExtension.java
  extensions/control-plane/provision/gcs-provision/src/main/java/org/eclipse/dataspaceconnector/gcp/storage/provision/GcsProvisionedResource.java
  extensions/control-plane/provision/gcs-provision/src/main/java/org/eclipse/dataspaceconnector/gcp/storage/provision/GcsProvisioner.java
  extensions/control-plane/provision/gcs-provision/src/main/java/org/eclipse/dataspaceconnector/gcp/storage/provision/GcsResourceDefinition.java
  extensions/control-plane/provision/gcs-provision/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/control-plane/provision/gcs-provision/src/test/java/org/eclipse/dataspaceconnector/gcp/storage/provision/GcsProvisionerTest.java
  gradle.properties
  settings.gradle.kts
Labels: enhancement

#2076 chore: move ModuleNames plugin out, adapt build source
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/ModuleNamesPlugin.java
  docs/swaggerui/swagger-ui-bundle.js
  docs/swaggerui/swagger-ui-bundle.js.map
  docs/swaggerui/swagger-ui-es-bundle-core.js
  docs/swaggerui/swagger-ui-es-bundle-core.js.map
  docs/swaggerui/swagger-ui-es-bundle.js
  docs/swaggerui/swagger-ui-es-bundle.js.map
  docs/swaggerui/swagger-ui-standalone-preset.js
  docs/swaggerui/swagger-ui-standalone-preset.js.map
  docs/swaggerui/swagger-ui.css
  docs/swaggerui/swagger-ui.css.map
  docs/swaggerui/swagger-ui.js
  docs/swaggerui/swagger-ui.js.map
  settings.gradle.kts
Labels: enhancement, build

#2063 docs: remove Docsify related files
  docs/.nojekyll
  docs/_coverpage.md
  docs/_media/edc-overview.png
  docs/_media/favicon.ico
  docs/_media/icon.png
  docs/index.html
Labels: no-changelog

#2084 feat(api): add `POST` endpoint to all APIs
  docs/swaggerui/swagger-spec.js
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/model/CriterionDto.java
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/query/QuerySpecDto.java
  extensions/common/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/transformer/QuerySpecDtoToQuerySpecTransformer.java
  extensions/common/api/api-core/src/test/java/org/eclipse/dataspaceconnector/api/transformer/QuerySpecDtoToQuerySpecTransformerTest.java
  extensions/control-plane/api/data-management/asset-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApi.java
  extensions/control-plane/api/data-management/asset-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiController.java
  extensions/control-plane/api/data-management/asset-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/asset-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiControllerTest.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApi.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiController.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiExtension.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/model/CatalogRequestDto.java
  extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/transform/CatalogRequestDtoToQuerySpecTransformer.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerTest.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/model/CatalogRequestDtoTest.java
  extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/transform/CatalogRequestDtoToQuerySpecTransformerTest.java
  extensions/control-plane/api/data-management/contractagreement-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApi.java
  extensions/control-plane/api/data-management/contractagreement-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiController.java
  extensions/control-plane/api/data-management/contractagreement-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/contractagreement-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiControllerTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApi.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiController.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/contractdefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerTest.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApi.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiController.java
  extensions/control-plane/api/data-management/contractnegotiation-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/policydefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApi.java
  extensions/control-plane/api/data-management/policydefinition-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApiController.java
  extensions/control-plane/api/data-management/policydefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/policydefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApiControllerTest.java
  extensions/control-plane/api/data-management/transferprocess-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApi.java
  extensions/control-plane/api/data-management/transferprocess-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiController.java
  extensions/control-plane/api/data-management/transferprocess-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/control-plane/api/data-management/transferprocess-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/asset-api.yaml
  resources/openapi/yaml/catalog-api.yaml
  resources/openapi/yaml/contractagreement-api.yaml
  resources/openapi/yaml/contractdefinition-api.yaml
  resources/openapi/yaml/contractnegotiation-api.yaml
  resources/openapi/yaml/policydefinition-api.yaml
  resources/openapi/yaml/transferprocess-api.yaml
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QuerySpec.java
Labels: enhancement, api

#2092 chore(github): remove checklist from issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: no-changelog

#2071 feat(build): adds manifest files as maven artifacts
  build.gradle.kts
  docs/developer/autodoc.md
Labels: documentation, enhancement, build

#2095 refactor(iam): remove unused dummy-credentials-verifier
  docs/developer/modules.md
  extensions/common/iam/decentralized-identity/dummy-credentials-verifier/build.gradle.kts
  extensions/common/iam/decentralized-identity/dummy-credentials-verifier/src/main/java/org/eclipse/dataspaceconnector/iam/verifier/DummyCredentialsVerifier.java
  extensions/common/iam/decentralized-identity/dummy-credentials-verifier/src/main/java/org/eclipse/dataspaceconnector/iam/verifier/DummyCredentialsVerifierExtension.java
  extensions/common/iam/decentralized-identity/dummy-credentials-verifier/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  settings.gradle.kts
Labels: refactoring

#2067 docs: add decision record for naming conventions
  docs/developer/decision-records/2022-10-10-naming-conventions/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#2079 chore: use TestSummary plugin from repositories
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/SummaryPrinterAdapter.java
  buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/TestSummaryPlugin.java
  gradle.properties
Labels: build

#2096 refactor(ContractNegotiationStore): remove ContractNegotiationStore.getAgreementsForDefinitionId
  core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/InMemoryContractNegotiationStore.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/InMemoryContractNegotiationStoreTest.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/schema/ContractNegotiationStatements.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStore.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStoreTestBase.java
Labels: refactoring

#2102 refactor(ContractValidationService): rename interface methods + docs
  core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/validation/ContractValidationService.java
Labels: documentation, refactoring

#2087 feat(DataPlaneInstanceStore): add SQL store implementation
  core/data-plane-selector/data-plane-selector-core/build.gradle.kts
  core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/core/DataPlaneSelectorDefaultServicesExtension.java
  core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/InMemoryDataPlaneInstanceStore.java
  core/data-plane-selector/data-plane-selector-core/src/test/java/org/eclipse/dataspaceconnector/dataplane/selector/store/InMemoryDataPlaneInstanceStoreTest.java
  docs/developer/modules.md
  extensions/data-plane-selector/selector-api/src/test/java/org/eclipse/dataspaceconnector/dataplane/selector/api/DataplaneSelectorApiControllerIntegrationTest.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/build.gradle.kts
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/docs/schema.sql
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/SqlDataPlaneInstanceStore.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/SqlDataPlaneInstanceStoreExtension.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/schema/BaseSqlDataPlaneInstanceStatements.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/schema/DataPlaneInstanceStatements.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/schema/postgres/PostgresDataPlaneInstanceStatements.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/test/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/PostgresDataPlaneInstanceStoreTest.java
  settings.gradle.kts
  spi/data-plane-selector/data-plane-selector-spi/build.gradle.kts
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/dataplane/selector/TestDataPlaneInstance.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/dataplane/selector/TestFunctions.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/dataplane/selector/store/DataPlaneInstanceStoreTestBase.java
Labels: enhancement

#2110 refactor: remove module list (generation)
  README.md
  build.gradle.kts
  docs/developer/modules.md
  docs/developer/releases.md
Labels: no-changelog

#2097 refactor: use `@Setting` and `@SettingContext`
  core/common/connector-core/src/main/java/org/eclipse/dataspaceconnector/core/CoreDefaultServicesExtension.java
  core/common/connector-core/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
  core/common/connector-core/src/main/java/org/eclipse/dataspaceconnector/core/base/OkHttpClientFactory.java
  core/control-plane/contract-core/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtension.java
  data-protocols/ids/ids-api-configuration/src/main/java/org/eclipse/dataspaceconnector/ids/api/configuration/IdsApiConfigurationExtension.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/IdsCoreServiceExtension.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceSettings.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/util/ConnectorIdUtil.java
  data-protocols/ids/ids-token-validation/src/main/java/org/eclipse/dataspaceconnector/ids/token/validation/IdsTokenValidationServiceExtension.java
  docs/developer/architecture/architecture-principles.md
  docs/developer/architecture/configuration/README.md
  docs/developer/decision-records/2022-08-04-documentation-automation/README.md
  docs/developer/decision-records/2022-09-23-extract-metamodel-and-autodoc/README.md
  extensions/common/auth/auth-basic/src/main/java/org/eclipse/dataspaceconnector/api/auth/BasicAuthenticationExtension.java
  extensions/common/auth/auth-tokenbased/src/main/java/org/eclipse/dataspaceconnector/api/auth/TokenBasedAuthenticationExtension.java
  extensions/common/aws/aws-s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/S3CoreExtension.java
  extensions/common/azure/azure-blob-core/src/main/java/org/eclipse/dataspaceconnector/azure/blob/core/BlobStoreCoreExtension.java
  extensions/common/azure/azure-cosmos-core/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/AbstractCosmosConfig.java
  extensions/common/azure/azure-eventgrid/src/main/java/org/eclipse/dataspaceconnector/events/azure/AzureEventGridConfig.java
  extensions/common/configuration/configuration-filesystem/src/main/java/org/eclipse/dataspaceconnector/configuration/fs/FsConfigurationExtension.java
  extensions/common/events/events-cloud-http/src/main/java/org/eclipse/dataspaceconnector/events/cloudevents/http/CloudEventsHttpExtension.java
  extensions/common/http/jersey-core/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyConfiguration.java
  extensions/common/http/jersey-micrometer/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyMicrometerExtension.java
  extensions/common/http/jetty-core/src/main/java/org/eclipse/dataspaceconnector/extension/jetty/JettyConfiguration.java
  extensions/common/http/jetty-core/src/main/java/org/eclipse/dataspaceconnector/extension/jetty/JettyExtension.java
  extensions/common/http/jetty-micrometer/src/main/java/org/eclipse/dataspaceconnector/extension/jetty/JettyMicrometerExtension.java
  extensions/common/iam/decentralized-identity/identity-did-web/src/main/java/org/eclipse/dataspaceconnector/iam/did/web/ConfigurationKeys.java
  extensions/common/iam/decentralized-identity/identity-did-web/src/main/java/org/eclipse/dataspaceconnector/iam/did/web/WebDidExtension.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/Oauth2Extension.java
  extensions/common/micrometer/micrometer-core/src/main/java/org/eclipse/dataspaceconnector/metrics/micrometer/MicrometerExtension.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/dataspaceconnector/sql/pool/commons/CommonsConnectionPoolConfigKeys.java
  extensions/common/transaction/transaction-atomikos/src/main/java/org/eclipse/dataspaceconnector/transaction/atomikos/DataSourceConfigurationKeys.java
  extensions/common/transaction/transaction-atomikos/src/main/java/org/eclipse/dataspaceconnector/transaction/atomikos/TransactionManagerConfigurationKeys.java
  extensions/common/vault/vault-azure/src/main/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVaultExtension.java
  extensions/common/vault/vault-filesystem/src/main/java/org/eclipse/dataspaceconnector/core/security/fs/FsConfiguration.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVaultExtension.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/DataPlaneTransferClientExtension.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncConfig.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncExtension.java
  extensions/control-plane/http-receiver/src/main/java/org/eclipse/dataspaceconnector/receiver/http/HttpEndpointDataReferenceReceiverExtension.java
  extensions/control-plane/provision/gcs-provision/src/main/java/org/eclipse/dataspaceconnector/gcp/storage/provision/GcsProvisionExtension.java
  extensions/control-plane/provision/http-provision/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpWebhookExtension.java
  extensions/control-plane/provision/http-provision/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/config/ConfigParser.java
  extensions/control-plane/provision/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/AwsProvisionExtension.java
  extensions/control-plane/store/cosmos/asset-index-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/AssetIndexCosmosConfig.java
  extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/TransferProcessStoreCosmosConfig.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/dataspaceconnector/sql/assetindex/ConfigurationKeys.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreExtension.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/policy/SqlPolicyStoreExtension.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/SqlTransferProcessStoreExtension.java
  extensions/data-plane-selector/data-plane-selector-client/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/DataPlaneInstanceClientExtension.java
  extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/DataPlaneApiExtension.java
  extensions/data-plane/data-plane-azure-data-factory/src/main/java/org/eclipse/dataspaceconnector/azure/dataplane/azuredatafactory/DataPlaneAzureDataFactoryExtension.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpExtension.java
  extensions/federated-catalog/store/fcc-node-directory-cosmos/src/main/java/org/eclipse/dataspaceconnector/catalog/node/directory/azure/FederatedCacheNodeDirectoryCosmosConfig.java
  spi/common/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/document/DidConstants.java
  spi/federated-catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/CacheConfiguration.java
Labels: refactoring

#2113 chore: rename ContractOfferService to ContractOfferResolver
  core/control-plane/contract-core/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
  core/control-plane/contract-core/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferResolverImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferResolverImplIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferResolverImplTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandlerTest.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/IdsCoreServiceExtension.java
  data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImpl.java
  data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImplTest.java
  extensions/control-plane/api/data-management-api/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractOfferResolver.java
Labels: refactoring

#2112 feat(dataplane gcs): add dataplane for Google Cloud Storage
  core/data-plane/data-plane-util/src/main/java/org/eclipse/dataspaceconnector/dataplane/common/validation/CompositeValidationRule.java
  core/data-plane/data-plane-util/src/main/java/org/eclipse/dataspaceconnector/dataplane/common/validation/EmptyValueValidationRule.java
  core/data-plane/data-plane-util/src/main/java/org/eclipse/dataspaceconnector/dataplane/common/validation/ValidationRule.java
  core/data-plane/data-plane-util/src/test/java/org/eclipse/dataspaceconnector/dataplane/common/validation/ValidationRuleTest.java
  extensions/common/gcp/gcp-core/src/main/java/org/eclipse/dataspaceconnector/gcp/core/storage/StorageServiceImpl.java
  extensions/control-plane/provision/gcs-provision/README.md
  extensions/control-plane/provision/gcs-provision/src/main/java/org/eclipse/dataspaceconnector/gcp/storage/provision/GcsProvisionExtension.java
  extensions/control-plane/provision/gcs-provision/src/main/java/org/eclipse/dataspaceconnector/gcp/storage/provision/GcsProvisioner.java
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSinkFactory.java
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSourceFactory.java
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/validation/S3DataAddressCredentialsValidationRule.java
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/validation/S3DataAddressValidationRule.java
  extensions/data-plane/data-plane-google-storage/README.md
  extensions/data-plane/data-plane-google-storage/build.gradle.kts
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/DataPlaneGcsExtension.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/GcsDataSink.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/GcsDataSinkFactory.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/GcsDataSource.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/GcsDataSourceFactory.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/validation/GcsSinkDataAddressValidationRule.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/validation/GcsSourceDataAddressValidationRule.java
  extensions/data-plane/data-plane-google-storage/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  extensions/data-plane/data-plane-google-storage/src/test/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/GcsDataSinkFactoryTest.java
  extensions/data-plane/data-plane-google-storage/src/test/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/GcsDataSourceFactoryTest.java
  extensions/data-plane/data-plane-google-storage/src/test/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/TestFunctions.java
  settings.gradle.kts
Labels: enhancement

#2121 docs: add decision record about EDC version catalogs
  docs/developer/decision-records/2022-10-21-gradle-versioncatalogs/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#2120 refactor(SqlStore): create a base class for all SQL stores
  extensions/common/sql/sql-core/build.gradle.kts
  extensions/common/sql/sql-core/src/main/java/org/eclipse/dataspaceconnector/sql/store/AbstractSqlStore.java
  extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/dataspaceconnector/sql/PostgresqlStoreSetupExtension.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/dataspaceconnector/sql/assetindex/SqlAssetIndex.java
  extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/dataspaceconnector/sql/assetindex/PostgresAssetIndexTest.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreExtension.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/PostgresContractDefinitionStoreTest.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/build.gradle.kts
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/SqlContractNegotiationStoreExtension.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/policy/SqlPolicyStoreExtension.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/policy/store/SqlPolicyDefinitionStore.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/policy/store/PostgresPolicyDefinitionStoreTest.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStore.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/PostgresTransferProcessStoreTest.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/SqlDataPlaneInstanceStore.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/test/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/PostgresDataPlaneInstanceStoreTest.java
Labels: refactoring

#2123 fix: add more logging to data-plane extensions (fixes #2122)
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtension.java
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/pipeline/PipelineServiceImpl.java
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/e2e/EndToEndTest.java
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/pipeline/PipelineServiceImplTest.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/DataPlaneTransferClientExtension.java
Labels: enhancement, dpf

#2125 docs: add description about rule of PR title (fixes #2124)
  .github/PULL_REQUEST_TEMPLATE.md
  pr_etiquette.md
Labels: documentation

#2140 feat: make default_iteration_wait on state_machines configurable
  core/control-plane/contract-core/README.md
  core/control-plane/contract-core/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
  core/control-plane/transfer-core/README.md
  core/control-plane/transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
Labels: enhancement

#2147 fix(jerseyExtension): flaky test ExceptionMappersIntegrationTest
  extensions/common/http/jersey-core/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/mapper/ExceptionMappersIntegrationTest.java
Labels: bug, flaky test

#2119 docs: Add ADR for creation of Trust Framework Adoption repository
  docs/developer/decision-records/2022-10-20-trust-framework-adoption-repository/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#2116 feat(transferprocess): introduced a comunication channel from data-plane to control-plane
  core/control-plane/control-plane-api-client/build.gradle.kts
  core/control-plane/control-plane-api-client/src/main/java/org/eclipse/dataspaceconnector/controlplane/api/client/ControlPlaneApiClientExtension.java
  core/control-plane/control-plane-api-client/src/main/java/org/eclipse/dataspaceconnector/controlplane/api/client/transferprocess/TransferProcessHttpClient.java
  core/control-plane/control-plane-api-client/src/main/java/org/eclipse/dataspaceconnector/controlplane/api/client/transferprocess/model/TransferProcessFailRequest.java
  core/control-plane/control-plane-api-client/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  core/control-plane/control-plane-api-client/src/test/java/org/eclipse/dataspaceconnector/controlplane/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  core/control-plane/control-plane-api/build.gradle.kts
  core/control-plane/control-plane-api/src/main/java/org/eclipse/dataspaceconnector/controlplane/api/ControlPlaneApiExtension.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/dataspaceconnector/controlplane/api/transferprocess/TransferProcessControlApi.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/dataspaceconnector/controlplane/api/transferprocess/TransferProcessControlApiController.java
  core/control-plane/control-plane-api/src/main/java/org/eclipse/dataspaceconnector/controlplane/api/transferprocess/model/TransferProcessFailStateDto.java
  core/control-plane/control-plane-api/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  core/control-plane/control-plane-api/src/test/java/org/eclipse/dataspaceconnector/controlplane/api/TransferProcessControlApiControllerIntegrationTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/core/TransferProcessCommandExtension.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CancelTransferCommandHandler.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CompleteTransferCommandHandler.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/DeprovisionRequestHandler.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/FailTransferCommandHandler.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/SingleTransferProcessCommandHandler.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CompleteTransferCommandHandlerTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/FailTransferCommandHandlerTest.java
  core/data-plane/data-plane-framework/build.gradle.kts
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneDefaultServicesExtension.java
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtension.java
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImpl.java
  core/data-plane/data-plane-framework/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtensionTest.java
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/e2e/EndToEndTest.java
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  docs/swaggerui/swagger-spec.js
  extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/DataPlaneTransferClientExtension.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/flow/DataPlaneTransferFlowController.java
  extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/flow/DataPlaneTransferFlowControllerTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/control-plane-api.yaml
  resources/openapi/yaml/data-plane-api.yaml
  settings.gradle.kts
  spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataFlowRequest.java
  spi/common/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataFlowRequestTest.java
  spi/control-plane/control-plane-api-client-spi/build.gradle.kts
  spi/control-plane/control-plane-api-client-spi/src/main/java/org/eclipse/dataspaceconnector/spi/controlplane/api/client/package-info.java
  spi/control-plane/control-plane-api-client-spi/src/main/java/org/eclipse/dataspaceconnector/spi/controlplane/api/client/transferprocess/NoopTransferProcessClient.java
  spi/control-plane/control-plane-api-client-spi/src/main/java/org/eclipse/dataspaceconnector/spi/controlplane/api/client/transferprocess/TransferProcessApiClient.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/callback/ControlPlaneApiUrl.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/command/CompleteTransferCommand.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/command/FailTransferCommand.java
Labels: enhancement, core feature, api, dpf
