Repository eclipse-edc/Connector, pull requests merged in 2022-06, with the labels that each got.

#1384 workflow: update pull-request-auto-assign-project.yaml
  .github/workflows/pull-request-auto-assign-project.yaml
Labels: no-changelog

#1385 test: fix cosmosdb integration test
  extensions/azure/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreIntegrationTest.java
Labels: no-changelog

#1393 workflow: close inactive issues
  .github/workflows/assign-issue-to-project.yaml
  .github/workflows/assign-pr-to-project.yaml
  .github/workflows/close-inactive-issues.yml
Labels: no-changelog

#1396 chore: allow manual triggering of close-inactive-issue workflow
  .github/workflows/close-inactive-issues.yml
Labels: no-changelog

#1398 chore: refine close-inactive-issue workflow
  .github/workflows/close-inactive-issues.yml
Labels: no-changelog

#1391 docs: update ids-api-configuration README
  data-protocols/ids/ids-api-configuration/README.md
Labels: no-changelog

#1399 chore: activate close-inactive-issue workflow
  .github/workflows/close-inactive-issues.yml
Labels: no-changelog

#1408 Bugfix: check to determine if asset can be deleted
  common/util/build.gradle.kts
  common/util/src/main/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtil.java
  common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/AnotherObject.java
  common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtilTest.java
  common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestObjectSubSubclass.java
  core/defaults/src/main/java/org/eclipse/dataspaceconnector/core/defaults/negotiationstore/InMemoryContractNegotiationStore.java
  core/defaults/src/test/java/org/eclipse/dataspaceconnector/core/defaults/negotiationstore/InMemoryContractNegotiationStoreTest.java
  extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImpl.java
  extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImplTest.java
  extensions/azure/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
  extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
  extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreTest.java
  extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/TestFunctions.java
  extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/model/ContractNegotiationDocumentSerializationTest.java
  extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/ContractNegotiationStatements.java
  extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresStatements.java
  extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
  extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/TestFunctions.java
  extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java
  spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStore.java
Labels: no-changelog

#1421 Doc: adds info about stale issues/PRs
  CONTRIBUTING.md
Labels: no-changelog

#1389 System tests: extend Gatling scope
  .github/workflows/performancetests.yaml
  extensions/azure/azure-test/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/testfixtures/AbstractAzureBlobTest.java
  extensions/azure/azure-test/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/testfixtures/TestFunctions.java
  extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerStatusCheckerIntegrationTest.java
  extensions/azure/data-plane/storage/src/test/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/AzureDataPlaneCopyIntegrationTest.java
  system-tests/azure-data-factory-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/AzureDataFactoryTransferIntegrationTest.java
  system-tests/azure-tests/build.gradle.kts
  system-tests/azure-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferIntegrationTest.java
  system-tests/azure-tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferLocalSimulation.java
  system-tests/azure-tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferSimulationConfiguration.java
  system-tests/azure-tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferUtils.java
  system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
  system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/FileTransferSimulationConfiguration.java
  system-tests/tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/local/TransferLocalSimulation.java
  system-tests/tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/utils/TransferSimulationConfiguration.java
  system-tests/tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/utils/TransferSimulationUtils.java
Labels: no-changelog

#1394 Flaky test: Update test to avoid key removal conflict during parallel test runs
  extensions/azure/data-plane/data-factory/src/test/java/org/eclipse/dataspaceconnector/azure/dataplane/azuredatafactory/AzureDataFactoryCopyIntegrationTest.java
Labels: no-changelog

#1400 decision record: ids serializer implementation
  docs/developer/decision-records/2022-06-02-ids-serializer/README.md
  docs/developer/decision-records/README.md
Labels: no-changelog

#1413 docs: add event framework decision record
  docs/developer/decision-records/2022-06-03-event-framework/README.md
  docs/developer/decision-records/README.md
Labels: no-changelog

#1443 Bugfix: brings back the edcVersion variable in the build file
  build.gradle.kts
  gradle.properties
Labels: no-changelog

#1447 Fix: Removes a log line that was forgotten previously
  build.gradle.kts
Labels: bug, no-changelog

#1414 Feature: create CosmosDB with terraform for integration testing
  extensions/azure/azure-test/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/testfixtures/CosmosTestClient.java
  resources/azure/testing/terraform-apply.sh
  resources/azure/testing/terraform/main.tf
  resources/azure/testing/terraform/outputs.tf
Labels: no-changelog

#1462 Core: shared Clock DR
  docs/developer/decision-records/2022-06-09-shared-clock/README.md
  docs/developer/decision-records/README.md
Labels: no-changelog

#1498 Bugfix: change time when loaders are cleared
  CHANGELOG.md
  extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
  extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/loader/LoaderManagerImpl.java
  extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/management/PartitionManagerImpl.java
  extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/LoaderManager.java
Labels: bug

#1516 chore: optimize GitHub project management
  .github/workflows/assign-issue-to-project.yaml
  .github/workflows/assign-pr-to-project.yaml
  .github/workflows/close-inactive-issues.yml
Labels: no-changelog

#1518 chore(dependabot): add dependabot.yml to activate auto dependency updates
  .github/dependabot.yml
Labels: no-changelog

#1536 Fix: throw auth-failed exception
  extensions/api/auth-spi/src/main/java/org/eclipse/dataspaceconnector/api/auth/AuthenticationRequestFilter.java
  extensions/api/auth-spi/src/test/java/org/eclipse/dataspaceconnector/api/auth/AuthenticationRequestFilterTest.java
  spi/web-spi/src/main/java/org/eclipse/dataspaceconnector/spi/exception/AuthenticationFailedException.java
Labels: no-changelog

#1543 build(deps): update github_actions dependencies
  .github/workflows/codeql-analysis.yml
  .github/workflows/performancetests.yaml
  .github/workflows/scan-pull-request.yaml
  .github/workflows/verify.yaml
Labels: no-changelog, dependencies, github_actions
