Repository eclipse-edc/Connector, pull requests merged in 2023-07, with the labels that each got.

#3255 docs: add decision record about using Testcontainers
  docs/developer/decision-records/2023-06-30-allow-use-of-testcontainers/README.md
  docs/developer/decision-records/README.md
  docs/developer/testing.md
Labels: documentation

#3256 fix: end to end transfer process flaky test
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
Labels: bug, flaky test

#3257 build(deps): bump opentelemetry versions
  core/control-plane/contract-core/build.gradle.kts
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/control-plane-aggregate-services/build.gradle.kts
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java
  core/control-plane/transfer-core/build.gradle.kts
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImpl.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/provision/ProvisionManagerImpl.java
  core/data-plane/data-plane-framework/build.gradle.kts
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceTransferServiceImpl.java
  core/data-plane/data-plane-util/build.gradle.kts
  core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/sink/ParallelSink.java
  extensions/data-plane/data-plane-client/build.gradle.kts
  extensions/data-plane/data-plane-client/src/main/java/org/eclipse/edc/connector/dataplane/client/EmbeddedDataPlaneClient.java
  extensions/data-plane/data-plane-client/src/main/java/org/eclipse/edc/connector/dataplane/client/RemoteDataPlaneClient.java
  gradle/libs.versions.toml
  system-tests/telemetry/telemetry-test-runner/build.gradle.kts
  system-tests/telemetry/telemetry-test-runner/src/test/java/org/eclipse/edc/test/e2e/tracing/TracingEndToEndTest.java
  system-tests/tests/build.gradle.kts
Labels: build, dependencies

#3264 docs: update build your own connector
  docs/developer/build-your-own-connector.md
Labels: documentation

#3258 feat(protocol): add ContractOfferMessage
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiController.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiControllerTest.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/dispatcher/DspNegotiationHttpDispatcherExtension.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/dispatcher/delegate/ContractOfferMessageHttpDelegate.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/dispatcher/delegate/ContractOfferMessageHttpDelegateTest.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/DspNegotiationTransformExtension.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractOfferMessageTransformer.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractOfferMessageTransformer.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractOfferMessageTransformerTest.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractOfferMessageTransformerTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractOfferMessage.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessage.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractnegotiation/ContractNegotiationProtocolService.java
Labels: enhancement, dataspace-protocol

#3265 docs: add example to contract definition management api
  extensions/common/api/api-core/build.gradle.kts
  extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/ApiCoreExtension.java
  extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/model/ApiCoreSchema.java
  extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/transformer/JsonObjectToQuerySpecDtoTransformer.java
  extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/model/ApiCoreSchemaTest.java
  extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/JsonObjectToQuerySpecDtoTransformerTest.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiExtension.java
  extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java
  extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiTest.java
  gradle/libs.versions.toml
  resources/openapi/openapi.yaml
  resources/openapi/yaml/management-api/contract-definition-api.yaml
Labels: documentation, api

#3270 docs: add example to asset management api
  core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplPerformanceTest.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetCreationRequestDto.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetEntryDto.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetEntryNewDto.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetRequestDto.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetResponseDto.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetUpdateRequestDto.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetUpdateRequestWrapperDto.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v2/AssetApi.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v2/AssetApiController.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApiController.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/validation/AssetEntryDtoValidator.java
  extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApiTest.java
  extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java
  extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/management-api/asset-api.yaml
  resources/openapi/yaml/management-api/contract-definition-api.yaml
Labels: documentation, api

#3272 docs: add openapi examples for policy definition endpoints
  core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/TestServiceExtensionContext.java
  data-protocols/dsp/dsp-transform/src/main/java/org/eclipse/edc/protocol/dsp/transform/DspTransformExtension.java
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/OdrlTransformersFactory.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApi.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiController.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiExtension.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionDto.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionRequestDto.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionResponseDto.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionUpdateDto.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionUpdateWrapperDto.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/transform/JsonObjectFromPolicyDefinitionTransformer.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/transform/JsonObjectToPolicyDefinitionTransformer.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/transform/JsonObjectToPolicyDefinitionUpdateDtoTransformer.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/transform/PolicyDefinitionRequestDtoToPolicyDefinitionTransformer.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/transform/PolicyDefinitionToPolicyDefinitionResponseDtoTransformer.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/transform/PolicyDefinitionUpdateWrapperDtoToPolicyDefinitionTransformer.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/validation/PolicyDefinitionValidator.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiControllerTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiExtensionTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionRequestDtoTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionResponseDtoTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionUpdateDtoTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/transform/JsonObjectFromPolicyDefinitionResponseDtoTransformerTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/transform/JsonObjectFromPolicyDefinitionTransformerTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/transform/JsonObjectToPolicyDefinitionTransformerTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/transform/PolicyDefinitionRequestDtoToPolicyDefinitionTransformerTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/transform/PolicyDefinitionToPolicyDefinitionResponseDtoTransformerTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/transform/PolicyDefinitionUpdateWrapperDtoToPolicyDefinitionTransformerTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/validation/PolicyDefinitionValidatorTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/management-api/policy-definition-api.yaml
  spi/control-plane/policy-spi/src/main/java/org/eclipse/edc/connector/policy/spi/PolicyDefinition.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
Labels: documentation, api

#3277 feat: make http client timeouts configurable
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreDefaultServicesExtension.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/OkHttpClientFactory.java
  core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/OkHttpClientFactoryTest.java
Labels: enhancement

#3268 feat(test): convert all postgres tests to use testcontainers
  core/common/junit/build.gradle.kts
  core/common/junit/src/main/java/org/eclipse/edc/junit/annotations/PostgresqlDbIntegrationTest.java
  extensions/common/sql/sql-core/build.gradle.kts
  extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/SqlQueryExecutorIntegrationTest.java
  extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlLocalInstance.java
  extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlStoreSetupExtension.java
  extensions/common/sql/sql-lease/src/test/java/org/eclipse/edc/sql/lease/PostgresLeaseContextTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultIntegrationTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/PathUtilTest.java
  extensions/control-plane/store/sql/asset-index-sql/build.gradle.kts
  extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/PostgresAssetIndexTest.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractdefinition/PostgresContractDefinitionStoreTest.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/policydefinition/PostgresPolicyDefinitionStoreTest.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/transferprocess/PostgresTransferProcessStoreTest.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/sql/PostgresDataPlaneInstanceStoreTest.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/store/sql/PostgresDataPlaneStoreTest.java
  gradle/libs.versions.toml
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferPostgresqlTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/PostgresConstants.java
Labels: enhancement, refactoring, build

#3276 feat(build): add dependency check to CI workflow
  .github/workflows/dependency-review.yml
  .github/workflows/verify.yaml
  DEPENDENCIES
  NOTICE.md
  docs/developer/releases.md
  docs/legal/generateThirdPartyReport.sh
Labels: documentation, enhancement, build

#3285 feat: Add fixtures for end-to-end transfer tests
  settings.gradle.kts
  system-tests/e2e-test-fixtures/build.gradle.kts
  system-tests/e2e-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java
  system-tests/e2e-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/PolicyFixtures.java
  system-tests/e2e-transfer-test/runner/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndKafkaTransferTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferPostgresqlTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java
  system-tests/tests/build.gradle.kts
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/local/TransferRuntimeConfiguration.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferConfiguration.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferTestClient.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferTestRunner.java
Labels: enhancement

#3294 chore: update DEPENDENCIES file with latest approvals
  DEPENDENCIES
Labels: documentation

#3290 feat: avoid creating temporary files when loading json-ld document cache
  .github/workflows/dependency-review.yml
  core/common/junit/src/main/java/org/eclipse/edc/junit/testfixtures/TestUtils.java
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/document/JarLoader.java
  extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/TitaniumJsonLdTest.java
  extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/document/JarLoaderTest.java
  extensions/common/json-ld/src/test/resources/.gitignore
  extensions/common/json-ld/src/test/resources/jar-with-resource-example.jar
  spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/JsonLd.java
Labels: enhancement

#3297 refactor: get rid of `managedResource`
  .github/workflows/dependency-review.yml
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplIntegrationTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImplTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/model/TransferRequestDto.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/JsonObjectToTransferRequestDtoTransformer.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferRequestDtoToTransferRequestTransformer.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/transform/JsonObjectToTransferRequestDtoTransformerTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferRequestDtoToTransferRequestTransformerTest.java
  extensions/control-plane/store/sql/transfer-process-store-sql/docs/schema.sql
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/TransferProcessStoreStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/DataRequestMapping.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/README.md
  resources/openapi/openapi.yaml
  resources/openapi/yaml/management-api/transfer-process-api.yaml
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/DataRequest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/ProvisionedResource.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/ProvisionedResourceSet.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TestFunctions.java
Labels: refactoring

#3298 feat(ci): improve outputting dependencies if they are different
  .github/workflows/dependency-review.yml
Labels: enhancement, github_actions

#3301 feat(ci): reuse dependency check from .github
  .github/workflows/dependency-review.yml
Labels: enhancement, github_actions

#3300 chore: remove unneeded method
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/TransferProcessManager.java
Labels: refactoring

#3296 feat(ci): publish OpenAPI specs on releases
  .github/workflows/apidoc.yaml
  .github/workflows/release-edc.yml
Labels: documentation, api, build

#3299 feat: add agreement endpoints schema examples
  extensions/common/api/management-api-configuration/build.gradle.kts
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtension.java
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchema.java
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/transform/JsonObjectFromContractAgreementTransformer.java
  extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchemaTest.java
  extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/transform/JsonObjectFromContractAgreementTransformerTest.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApi.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiController.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiExtension.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/model/ContractAgreementDto.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/transform/ContractAgreementToContractAgreementDtoTransformer.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/transform/JsonObjectFromContractAgreementDtoTransformer.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiControllerTest.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/management/contractagreement/model/ContractAgreementDtoTest.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/management/contractagreement/transform/ContractAgreementToContractAgreementDtoTransformerTest.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/management/contractagreement/transform/JsonObjectFromContractAgreementDtoTransformerTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiExtension.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiTest.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/management-api/contract-agreement-api.yaml
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/asset/AssetEntry.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiDeprecatedEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/BaseManagementApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractAgreementApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractDefinitionApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
Labels: documentation, enhancement, api

#3306 feat: add catalog endpoints schema examples
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/JsonWalkers.java
  docs/developer/custom_validation.md
  extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/model/ApiCoreSchema.java
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchema.java
  extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchemaTest.java
  extensions/control-plane/api/management-api/catalog-api/build.gradle.kts
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApi.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiController.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiExtension.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/model/CatalogRequestDto.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/transform/CatalogRequestDtoToCatalogRequestTransformer.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/transform/JsonObjectToCatalogRequestDtoTransformer.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/transform/JsonObjectToCatalogRequestTransformer.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/validation/CatalogRequestValidator.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiControllerTest.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiExtensionTest.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiTest.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/TestFunctions.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/model/CatalogRequestMessageDtoTest.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/transform/JsonObjectToCatalogRequestDtoTransformerTest.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/transform/JsonObjectToCatalogRequestTransformerTest.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/validation/CatalogRequestValidatorTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApi.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/management-api/asset-api.yaml
  resources/openapi/yaml/management-api/catalog-api.yaml
  resources/openapi/yaml/management-api/contract-agreement-api.yaml
  resources/openapi/yaml/management-api/contract-definition-api.yaml
  resources/openapi/yaml/management-api/contract-negotiation-api.yaml
  resources/openapi/yaml/management-api/policy-definition-api.yaml
  resources/openapi/yaml/management-api/transfer-process-api.yaml
  spi/common/catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CatalogRequest.java
  system-tests/e2e-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
  system-tests/telemetry/telemetry-test-runner/src/test/java/org/eclipse/edc/test/e2e/tracing/MicrometerEndToEndTest.java
Labels: documentation, enhancement, api

#3307 feat: permit to configure fs vault with configuration file
  core/common/util/src/main/java/org/eclipse/edc/util/configuration/ConfigurationFunctions.java
  core/common/util/src/test/java/org/eclipse/edc/util/configuration/ConfigurationFunctionsTest.java
  extensions/common/vault/vault-filesystem/src/main/java/org/eclipse/edc/vault/filesystem/FsVaultExtension.java
Labels: enhancement

#3316 chore: handle missing destination in transfer protocol service
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java
Labels: enhancement, dataspace-protocol

#3318 docs: add decision record about state machine manual interactions
  DEPENDENCIES
  docs/developer/decision-records/2023-07-20-state-machine-guards/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#3326 fix: create openapi only on pushes to main
  .github/workflows/apidoc.yaml
Labels: bug

#3327 fix(jersey): bind controllers to the correct context
  extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyRestService.java
  extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/JerseyRestServiceTest.java
Labels: bug

#3331 docs: add documentation about the in-force policy
  docs/developer/contract-duration/contract-validity-check.md
  docs/developer/contract-duration/policy.inforce.duration.json
  docs/developer/contract-duration/policy.inforce.fixed.json
Labels: documentation

#3321 feat: add pending state to `ContractNegotiation` and `TransferProcess`
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/Processor.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/ProcessorImpl.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/StateMachineManager.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/StateProcessorImpl.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/ProcessorImplTest.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/StateMachineManagerTest.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/retry/TestEntity.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractNegotiationDefaultServicesExtension.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/listener/ContractNegotiationEventListener.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/ContractCoreExtensionTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/listener/ContractNegotiationEventListenerTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferCoreExtension.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferProcessDefaultServicesExtension.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
  docs/developer/state-machine.md
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/statement/ColumnEntry.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/statement/SqlExecuteStatement.java
  extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/docs/schema.sql
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/SqlContractNegotiationStore.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/schema/ContractNegotiationStatements.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/schema/postgres/ContractNegotiationMapping.java
  extensions/control-plane/store/sql/transfer-process-store-sql/docs/schema.sql
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/TransferProcessStoreStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/TransferProcessMapping.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/transferprocess/PostgresTransferProcessStoreTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/entity/PendingGuard.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/entity/StatefulEntity.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/persistence/StateEntityStore.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/event/contractnegotiation/ContractNegotiationConfirmed.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/event/contractnegotiation/ContractNegotiationDeclined.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/event/contractnegotiation/ContractNegotiationFailed.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ContractNegotiationPendingGuard.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/observe/ContractNegotiationListener.java
  spi/control-plane/contract-spi/src/test/java/org/eclipse/edc/connector/contract/spi/event/ContractEventTest.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/TestFunctions.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/TransferProcessPendingGuard.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/event/TransferProcessCancelled.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/event/TransferProcessEnded.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TransferProcessStoreTestBase.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
Labels: enhancement, core feature

#3336 fix: break lease for STARTED processes
  DEPENDENCIES
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
Labels: bug

#3330 refactor: uniform in-memory and sql store implementations
  core/common/util/src/main/java/org/eclipse/edc/util/reflection/ReflectionUtil.java
  core/common/util/src/test/java/org/eclipse/edc/util/reflection/ReflectionUtilTest.java
  core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/CatalogCoreExtension.java
  core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DatasetResolverImpl.java
  core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplIntegrationTest.java
  core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/asset/AssetServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetServiceImplTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/ControlPlaneDefaultServicesExtension.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/asset/CriterionToAssetPredicateConverterImpl.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/CriterionToPredicateConverterImpl.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/DefaultCriterionToPredicateConverter.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/InMemoryStatefulEntityStore.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/ReflectionBasedQueryResolver.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndex.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/policydefinition/InMemoryPolicyDefinitionStore.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/asset/CriterionToAssetPredicateConverterImplTest.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/CriterionToPredicateConverterImplTest.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/ReflectionBasedQueryResolverTest.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndexTest.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/contractdefinition/InMemoryContractDefinitionStoreTest.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/contractnegotiation/InMemoryContractNegotiationStoreTest.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/policydefinition/InMemoryPolicyDefinitionStoreTest.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/transferprocess/InMemoryTransferProcessStoreTest.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/api/controller/DspTransferProcessApiControllerTest.java
  extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/mapper/UnexpectedExceptionMapper.java
  extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/mapper/UnexpectedExceptionMapperTest.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/JsonFieldMapping.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/SqlConditionExpression.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/SqlQueryStatement.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/TranslationMapping.java
  extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/SqlQueryStatementTest.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndex.java
  extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/SqlConditionExpressionTest.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractdefinition/PostgresContractDefinitionStoreTest.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/schema/postgres/ContractNegotiationSqlQueryStatementTest.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/policydefinition/PostgresPolicyDefinitionStoreTest.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/transferprocess/PostgresTransferProcessStoreTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetPredicateConverter.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/BaseCriterionToPredicateConverter.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/Criterion.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/CriterionToAssetPredicateConverter.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/CriterionToPredicateConverter.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/asset/Asset.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/query/BaseCriterionToPredicateConverterTest.java
  spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java
  spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/TestObject.java
  spi/common/transaction-spi/src/main/java/org/eclipse/edc/transaction/spi/NoopTransactionContext.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/offer/store/ContractDefinitionStoreTestBase.java
  spi/control-plane/policy-spi/src/testFixtures/java/org/eclipse/edc/connector/policy/spi/testfixtures/store/PolicyDefinitionStoreTestBase.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TransferProcessStoreTestBase.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiDeprecatedEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java
Labels: enhancement, refactoring
