Repository eclipse-edc/Connector, pull requests merged in 2023-03, with the labels that each got.

#2523 chore: upgrade to gradle 8, upgrade the shadow plugin
  build.gradle.kts
  docs/developer/build-your-own-connector.md
  gradle/wrapper/gradle-wrapper.properties
  launchers/data-plane-server/build.gradle.kts
  launchers/dpf-selector/build.gradle.kts
  launchers/ids-connector/build.gradle.kts
  system-tests/runtimes/azure-data-factory-transfer-consumer/build.gradle.kts
  system-tests/runtimes/azure-data-factory-transfer-provider/build.gradle.kts
  system-tests/runtimes/azure-storage-transfer-consumer/build.gradle.kts
  system-tests/runtimes/azure-storage-transfer-provider/build.gradle.kts
  system-tests/runtimes/file-transfer-consumer/build.gradle.kts
  system-tests/runtimes/file-transfer-provider/build.gradle.kts
Labels: build

#2524 feat(ContractValidation): removes the check on ContractDefinition when validating an agreement
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
Labels: enhancement, core feature

#2540 docs: add decision record about store refactoring
  docs/developer/decision-records/2023-03-02_entity_store_refactoring/README.md
Labels: documentation

#2528 feat: update policy definition update
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionEventListener.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionServiceImplTest.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/policydefinition/InMemoryPolicyDefinitionStore.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/policydefinition/InMemoryPolicyDefinitionStoreTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApi.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiController.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiExtension.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionDto.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionRequestDto.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionUpdateDto.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionUpdateWrapperDto.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/transform/PolicyDefinitionUpdateWrapperDtoToPolicyDefinitionTransformer.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiControllerTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionRequestDtoValidationTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionUpdateDtoTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionUpdateDtoValidationTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/transform/PolicyDefinitionUpdateWrapperDtoToPolicyDefinitionTransformerTest.java
  extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStore.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/policydefinition/store/SqlPolicyDefinitionStore.java
  resources/openapi/openapi.yaml
  resources/openapi/yaml/management-api/policy-definition-api.yaml
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/policydefinition/PolicyDefinitionUpdated.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/policydefinition/PolicyDefinitionService.java
  spi/control-plane/policy-spi/src/main/java/org/eclipse/edc/connector/policy/spi/observe/PolicyDefinitionListener.java
  spi/control-plane/policy-spi/src/main/java/org/eclipse/edc/connector/policy/spi/store/PolicyDefinitionStore.java
  spi/control-plane/policy-spi/src/testFixtures/java/org/eclipse/edc/connector/policy/spi/testfixtures/store/PolicyDefinitionStoreTestBase.java
Labels: core feature, api

#2547 refactor: rename and move ServiceResult
  build.gradle.kts
  spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceResult.java
  spi/common/aggregate-service-spi/src/test/java/org/eclipse/edc/service/spi/result/ServiceResultTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreFailure.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreResult.java
Labels: refactoring

#2554 refactor: add create update to cosmos api
  extensions/common/azure/azure-cosmos-core/src/main/java/org/eclipse/edc/azure/cosmos/CosmosDbApi.java
  extensions/common/azure/azure-cosmos-core/src/main/java/org/eclipse/edc/azure/cosmos/CosmosDbApiImpl.java
  extensions/common/azure/azure-cosmos-core/src/test/java/org/eclipse/edc/azure/cosmos/CosmosDbApiImplIntegrationTest.java
  extensions/control-plane/store/cosmos/asset-index-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndex.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/contractdefinition/CosmosContractDefinitionStore.java
  extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractdefinition/CosmosContractDefinitionStoreTest.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStore.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreTest.java
  extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStore.java
  extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStoreTest.java
  extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStore.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStore.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStore.java
  spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceResult.java
  spi/common/aggregate-service-spi/src/test/java/org/eclipse/edc/service/spi/result/ServiceResultTest.java
Labels: enhancement, refactoring

#2553 refactor: adapt `AssetIndex`
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/asset/AssetServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetServiceImplTest.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndex.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndexTest.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetLoaderIndexTest.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApi.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiController.java
  extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/AssetApiControllerTest.java
  extensions/control-plane/store/cosmos/asset-index-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndex.java
  extensions/control-plane/store/cosmos/asset-index-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndexIntegrationTest.java
  extensions/control-plane/store/cosmos/asset-index-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndexTest.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndex.java
  extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/PostgresAssetIndexTest.java
  resources/openapi/yaml/management-api/asset-api.yaml
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetIndex.java
  spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/asset/AssetService.java
Labels: core feature, refactoring

#2561 chore(ContractDefinitionStore): fix javadoc typo on ContratDefinitionStore
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/offer/store/ContractDefinitionStore.java
Labels: build

#2568 refactor: remove MessageContext class
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/RemoteMessageDispatcherRegistryImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/CatalogServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/CatalogServiceImplTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/IdsMultipartRemoteMessageDispatcher.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/client/MultipartDispatcherIntegrationTest.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiControllerIntegrationTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowControllerTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/message/MessageContext.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/message/RemoteMessageDispatcher.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/message/RemoteMessageDispatcherRegistry.java
Labels: refactoring

#2560 refactor(DataPlaneInstanceStore): removed upsert semantic and introduced results on CU operations
  core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorServiceImpl.java
  core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/core/DataPlaneSelectorExtension.java
  core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/InMemoryDataPlaneInstanceStore.java
  extensions/data-plane-selector/data-plane-selector-api/build.gradle.kts
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/DataplaneSelectorApiController.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtensionTest.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataplaneSelectorApiControllerIntegrationTest.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStore.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStoreExtension.java
  extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStoreIntegrationTest.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/SqlDataPlaneInstanceStore.java
  spi/data-plane-selector/data-plane-selector-spi/build.gradle.kts
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/DataPlaneSelectorService.java
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/store/DataPlaneInstanceStore.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/store/DataPlaneInstanceStoreTestBase.java
Labels: core feature, refactoring

#2571 docs: Add Contract Negotiation state machine diagram
  docs/developer/README.md
  docs/developer/architecture/README.md
  docs/developer/architecture/data-transfer/README.md
  docs/developer/architecture/usage-control/contracts.md
  docs/developer/architecture/usage-control/diagrams/contract-negotiation-states.png
  docs/developer/architecture/usage-control/diagrams/contract-negotiation-states.puml
Labels: documentation

#2574 docs(transferprocess): fix message names
  .github/workflows/scan-pull-request.yaml
  docs/developer/architecture/data-transfer/diagrams/transfer-process-states.png
  docs/developer/architecture/data-transfer/diagrams/transfer-process-states.puml
Labels: documentation

#2576 fix: repair cosmos tests and simplify GH action check
  .github/workflows/verify.yaml
  core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EdcRuntimeExtension.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStore.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreTest.java
  extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStore.java
  extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStore.java
  extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStore.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataReference.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/store/DataPlaneInstanceStoreTestBase.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferCosmosDbTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
Labels: bug

#2570 docs: add decision record about event framework refactoring
  docs/developer/decision-records/2023-03-09-event-framework-refactoring/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#2504 chore: simplify DataSourceFactory and DataSinkFactory APIs
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/edc/connector/dataplane/framework/e2e/EndToEndTest.java
  core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/sink/OutputStreamDataSinkFactory.java
  core/data-plane/data-plane-util/src/test/java/org/eclipse/edc/connector/dataplane/util/sink/OutputStreamDataSinkFactoryTest.java
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
  extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactoryTest.java
  extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactoryTest.java
  extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkFactory.java
  extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSourceFactory.java
  extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkFactoryTest.java
  extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSourceFactoryTest.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSinkFactory.java
  extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSourceFactory.java
  extensions/data-plane/data-plane-google-storage/src/test/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSinkFactoryTest.java
  extensions/data-plane/data-plane-google-storage/src/test/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSourceFactoryTest.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactory.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactoryTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSinkFactory.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSourceFactory.java
  system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/edc/test/extension/api/FileTransferDataSinkFactory.java
  system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/edc/test/extension/api/FileTransferDataSourceFactory.java
Labels: refactoring, dpf

#2562 feat: Send new protocol messages transfer process
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/CompletableFutureRetryProcess.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/EntitySendRetryManager.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/RetryProcess.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/SendRetryManager.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/SimpleRetryProcess.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcess.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/retry/EntitySendRetryManagerTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplIntegrationTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/IdsMultipartRemoteMessageDispatcher.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/IdsMultipartRemoteMessageDispatcherTest.java
  extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  extensions/control-plane/api/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferCompletionMessage.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferStartMessage.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferTerminationMessage.java
Labels: enhancement, ids, dataspace-protocol

#2591 feat(protocol): Adapt `ContractNegotiation` states to Dataspace Protocol
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/listener/ContractNegotiationEventListener.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/CancelNegotiationCommandHandler.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandler.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/ContractNegotiationCommandQueueIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/CancelNegotiationCommandHandlerTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandlerTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImplTest.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/contractnegotiation/InMemoryContractNegotiationStoreTest.java
  docs/developer/architecture/usage-control/diagrams/contract-negotiation-states.png
  docs/developer/architecture/usage-control/diagrams/contract-negotiation-states.puml
  docs/developer/performance-tuning.md
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiControllerIntegrationTest.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreTest.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/TestFunctions.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationTerminated.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/event/EventTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/observe/ContractNegotiationListener.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiationStates.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/TestFunctions.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferSimulationUtils.java
Labels: enhancement, dataspace-protocol

#2593 feat(EventFramework): refactor ES according to the DR
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/event/EventRouterImpl.java
  core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/event/EventRouterImplTest.java
  core/common/junit/src/main/java/org/eclipse/edc/junit/matchers/EventEnvelopeMatcher.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/listener/ContractNegotiationEventListener.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/asset/AssetEventListener.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractdefinition/ContractDefinitionEventListener.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionEventListener.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractdefinition/ContractDefinitionEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/listener/TransferProcessEventListener.java
  docs/developer/events.md
  extensions/common/events/events-cloud-http/src/main/java/org/eclipse/edc/event/cloud/http/CloudEventsHttpExtension.java
  extensions/common/events/events-cloud-http/src/main/java/org/eclipse/edc/event/cloud/http/CloudEventsPublisher.java
  extensions/common/events/events-cloud-http/src/test/java/org/eclipse/edc/event/cloud/http/CloudEventsHttpExtensionTest.java
  extensions/common/events/events-cloud-http/src/test/java/org/eclipse/edc/event/cloud/http/TestEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/Event.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventEnvelope.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventRouter.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventSubscriber.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/asset/AssetCreated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/asset/AssetDeleted.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/asset/AssetEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/asset/AssetUpdated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractdefinition/ContractDefinitionCreated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractdefinition/ContractDefinitionDeleted.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractdefinition/ContractDefinitionEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractdefinition/ContractDefinitionUpdated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationApproved.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationConfirmed.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationDeclined.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationFailed.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationInitiated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationOffered.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationTerminated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/policydefinition/PolicyDefinitionCreated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/policydefinition/PolicyDefinitionDeleted.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/policydefinition/PolicyDefinitionEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/policydefinition/PolicyDefinitionUpdated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessCancelled.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessCompleted.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessDeprovisioned.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessDeprovisioningRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessEnded.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessFailed.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessInitiated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessProvisioned.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessProvisioningRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessStarted.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessTerminated.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/event/EventTest.java
Labels: core feature, refactoring

#2604 refactor: separate `DataRequest` from `RemoteMessage`
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/sender/type/MultipartTransferRequestSender.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/client/MultipartDispatcherIntegrationTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/sender/type/MultipartTransferRequestSenderTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/DataRequest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferCompletionMessage.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferRequestMessage.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferStartMessage.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferTerminationMessage.java
Labels: refactoring

#2601 feat: add missing transitions to `ContractNegotiation` state machines
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/CompletableFutureRetryProcess.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessConfiguration.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessFactory.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/EntitySendRetryManager.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/RetryProcess.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/SendRetryManager.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/SimpleRetryProcess.java
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcess.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/retry/CompletableFutureRetryProcessTest.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/retry/EntitySendRetryManagerTest.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/retry/RetryProcessTest.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/retry/SimpleRetryProcessTest.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcessTest.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/retry/TestEntity.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/ContractNegotiationCommandQueueIntegrationTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferCoreExtension.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplIntegrationTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
  docs/developer/architecture/README.md
  docs/developer/architecture/usage-control/diagrams/contract-negotiation-states.png
  docs/developer/architecture/usage-control/diagrams/contract-negotiation-states.puml
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ConsumerContractNegotiationManager.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ProviderContractNegotiationManager.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractAgreementVerificationMessage.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractNegotiationEventMessage.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java
Labels: enhancement, dataspace-protocol

#2618 feat(negotiation): add correlationId to new RemoteMessages
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractAgreementVerificationMessage.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractNegotiationEventMessage.java
Labels: enhancement

#2587 refactor: persistence implementations in PolicyDefinitionStore harmon…
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionServiceImplTest.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/policydefinition/InMemoryPolicyDefinitionStore.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/policydefinition/InMemoryPolicyDefinitionStoreTest.java
  extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiControllerIntegrationTest.java
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
  extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStore.java
  extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStoreTest.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/policydefinition/store/SqlPolicyDefinitionStore.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/policydefinition/PostgresPolicyDefinitionStoreTest.java
  spi/control-plane/policy-spi/src/main/java/org/eclipse/edc/connector/policy/spi/store/PolicyDefinitionStore.java
  spi/control-plane/policy-spi/src/testFixtures/java/org/eclipse/edc/connector/policy/spi/testfixtures/store/PolicyDefinitionStoreTestBase.java
  system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/edc/test/extension/api/FileTransferExtension.java
Labels: refactoring

#2615 feat(systemTests): removes gatling
  .github/workflows/performancetests.yaml
  .github/workflows/verify.yaml
  core/common/junit/src/main/java/org/eclipse/edc/junit/annotations/PerformanceTest.java
  docs/developer/testing.md
  system-tests/azure-data-factory-tests/build.gradle.kts
  system-tests/azure-data-factory-tests/src/test/java/org/eclipse/edc/test/system/local/AzureDataFactoryTransferIntegrationTest.java
  system-tests/azure-tests/build.gradle.kts
  system-tests/azure-tests/src/test/java/org/eclipse/edc/test/system/local/BlobTransferIntegrationTest.java
  system-tests/azure-tests/src/testFixtures/java/org/eclipse/edc/test/system/local/BlobTransferConfiguration.java
  system-tests/azure-tests/src/testFixtures/java/org/eclipse/edc/test/system/local/BlobTransferLocalSimulation.java
  system-tests/azure-tests/src/testFixtures/java/org/eclipse/edc/test/system/local/BlobTransferSimulationConfiguration.java
  system-tests/azure-tests/src/testFixtures/java/org/eclipse/edc/test/system/local/BlobTransferUtils.java
  system-tests/tests/build.gradle.kts
  system-tests/tests/src/test/java/org/eclipse/edc/test/system/FileTransferSimulationConfiguration.java
  system-tests/tests/src/test/java/org/eclipse/edc/test/system/local/FileTransferEdcRuntime.java
  system-tests/tests/src/test/java/org/eclipse/edc/test/system/local/FileTransferIntegrationTest.java
  system-tests/tests/src/test/java/org/eclipse/edc/test/system/local/FileTransferLocalSimulation.java
  system-tests/tests/src/test/java/org/eclipse/edc/test/system/local/TracingIntegrationTest.java
  system-tests/tests/src/test/java/org/eclipse/edc/test/system/remote/FileTransferAsClientIntegrationTest.java
  system-tests/tests/src/test/java/org/eclipse/edc/test/system/remote/FileTransferAsClientSimulation.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/local/TransferLocalSimulation.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/local/TransferRuntimeConfiguration.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/FileTransferConfiguration.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/GatlingUtils.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferConfiguration.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferInitiationData.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferSimulationConfiguration.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferSimulationUtils.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferTestClient.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferTestRunner.java
Labels: refactoring

#2639 feat(TransferProcess): introduces TransferRequest type
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandler.java
  data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiController.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiExtension.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferRequestDtoToTransferRequestTransformer.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiControllerTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferRequestDtoToTransferRequestTransformerTest.java
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/transferprocess/TransferProcessService.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/TransferProcessManager.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferRequest.java
Labels: refactoring

#2586 refactor: persistence implementations in ContractNegotiationStore har…
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/SingleContractNegotiationCommandHandler.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/ContractNegotiationCommandQueueIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/CancelNegotiationCommandHandlerTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandlerTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImplTest.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/contractnegotiation/InMemoryContractNegotiationStore.java
  core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/contractnegotiation/InMemoryContractNegotiationStoreTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStore.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreIntegrationTest.java
  extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreTest.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/SqlContractNegotiationStore.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/store/ContractNegotiationStore.java
  spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java
Labels: refactoring

#2645 fix: cleanup version to fix release
  build.gradle.kts
  docs/developer/releases.md
  gradle.properties
  settings.gradle.kts
Labels: bug

#2649 fix: use gradle 'group' property instead of 'groupId'
  build.gradle.kts
  gradle.properties
Labels: build

#2630 feat: Adds support for participant identities and checks
  .github/workflows/verify.yaml
  build.gradle.kts
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/agent/ParticipantAgentServiceImpl.java
  core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/agent/ParticipantAgentServiceImplTest.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
  data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/client/MultipartDispatcherIntegrationTest.java
  extensions/common/iam/iam-mock/src/main/java/org/eclipse/edc/iam/mock/IamMockExtension.java
  extensions/common/iam/iam-mock/src/main/java/org/eclipse/edc/iam/mock/MockIdentityService.java
  extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiControllerIntegrationTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiExtension.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/NegotiationInitiateRequestDto.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformer.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/NegotiationInitiateRequestDtoValidationTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformerTest.java
  resources/openapi/yaml/management-api/contract-negotiation-api.yaml
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/agent/ParticipantAgent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/agent/ParticipantAgentService.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ConsumerContractNegotiationManager.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ProviderContractNegotiationManager.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ContractValidationService.java
  system-tests/azure-tests/src/test/java/org/eclipse/edc/test/system/local/BlobTransferIntegrationTest.java
  system-tests/azure-tests/src/testFixtures/java/org/eclipse/edc/test/system/local/BlobTransferConfiguration.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
  system-tests/minikube/values-consumer.yaml
  system-tests/minikube/values-provider.yaml
  system-tests/tests/build.gradle.kts
  system-tests/tests/src/test/java/org/eclipse/edc/test/system/local/FileTransferEdcRuntime.java
  system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/FileTransferConfiguration.java
Labels: enhancement, core feature

#2653 feat: add json-ld module
  extensions/common/json-ld/build.gradle.kts
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdKeywords.java
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/util/JsonLdUtil.java
  extensions/common/json-ld/src/main/resources/META-INF/resources/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/util/JsonLdUtilTest.java
  settings.gradle.kts
Labels: enhancement, dataspace-protocol

#2658 chore: get rid of DependencyRulesPlugin
  .github/workflows/verify.yaml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/eclipse/edc/gradle/DependencyRulesPlugin.java
  buildSrc/src/main/java/org/eclipse/edc/gradle/DependencyRulesPluginExtension.java
  buildSrc/src/main/java/org/eclipse/edc/gradle/DependencyRulesTask.java
Labels: refactoring

#2660 fix: javadoc compilation
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdKeywords.java
Labels: bug

#2655 fix: update expected slf4j-api version of MonitorProvider
  core/common/boot/src/main/java/org/eclipse/edc/boot/monitor/MonitorProvider.java
Labels: bug
