Repository eclipse-edc/Connector, pull requests merged in 2023-02, with the labels that each got.

#2421 docs(adoptions): add references to IDS components extensions and connector gui
  known_friends.md
Labels: documentation

#2432 docs: add DR about new release process
  docs/developer/decision-records/2023-01-26-release-process/README.md
  docs/developer/decision-records/README.md
Labels: refactoring

#2459 build: fix dependabot edc-versions ignore entry
  .github/dependabot.yml
Labels: build

#2455 feat: AWS Secrets Manager Vault implementation
  extensions/common/vault/vault-aws/README.md
  extensions/common/vault/vault-aws/build.gradle.kts
  extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVault.java
  extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultDefaultSanitationStrategy.java
  extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtension.java
  extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultSanitationStrategy.java
  extensions/common/vault/vault-aws/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerDefaultKeySanitationStrategyTest.java
  extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtensionTest.java
  extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultTest.java
  settings.gradle.kts
Labels: enhancement

#2469 feat: `data-plane-http-oauth2` extension
  core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/DependencyInjectionExtension.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/README.md
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ConsumerResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProviderResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtension.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ResourceDefinition.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/AbstractOauth2DataAddressValidationTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ConsumerResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2CredentialsRequestFactoryTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2DataAddressValidatorTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProviderResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtensionTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ResourceDefinitionTest.java
  extensions/data-plane/data-plane-http-oauth2-core/README.md
  extensions/data-plane/data-plane-http-oauth2-core/build.gradle.kts
  extensions/data-plane/data-plane-http-oauth2-core/src/main/java/org/eclipse/edc/connector/dataplane/http/oauth2/DataPlaneHttpOauth2Extension.java
  extensions/data-plane/data-plane-http-oauth2-core/src/main/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2CredentialsRequestFactory.java
  extensions/data-plane/data-plane-http-oauth2-core/src/main/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2HttpRequestParamsDecorator.java
  extensions/data-plane/data-plane-http-oauth2-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/data-plane/data-plane-http-oauth2-core/src/test/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2CredentialsRequestFactoryTest.java
  extensions/data-plane/data-plane-http-oauth2-core/src/test/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2HttpRequestParamsDecoratorTest.java
  extensions/data-plane/data-plane-http-oauth2/README.md
  extensions/data-plane/data-plane-http-oauth2/build.gradle.kts
  extensions/data-plane/data-plane-http/build.gradle.kts
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpExtension.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestFactory.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImpl.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/decorators/BaseCommonHttpParamsDecorator.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/decorators/BaseSinkHttpParamsDecorator.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/decorators/BaseSourceHttpParamsDecorator.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSink.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactory.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSource.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpExtensionTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestFactoryTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImplSinkTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImplSourceTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImplTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/DataSourceToDataSinkTests.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactoryTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceTest.java
  settings.gradle.kts
  spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2DataAddressSchema.java
  spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2DataAddressValidator.java
  spi/common/oauth2-spi/src/test/java/org/eclipse/edc/iam/oauth2/spi/Oauth2DataAddressValidatorTest.java
  spi/data-plane/data-plane-http-spi/build.gradle.kts
  spi/data-plane/data-plane-http-spi/src/main/java/org/eclipse/edc/connector/dataplane/http/spi/HttpParamsDecorator.java
  spi/data-plane/data-plane-http-spi/src/main/java/org/eclipse/edc/connector/dataplane/http/spi/HttpRequestParams.java
  spi/data-plane/data-plane-http-spi/src/main/java/org/eclipse/edc/connector/dataplane/http/spi/HttpRequestParamsProvider.java
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/e2e-transfer-test/data-plane/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
Labels: enhancement, dpf

#2383 feat(dataPlaneS3): adds support for vault on data source address
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/DataPlaneS3Extension.java
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
  extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java
  extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactoryTest.java
Labels: enhancement, dpf

#2482 feat: decision record about nightly builds
  docs/developer/decision-records/2023-02-10-nightly-builds/README.md
Labels: documentation, build

#2485 chore: remove unused dependency
  NOTICE.md
  extensions/common/iam/iam-mock/build.gradle.kts
Labels: build

#2486 refactor: move api modules from control-plane to extensions module
  extensions/control-plane/api/control-plane-api-client/build.gradle.kts
  extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/api/client/ControlPlaneApiClientExtension.java
  extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClient.java
  extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/api/client/transferprocess/model/TransferProcessFailRequest.java
  extensions/control-plane/api/control-plane-api-client/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  extensions/control-plane/api/control-plane-api/build.gradle.kts
  extensions/control-plane/api/control-plane-api/src/main/java/org/eclipse/edc/connector/api/ControlPlaneApiExtension.java
  extensions/control-plane/api/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/TransferProcessControlApi.java
  extensions/control-plane/api/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/TransferProcessControlApiController.java
  extensions/control-plane/api/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/model/TransferProcessFailStateDto.java
  extensions/control-plane/api/control-plane-api/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/api/control-plane-api/src/test/java/org/eclipse/edc/connector/api/ControlPlaneApiExtensionTest.java
  extensions/control-plane/api/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
Labels: refactoring

#2495 fix: adding missing wrapping transaction blocks in `SqlPolicyDefinitionStore`
  extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/policydefinition/store/SqlPolicyDefinitionStore.java
Labels: bug

#2497 fix: disable flaky ADF test
  .github/workflows/verify.yaml
Labels: bug

#2494 fix: catalog pagination
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImplIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImplTest.java
Labels: bug

#2496 fix: permit `Config` keys with snakeCase format
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/DefaultServiceExtensionContext.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/configuration/ConfigFactory.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/configuration/ConfigImpl.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/system/configuration/ConfigFactoryTest.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/system/configuration/ConfigImplTest.java
Labels: bug

#2513 docs: add decision record about PUT endpoints
  docs/developer/decision-records/2023-02-22-update-entities/README.md
  docs/developer/decision-records/README.md
Labels: documentation, api

#2515 docs: decision record for ContractDefinition validation
  docs/developer/decision-records/2023-02-22-contract-definition-validation/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#2448 docs: create first draft of dataspace protocol architecture documents
  docs/developer/architecture/ids-dataspace-protocol/README.md
  docs/developer/architecture/ids-dataspace-protocol/contract-negotiation-architecture.md
  docs/developer/architecture/ids-dataspace-protocol/ids-endpoints-services-architecture.md
  docs/developer/architecture/ids-dataspace-protocol/json-ld-processing-architecture.md
  docs/developer/architecture/ids-dataspace-protocol/management-api.md
  docs/developer/architecture/ids-dataspace-protocol/transfer-process-architecture.md
Labels: documentation, no-changelog, ids-next

#2525 docs: add decision record about transfer process state transitions change
  docs/developer/decision-records/2023-02-27-dataspace-protocol-transferprocess-state-transitions/README.md
  docs/developer/decision-records/README.md
Labels: documentation
