Repository eclipse-edc/Connector, pull requests merged in 2023-08, with the labels that each got.

#3338 docs: Fix typo in Contract In Force Policy documentation
  docs/developer/contract-duration/contract-validity-check.md
Labels: documentation

#3345 refactor: remove pre-0.1.0 deprecated stuff
  DEPENDENCIES
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/edc/connector/dataplane/framework/e2e/EndToEndTest.java
  core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/sink/OutputStreamDataSinkFactory.java
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtension.java
  extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtensionTest.java
  extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/v2/AssetApiControllerTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/README.md
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/build.gradle.kts
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/docs/diagram.png
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ConsumerResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2CredentialsRequestFactory.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProviderResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtension.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionedResource.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2Provisioner.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ResourceDefinition.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2SecretToken.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/AbstractOauth2DataAddressValidationTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ConsumerResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2CredentialsRequestFactoryTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProviderResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtensionTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionerTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ResourceDefinitionTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2SecretTokenTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2/README.md
  extensions/control-plane/provision/provision-oauth2/provision-oauth2/build.gradle.kts
  extensions/data-plane/data-plane-http-oauth2-core/src/main/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2CredentialsRequestFactory.java
  extensions/data-plane/data-plane-http-oauth2-core/src/test/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2CredentialsRequestFactoryTest.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactory.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java
  extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSinkFactory.java
  extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSourceFactory.java
  extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSinkFactoryTest.java
  extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSourceFactoryTest.java
  settings.gradle.kts
  spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2DataAddressSchema.java
  spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2DataAddressValidator.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSinkFactory.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSourceFactory.java
Labels: refactoring

#3346 docs: adds decision record about default datasource
  docs/developer/decision-records/2023-08-01-default-datasource/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#3348 refactor: avoid manual construction of sql execute statements
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/dialect/BaseSqlDialect.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/statement/ColumnEntry.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/statement/SqlExecuteStatement.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/statement/SqlStatements.java
  extensions/common/sql/sql-lease/src/main/java/org/eclipse/edc/sql/lease/LeaseStatements.java
  extensions/common/sql/sql-lease/src/test/java/org/eclipse/edc/sql/lease/PostgresLeaseContextTest.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/schema/AssetStatements.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractdefinition/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractdefinition/schema/ContractDefinitionStatements.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/schema/postgres/PostgresDialectStatements.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/policydefinition/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/policydefinition/store/schema/SqlPolicyStoreStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/TransferProcessStoreStatements.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/schema/BaseSqlDataPlaneInstanceStatements.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/schema/DataPlaneInstanceStatements.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlDataPlaneStatements.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/DataPlaneStatements.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/sql/statement/SqlExecuteStatementTest.java
Labels: refactoring

#3351 feat: fix dataset case according to DSP specs
  DEPENDENCIES
  core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToCatalogTransformerTest.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiControllerTest.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractRequestMessageTransformer.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractRequestMessageTransformer.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractRequestMessageTransformerTest.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractRequestMessageTransformerTest.java
  data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/type/DspNegotiationPropertyAndTypeNames.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessage.java
  spi/control-plane/contract-spi/src/test/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessageTest.java
Labels: enhancement, dataspace-protocol

#3356 feat: implement newInstance everywhere
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/command/CommandResult.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/response/StatusResult.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreResult.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/health/HealthCheckResult.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/StreamResult.java
Labels: enhancement

#3358 docs: generic properties DR
  docs/developer/decision-records/2023-08-07-generic-properties/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#3359 feat: adopt JWS 2020 crypto suite
  DEPENDENCIES
  extensions/common/crypto/crypto-core/build.gradle.kts
  extensions/common/crypto/crypto-core/src/main/java/org/eclipse/edc/security/signature/jws2020/KeyFactory.java
  extensions/common/crypto/crypto-core/src/test/java/org/eclipse/edc/security/signature/jws2020/KeyFactoryTest.java
  extensions/common/crypto/crypto-core/src/test/resources/rsakey.json
  extensions/common/crypto/jws2020/README.md
  extensions/common/crypto/jws2020/build.gradle.kts
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/ByteArrayAdapter.java
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/IssuerCompatibility.java
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/JsonAdapter.java
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/JwkAdapter.java
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/JwkMethod.java
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/Jws2020CryptoSuite.java
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/Jws2020Schema.java
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/Jws2020SignatureProvider.java
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/JwsSignature2020Suite.java
  extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/JwsSignatureProofOptions.java
  extensions/common/crypto/jws2020/src/test/java/org/eclipse/edc/security/signature/jws2020/IssuerTests.java
  extensions/common/crypto/jws2020/src/test/java/org/eclipse/edc/security/signature/jws2020/JsonAdapterTest.java
  extensions/common/crypto/jws2020/src/test/java/org/eclipse/edc/security/signature/jws2020/TestFunctions.java
  extensions/common/crypto/jws2020/src/test/java/org/eclipse/edc/security/signature/jws2020/TestResourcesLoader.java
  extensions/common/crypto/jws2020/src/test/java/org/eclipse/edc/security/signature/jws2020/VerifierTests.java
  extensions/common/crypto/jws2020/src/test/resources/jws2020/issuing/0001_vc.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/issuing/0003_vc_embedded.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/issuing/0004_vc_did_key.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/issuing/0005_vp_compacted_signed.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/issuing/linkedCredentialData.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/issuing/private-key.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/0001_vc.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/0002_vc_forged.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/0003_vc_embedded.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/0004_vc_two_valid_proofs.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/0005_vc_one_forged_proof.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/0006_vc_did_key.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/0007_vp_compacted.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/0007_vp_compacted_forged.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/linkedCredentialData.json
  extensions/common/crypto/jws2020/src/test/resources/jws2020/verifying/verification-method.json
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement, core feature

#3360 feat: add get negotiation by agreement id endpoint
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractagreement/ContractAgreementServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractagreement/ContractAgreementServiceImplTest.java
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchema.java
  extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchemaTest.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java
  extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApiTest.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApi.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiController.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiControllerTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiTest.java
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractagreement/ContractAgreementService.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractAgreementApiEndToEndTest.java
Labels: enhancement, api

#3365 feat: validate DSP catalog messages
  DEPENDENCIES
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/TypeIs.java
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/model/CriterionValidator.java
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/model/QuerySpecValidator.java
  core/common/validator-core/src/test/java/org/eclipse/edc/validator/jsonobject/validators/model/CriterionValidatorTest.java
  core/common/validator-core/src/test/java/org/eclipse/edc/validator/jsonobject/validators/model/QuerySpecValidatorTest.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-api/build.gradle.kts
  data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/api/DspCatalogApiExtension.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/api/controller/DspCatalogApiController.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/api/validation/CatalogRequestMessageValidator.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/api/DspCatalogApiExtensionTest.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/api/controller/DspCatalogApiControllerTest.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/api/validation/CatalogRequestMessageValidatorTest.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/DspCatalogTransformExtension.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/to/JsonObjectToCatalogRequestMessageTransformer.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/to/JsonObjectToCatalogRequestMessageTransformerTest.java
  extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/ApiCoreExtension.java
  extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/model/ApiCoreSchemaTest.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/validation/CatalogRequestValidator.java
  extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/validation/ContractDefinitionValidator.java
  spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/TypeUtil.java
Labels: enhancement, dataspace-protocol

#3368 refactor: switch properties to Map<String, Object>
  DEPENDENCIES
  core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromDataAddressTransformer.java
  core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToDataAddressTransformerTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/edr/DataAddressToEndpointDataReferenceTransformer.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/edr/DataAddressToEndpointDataReferenceTransformerTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
  core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/validation/EmptyValueValidationRule.java
  core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/validation/ValidationRule.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/to/JsonObjectToTransferRequestMessageTransformerTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApi.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/JsonObjectToTransferRequestTransformer.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiTest.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiver.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiverTest.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/dynamic/TestFunctions.java
  extensions/data-plane/data-plane-http-oauth2-core/src/main/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2CredentialsRequestFactory.java
  extensions/data-plane/data-plane-http-oauth2-core/src/test/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2CredentialsRequestFactoryTest.java
  extensions/data-plane/data-plane-http/src/testFixtures/java/org/eclipse/edc/connector/dataplane/http/testfixtures/HttpTestFixtures.java
  extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/config/KafkaPropertiesFactory.java
  extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSinkFactory.java
  extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSourceFactory.java
  extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/pipeline/validation/KafkaSinkDataAddressValidation.java
  extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/pipeline/validation/KafkaSourceDataAddressValidation.java
  extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSinkFactoryTest.java
  extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSourceFactoryTest.java
  extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaPropertiesFactoryTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/DataAddress.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/HttpDataAddress.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataReference.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/domain/DataAddressTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferRequest.java
Labels: refactoring

#3386 build: update release.yml file
  .github/release.yaml
Labels: documentation, build

#3387 fix: send correlation id as process id in the transfer messages
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/e2e-transfer-test/data-plane/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
Labels: bug
