Repository eclipse-edc/Connector, pull requests merged in 2023-01, with the labels that each got.

#2379 build(deps): bump BouncyCastle to 1.72 Jdk18on
  core/common/connector-core/build.gradle.kts
  extensions/common/vault/vault-filesystem/build.gradle.kts
  extensions/control-plane/transfer/transfer-data-plane/build.gradle.kts
  extensions/data-plane/data-plane-azure-data-factory/build.gradle.kts
Labels: stale, dependencies

#2373 feat: add synthetic service provider
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/DependencyGraph.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/ExtensionLoader.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/DependencyGraphTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/ExtensionLoaderTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/TestFunctions.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/BaseRuntimeFixture.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java
Labels: bug, core feature

#2400 chore: update sample links
  docs/developer/architecture/README.md
  docs/developer/command-queue.md
  docs/developer/metrics.md
Labels: refactoring, no-changelog

#2378 refactor: improve `Event` hierarchy
  .github/workflows/verify.yaml
  core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/event/EventRouterImplTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetEventDispatchTest.java
  extensions/common/events/events-cloud-http/src/test/java/org/eclipse/edc/event/cloud/http/TestEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/asset/AssetCreated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/asset/AssetDeleted.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/asset/AssetEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/asset/AssetEventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractdefinition/ContractDefinitionCreated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractdefinition/ContractDefinitionDeleted.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractdefinition/ContractDefinitionEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractdefinition/ContractDefinitionEventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationApproved.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationConfirmed.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationDeclined.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationEventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationFailed.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationInitiated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationOffered.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/policydefinition/PolicyDefinitionCreated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/policydefinition/PolicyDefinitionDeleted.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/policydefinition/PolicyDefinitionEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/policydefinition/PolicyDefinitionEventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessCancelled.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessCompleted.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessDeprovisioned.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessDeprovisioningRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessEnded.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessEvent.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessEventPayload.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessFailed.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessInitiated.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessProvisioned.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessProvisioningRequested.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/transferprocess/TransferProcessRequested.java
Labels: refactoring

#2398 fix: publish to swaggerhub only on upstream main branch pushes
  .github/workflows/apidoc.yaml
Labels: bug

#2381 fix: Fix `baseUrl` handling in `HttpRequestParams`
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpExtension.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/AbstractTransferRequestBody.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/ChunkedTransferRequestBody.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSource.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpRequestParams.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSinkRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSourceRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/NonChunkedTransferRequestBody.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/DataSourceToDataSinkTests.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpRequestParamsSupplierTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpRequestParamsTests.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSourceRequestParamsSupplierTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/NonChunkedTransferRequestBodyTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/HttpDataAddress.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/domain/HttpDataAddressTest.java
Labels: bug

#2399 fix: ContractDefinition.Validity breaks catalog requests if number is too big
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImplIntegrationTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImplTest.java
Labels: bug

#2407 feat: add scope parameter to oauth2 provisioner
  extensions/common/iam/oauth2/oauth2-client/src/main/java/org/eclipse/edc/iam/oauth2/client/Oauth2ClientImpl.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/README.md
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2CredentialsRequestFactory.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2DataAddressSchema.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtension.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2Provisioner.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ResourceDefinition.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2CredentialsRequestFactoryTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionerTest.java
Labels: enhancement

#2410 feat: fetch provision-oauth2 client secret from the vault
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/README.md
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2CredentialsRequestFactory.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2DataAddressSchema.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2DataAddressValidator.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtension.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ResourceDefinition.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/AbstractOauth2DataAddressValidationTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ConsumerResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2CredentialsRequestFactoryTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProviderResourceDefinitionGeneratorTest.java
  extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtensionTest.java
  system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/edc/test/e2e/Oauth2TokenController.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
  system-tests/e2e-transfer-test/runner/src/test/resources/consumer-vault.properties
  system-tests/e2e-transfer-test/runner/src/test/resources/provider-vault.properties
Labels: enhancement

#2431 build: stops dependabot opening update PR on `edc-versions`
  .github/dependabot.yml
Labels: build

#2428 feat: permit `data-plane-http` request build to be extended
  .github/workflows/release-edc.yml
  extensions/data-plane/data-plane-http/README.md
  extensions/data-plane/data-plane-http/build.gradle.kts
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpExtension.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/HttpParamsDecorator.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParams.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProvider.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImpl.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/decorators/BaseCommonHttpParamsDecorator.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/decorators/BaseSinkHttpParamsDecorator.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/decorators/BaseSourceHttpParamsDecorator.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSink.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactory.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSource.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSinkRequestParamsSupplier.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpExtensionTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImplSinkTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImplSourceTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImplTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/DataSourceToDataSinkTests.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactoryTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpRequestParamsSupplierTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSinkRequestParamsSupplierTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpSourceRequestParamsSupplierTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowRequest.java
Labels: enhancement
