Repository eclipse-edc/Connector, pull requests merged in 2023-09, with the labels that each got.

#3390 feat: handle ContractRequestMessage on an already existing negotiation
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/result/ResultTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java
Labels: enhancement, dataspace-protocol

#3405 refactor: add onNotProcessed handler on Processor
  core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/ProcessorImpl.java
  core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/ProcessorImplTest.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
Labels: refactoring

#3402 feat: adds counter party validation on all DSP messages
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java
Labels: enhancement

#3419 refactor: removes TransferProcessFailed event
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/listener/TransferProcessEventListener.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/event/TransferProcessFailed.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/observe/TransferProcessListener.java
  spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/transfer/spi/event/TransferProcessEventTest.java
Labels: refactoring

#3426 docs: add example for failing responses on api specs
  DEPENDENCIES
  extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/model/ApiCoreSchema.java
  extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/model/ApiCoreSchemaTest.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApi.java
  extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java
  extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApi.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApi.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApi.java
Labels: documentation, api

#3425 docs: dataplanes api docs fix
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/MandatoryArray.java
  core/common/validator-core/src/test/java/org/eclipse/edc/validator/jsonobject/JsonObjectValidatorTest.java
  extensions/data-plane-selector/data-plane-selector-api/build.gradle.kts
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtension.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiController.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/DataPlaneInstanceSchema.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/SelectionRequestSchema.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/validation/DataPlaneInstanceValidator.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/TestFunctions.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataPlaneApiSelectorTest.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataPlaneSelectorApiControllerTest.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/v2/validation/DataPlaneInstanceValidatorTest.java
  extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/client/RemoteDataPlaneSelectorClientTest.java
Labels: documentation

#3428 feat: add priority on `DataFlowController` registration
  DEPENDENCIES
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImpl.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImplTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowController.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowControllerTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowControllerTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowController.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowManager.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java
Labels: enhancement

#3437 build: set default version after api spec publish
  .github/workflows/apidoc.yaml
Labels: documentation, build

#3438 refactor: avoid illegal status in state machines
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
Labels: enhancement

#3441 docs: PolicyMonitor DR
  docs/developer/decision-records/2023-09-07-policy-monitor/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#3440 refactor: get rid of `NoopTransferProcessClient`
  core/data-plane/data-plane-framework/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultServicesExtension.java
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtensionTest.java
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/edc/connector/dataplane/framework/e2e/EndToEndTest.java
  core/data-plane/data-plane-framework/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  extensions/common/http/jetty-core/build.gradle.kts
  extensions/common/http/jetty-core/src/test/java/org/eclipse/edc/web/jetty/JettyServiceTest.java
  extensions/control-plane/api/control-plane-api/src/test/java/org/eclipse/edc/connector/api/transferprocess/TransferProcessControlApiControllerTest.java
  extensions/data-plane/data-plane-http/build.gradle.kts
  extensions/data-plane/data-plane-integration-tests/build.gradle.kts
  gradle/libs.versions.toml
  spi/control-plane/control-plane-api-client-spi/src/main/java/org/eclipse/edc/connector/api/client/spi/transferprocess/NoopTransferProcessClient.java
Labels: refactoring, api

#3443 build: speed up e2e transfer tests
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/EdcHttpClientImpl.java
  core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EdcClassRuntimesExtension.java
  extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/statement/SqlExecuteStatementTest.java
  extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClient.java
  extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  spi/common/http-spi/src/main/java/org/eclipse/edc/spi/http/EdcHttpClient.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferInMemoryTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferPostgresqlTest.java
Labels: build

#3449 feat: add IdResponse on addEntry API
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtension.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApi.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiController.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataPlaneSelectorApiControllerTest.java
  extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/client/RemoteDataPlaneSelectorClientTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java
Labels: enhancement, api

#3450 feat(build): publish directly from GHA using a reusable WF
  .github/workflows/trigger_snapshot.yml
Labels: enhancement, build, github_actions

#3454 chore(docs): remove specific docker base image from readme
  extensions/common/api/api-observability/README.md
Labels: documentation

#3463 fix: remove SLF4j-Monitor bridge
  DEPENDENCIES
  core/common/boot/build.gradle.kts
  core/common/boot/src/main/java/org/eclipse/edc/boot/monitor/MonitorProvider.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java
  core/common/boot/src/main/resources/META-INF/services/org.slf4j.spi.SLF4JServiceProvider
  gradle/libs.versions.toml
Labels: refactoring, dependencies

#3470 fix: update DataAddress in SqlAssetIndex
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndex.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetIndex.java
  spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java
Labels: bug

#3467 fix: validate every item of QuerySpec filterExpression
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/JsonObjectValidator.java
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/JsonWalker.java
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/MandatoryValue.java
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/model/CriterionValidator.java
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/model/QuerySpecValidator.java
  core/common/validator-core/src/test/java/org/eclipse/edc/validator/jsonobject/validators/model/CriterionValidatorTest.java
  core/common/validator-core/src/test/java/org/eclipse/edc/validator/jsonobject/validators/model/QuerySpecValidatorTest.java
Labels: bug, api

#3456 feat: implement policy-monitor
  DEPENDENCIES
  core/common/connector-core/build.gradle.kts
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/entity/AbstractStateEntityManager.java
  core/control-plane/contract-core/build.gradle.kts
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/transfer-core/build.gradle.kts
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferCoreExtension.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/listener/TransferProcessEventListener.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplIntegrationTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtension.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java
  core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/sink/ParallelSink.java
  core/policy-monitor/policy-monitor-core/build.gradle.kts
  core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/PolicyMonitorExtension.java
  core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/manager/PolicyMonitorManagerImpl.java
  core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/store/InMemoryPolicyMonitorStore.java
  core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/subscriber/StartMonitoring.java
  core/policy-monitor/policy-monitor-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  core/policy-monitor/policy-monitor-core/src/test/java/org/eclipse/edc/connector/policy/monitor/manager/PolicyMonitorManagerImplTest.java
  core/policy-monitor/policy-monitor-core/src/test/java/org/eclipse/edc/connector/policy/monitor/subscriber/StartMonitoringTest.java
  docs/developer/README.md
  docs/developer/policy-monitor.md
  extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/PolicyFixtures.java
  extensions/control-plane/callback/callback-http-dispatcher/src/test/java/org/eclipse/edc/connector/callback/dispatcher/http/GenericHttpRemoteDispatcherWrapperTest.java
  settings.gradle.kts
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/entity/StateEntityManager.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ConsumerContractNegotiationManager.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ProviderContractNegotiationManager.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/TransferProcessManager.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/event/TransferProcessStarted.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/manager/DataPlaneManager.java
  spi/policy-monitor/policy-monitor-spi/build.gradle.kts
  spi/policy-monitor/policy-monitor-spi/src/main/java/org/eclipse/edc/connector/policy/monitor/spi/PolicyMonitorEntry.java
  spi/policy-monitor/policy-monitor-spi/src/main/java/org/eclipse/edc/connector/policy/monitor/spi/PolicyMonitorEntryStates.java
  spi/policy-monitor/policy-monitor-spi/src/main/java/org/eclipse/edc/connector/policy/monitor/spi/PolicyMonitorManager.java
  spi/policy-monitor/policy-monitor-spi/src/main/java/org/eclipse/edc/connector/policy/monitor/spi/PolicyMonitorStore.java
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndKafkaTransferTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java
Labels: enhancement, core feature

#3480 feat: removes StatusChecker
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferCoreExtension.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferProcessDefaultServicesExtension.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/StatusCheckerRegistryImpl.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplIntegrationTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/status/StatusCheckerRegistry.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/StatusChecker.java
Labels: enhancement, refactoring

#3479 feat(Pool): autovacuum fix + refactor
  extensions/common/sql/sql-pool/sql-pool-apache-commons/README.md
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPool.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolConfig.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolConfigKeys.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtension.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/test/java/org/eclipse/edc/sql/pool/commons/AbstractCommonsConnectionPoolServiceExtensionTest.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/test/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolConfigTest.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/test/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtensionTest.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/test/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolTest.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/test/java/org/eclipse/edc/sql/pool/commons/DriverManagerConnectionFactoryTest.java
Labels: bug, refactoring
