Repository eclipse-edc/Connector, pull requests merged in 2024-03, with the labels that each got.

#3940 feat: add trasformers from/to for DataFlowStartMessage
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImplTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowController.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowStartMessageTransformer.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowStartMessageTransformer.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowStartMessageTransformerTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowStartMessageTransformerTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowStartMessage.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/FlowType.java
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowStartMessageTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataplaneEndToEndTest.java
Labels: enhancement, dpf

#3944 build: add openapi ui publish workflow
  .github/workflows/publish-openapi-ui.yml
Labels: build

#3945 build(docs): publish openapi ui on release
  .github/workflows/release-edc.yml
Labels: build

#3946 feat: add trasformers from/to for DataFlowResponseMessage
  extensions/data-plane/data-plane-signaling/data-plane-signaling-api-configuration/src/main/java/org/eclipse/edc/connector/api/signaling/configuration/SignalingApiConfigurationExtension.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowResponseMessageTransformer.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowResponseMessageTransformer.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowResponseMessageTransformerTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowResponseMessageTransformerTest.java
Labels: enhancement, dpf

#3947 feat: data plane client for signaling protocol
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/build.gradle.kts
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClient.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtension.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTransformExtension.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtensionTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTransformExtensionTest.java
  settings.gradle.kts
Labels: enhancement, dpf

#3952 feat: introduce allowedTransferTypes in DataPlaneInstance
  DEPENDENCIES
  core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorService.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiController.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/model/SelectionRequest.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/DataPlaneInstanceSchema.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/SelectionRequestSchema.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectFromDataPlaneInstanceTransformer.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToDataPlaneInstanceTransformer.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToSelectionRequestTransformer.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataPlaneApiSelectorTest.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectFromDataPlaneInstanceTransformerTest.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToDataPlaneInstanceTransformerTest.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToSelectionRequestTransformerTest.java
  extensions/data-plane-selector/data-plane-selector-client/src/main/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorService.java
  extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorServiceTest.java
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/DataPlaneSelectorService.java
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstance.java
  spi/data-plane-selector/data-plane-selector-spi/src/test/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstanceTest.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/TestFunctions.java
  spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/store/DataPlaneInstanceStoreTestBase.java
Labels: enhancement, dpf

#3957 feat: public Participant#getId
  extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java
Labels: enhancement

#3859 chore: move observability api docs to default api docs
  .github/workflows/apidoc.yaml
  extensions/common/api/api-observability/build.gradle.kts
Labels: documentation, refactoring, api

#3969 feat: store additional properties with the AccessTokenData
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImpl.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImplTest.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImplTest.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAccessTokenService.java
Labels: enhancement, dpf

#3965 refactor: add context handling capabilities to TypeTransformerRegistry
  core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/TypeTransformerRegistryImpl.java
  core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/IntegerStringTypeTransformer.java
  core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/TypeTransformerRegistryImplTest.java
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtension.java
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/transform/ManagementApiTypeTransformerRegistry.java
  extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/transform/ManagementApiTypeTransformerRegistryImpl.java
  extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtensionTest.java
  extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/transform/ManagementApiTypeTransformerRegistryImplTest.java
  extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiExtension.java
  extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiExtension.java
  extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiExtension.java
  extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiExtension.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiExtension.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiExtensionTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiExtension.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiExtensionTest.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtension.java
  extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtensionTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-api-configuration/src/main/java/org/eclipse/edc/connector/api/signaling/configuration/SignalingApiConfigurationExtension.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-api-configuration/src/test/java/org/eclipse/edc/connector/api/signaling/configuration/SignalingApiConfigurationExtensionTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlaneSignalingApiExtension.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtension.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTransformExtension.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTransformExtensionTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/SignalingApiTransformerRegistry.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/SignalingApiTransformerRegistryImpl.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/SignalingApiTransformerRegistryImplTest.java
  spi/common/transform-spi/src/main/java/org/eclipse/edc/transform/spi/TypeTransformerRegistry.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSignalingApiEndToEndTest.java
Labels: refactoring

#3981 feat: add update method to AccessTokenDataStore
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/store/InMemoryAccessTokenDataStore.java
  extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlAccessTokenDataStore.java
  extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/AccessTokenDataStatements.java
  extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlAccessTokenStatements.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/store/AccessTokenDataStore.java
  spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/store/AccessTokenDataTestBase.java
Labels: enhancement, dpf

#3978 feat: EDR (data address) and metadata storage/cache
  core/common/edr-store-core/build.gradle.kts
  core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/EndpointDataReferenceStoreDefaultServicesExtension.java
  core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/EndpointDataReferenceStoreExtension.java
  core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/defaults/InMemoryEndpointDataReferenceEntryIndex.java
  core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/defaults/VaultEndpointDataReferenceCache.java
  core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/store/EndpointDataReferenceStoreImpl.java
  core/common/edr-store-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/EndpointDataReferenceStoreDefaultServicesExtensionTest.java
  core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/EndpointDataReferenceStoreExtensionTest.java
  core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/defaults/InMemoryEndpointDataReferenceEntryStoreTest.java
  core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/defaults/VaultEndpointDataReferenceCacheTest.java
  core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/store/EndpointDataReferenceStoreImplTest.java
  settings.gradle.kts
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreFailure.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreResult.java
  spi/common/edr-store-spi/build.gradle.kts
  spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/store/EndpointDataReferenceCache.java
  spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/store/EndpointDataReferenceEntryIndex.java
  spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/store/EndpointDataReferenceStore.java
  spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/types/EndpointDataReferenceEntry.java
  spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/TestFunctions.java
  spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/store/EndpointDataReferenceCacheTestBase.java
  spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/store/EndpointDataReferenceEntryIndexTestBase.java
  spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/store/EndpointDataReferenceStoreTestBase.java
Labels: enhancement

#3983 feat: EDR cache API
  extensions/control-plane/api/management-api/edr-cache-api/build.gradle.kts
  extensions/control-plane/api/management-api/edr-cache-api/src/main/java/org/eclipse/edc/connector/api/management/edr/EdrCacheApiExtension.java
  extensions/control-plane/api/management-api/edr-cache-api/src/main/java/org/eclipse/edc/connector/api/management/edr/transform/JsonObjectFromEndpointDataReferenceEntryTransformer.java
  extensions/control-plane/api/management-api/edr-cache-api/src/main/java/org/eclipse/edc/connector/api/management/edr/v1/EdrCacheApi.java
  extensions/control-plane/api/management-api/edr-cache-api/src/main/java/org/eclipse/edc/connector/api/management/edr/v1/EdrCacheApiController.java
  extensions/control-plane/api/management-api/edr-cache-api/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/api/management-api/edr-cache-api/src/test/java/org/eclipse/edc/connector/api/management/edr/transform/JsonObjectFromEndpointDataReferenceEntryTransformerTest.java
  extensions/control-plane/api/management-api/edr-cache-api/src/test/java/org/eclipse/edc/connector/api/management/edr/v1/EdrCacheApiControllerTest.java
  extensions/control-plane/api/management-api/edr-cache-api/src/test/java/org/eclipse/edc/connector/api/management/edr/v1/EdrCacheApiExtensionTest.java
  extensions/control-plane/api/management-api/edr-cache-api/src/test/java/org/eclipse/edc/connector/api/management/edr/v1/EdrCacheApiTest.java
  settings.gradle.kts
  spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/types/EndpointDataReferenceEntry.java
Labels: enhancement, api

#3987 feat(dsp): implement `TransferSuspensionMessage` transformers
  .github/workflows/apidoc.yaml
  core/common/transform-dspace/build.gradle.kts
  data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/type/DspPropertyAndTypeNames.java
  data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/type/DspTransferProcessPropertyAndTypeNames.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/DspTransferProcessTransformExtension.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromTransferSuspensionMessageTransformer.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/to/JsonObjectToTransferSuspensionMessageTransformer.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/to/JsonObjectToTransferTerminationMessageTransformer.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/from/JsonObjectFromTransferSuspensionMessageTransformerTest.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/to/JsonObjectToTransferSuspensionMessageTransformerTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferSuspensionMessage.java
Labels: enhancement, dataspace-protocol

#3991 feat: register default PublicEndpointGenerator fct
  extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlanePublicApiExtension.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSignalingApiEndToEndTest.java
Labels: enhancement, dpf

#3988 feat: enable HTTP pull scenario E2E test with DPS
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultIamServicesExtension.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImplTest.java
  extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java
  extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlanePublicApiV2Extension.java
  extensions/data-plane/data-plane-public-api-v2/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiController.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiControllerTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/participant/DataPlaneParticipant.java
  system-tests/e2e-transfer-test/data-plane/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferInMemoryTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferPostgresqlTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/AbstractSignalingTransfer.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/SignalingTransferInMemoryTest.java
Labels: enhancement

#4000 feat: store claims on additionalProperties
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultIamServicesExtension.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImplTest.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAccessControlService.java
Labels: enhancement

#4002 refactor: transfer e2e tests
  .github/workflows/release-edc.yml
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndKafkaTransferTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/InMemoryRuntimes.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/PostgresRuntimes.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndTestBase.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPushEndToEndTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
Labels: refactoring

#3948 chore: deprecate provider_id field in ContractRequest
  core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/LogDeprecatedValue.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImplTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractRequestTransformer.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/validation/ContractRequestValidator.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractRequestTransformerTest.java
  extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/validation/ContractRequestValidatorTest.java
  spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequest.java
Labels: enhancement, refactoring, api

#4011 docs: Qualify auth endpoint property values
  docs/developer/data-plane-signaling/data-plane-signaling-token-handling.md
Labels: enhancement

#4012 chore: fix after IATP changes
  extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifier.java
  extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/rules/TokenNotNullRule.java
  extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifierTest.java
  extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/rules/TokenNotNullRuleTest.java
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClient.java
  extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClientTest.java
  extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java
  extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java
  extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/verification/MultiFormatPresentationVerifierTest.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-api/src/main/java/org/eclipse/edc/connector/api/sts/controller/SecureTokenServiceApiController.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-api/src/main/java/org/eclipse/edc/connector/api/sts/model/StsTokenRequest.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/core/defaults/service/StsClientTokenGeneratorServiceImpl.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/core/defaults/StsClientTokenIssuanceIntegrationTest.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-embedded/src/main/java/org/eclipse/edc/iam/identitytrust/sts/embedded/EmbeddedSecureTokenService.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-embedded/src/test/java/org/eclipse/edc/iam/identitytrust/sts/embedded/EmbeddedSecureTokenServiceIntegrationTest.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/RemoteSecureTokenService.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote/src/test/java/org/eclipse/edc/iam/identitytrust/sts/remote/RemoteSecureTokenServiceTest.java
  launchers/sts-server/README.md
  spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/SecureTokenService.java
  spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/SelfIssuedTokenConstants.java
  spi/common/identity-trust-spi/src/testFixtures/java/org/eclipse/edc/identitytrust/TestFunctions.java
  system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/RemoteStsEndToEndTest.java
  system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/StsApiEndToEndTest.java
Labels: bug

#4017 chore: restore scope field
  DEPENDENCIES
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClient.java
  extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClientTest.java
Labels: bug

#4018 feat: do not map root level properties as asset properties
  core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/edc/to/JsonObjectToAssetTransformer.java
  core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/edc/to/JsonObjectToAssetTransformerTest.java
Labels: enhancement, api

#4021 chore: remove util dependency on SPI and remove Jax-RS dependency
  core/common/util/build.gradle.kts
  core/common/util/src/main/java/org/eclipse/edc/util/reflection/PathItem.java
  core/common/util/src/main/java/org/eclipse/edc/util/reflection/ReflectionUtil.java
  extensions/common/iam/decentralized-identity/identity-did-core/build.gradle.kts
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/FieldTranslator.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/JsonFieldTranslator.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/PlainColumnFieldTranslator.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/TranslationMapping.java
  extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/JsonFieldTranslatorTest.java
  extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/PlainColumnFieldTranslatorTest.java
  extensions/control-plane/store/sql/asset-index-sql/build.gradle.kts
  spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/PathItemTest.java
Labels: refactoring, dependencies

#4024 fix: @Setting annotations placement
  core/common/boot/src/main/java/org/eclipse/edc/boot/BootServicesExtension.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/DefaultServiceExtensionContext.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreDefaultServicesExtension.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/OkHttpClientConfiguration.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/OkHttpClientFactory.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/RetryPolicyConfiguration.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/RetryPolicyFactory.java
  core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/OkHttpClientFactoryTest.java
  core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/RetryPolicyFactoryTest.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultIamServicesExtension.java
  extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyConfiguration.java
  extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyExtension.java
  extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/JerseyConfigurationTest.java
  extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/JerseyRestServiceTest.java
  extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyConfiguration.java
  extensions/common/iam/decentralized-identity/identity-did-web/src/main/java/org/eclipse/edc/iam/did/web/ConfigurationKeys.java
  extensions/common/iam/decentralized-identity/identity-did-web/src/main/java/org/eclipse/edc/iam/did/web/WebDidExtension.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/SqlCoreExtension.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/SqlQueryExecutorConfiguration.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolConfigKeys.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtension.java
  extensions/common/sql/sql-pool/sql-pool-apache-commons/src/test/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtensionTest.java
  extensions/common/transaction/transaction-atomikos/src/main/java/org/eclipse/edc/transaction/atomikos/AtomikosTransactionExtension.java
  extensions/common/transaction/transaction-atomikos/src/main/java/org/eclipse/edc/transaction/atomikos/DataSourceConfigurationKeys.java
  extensions/common/transaction/transaction-atomikos/src/main/java/org/eclipse/edc/transaction/atomikos/DataSourceConfigurationParser.java
  extensions/common/transaction/transaction-atomikos/src/main/java/org/eclipse/edc/transaction/atomikos/TransactionManagerConfigurationKeys.java
  extensions/common/transaction/transaction-atomikos/src/test/java/org/eclipse/edc/transaction/atomikos/AtomikosTransactionExtensionTest.java
  extensions/common/transaction/transaction-atomikos/src/test/java/org/eclipse/edc/transaction/atomikos/DataSourceConfigurationParserTest.java
  extensions/common/transaction/transaction-atomikos/src/test/java/org/eclipse/edc/transaction/atomikos/JdbcTestFixtures.java
  extensions/common/vault/vault-filesystem/src/main/java/org/eclipse/edc/vault/filesystem/FsConfiguration.java
  extensions/common/vault/vault-filesystem/src/main/java/org/eclipse/edc/vault/filesystem/FsVaultExtension.java
  extensions/common/vault/vault-filesystem/src/main/java/org/eclipse/edc/vault/filesystem/JskPrivateKeyResolverExtension.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultClientConfig.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultExtension.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultHealthExtension.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/model/Constants.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultExtensionTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultIntegrationTest.java
  extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/HttpProvisionerExtension.java
  extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/config/ConfigParser.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/ConfigurationKeys.java
  extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndexServiceExtension.java
  extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndexServiceExtensionTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtension.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneDefaultServicesExtension.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtensionTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/ServiceExtensionContext.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/TransferDataPlaneConfig.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/BaseEndToEndParticipant.java
Labels: documentation, build

#4019 feat: implements revocation in DataPlaneAuthorizationService
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/listener/TransferProcessEventListener.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImpl.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImpl.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImplTest.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImplTest.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  extensions/control-plane/edr/edr-store-receiver/src/main/java/org/eclipse/edc/connector/edr/store/receiver/EndpointDataReferenceStoreReceiver.java
  extensions/control-plane/edr/edr-store-receiver/src/test/java/org/eclipse/edc/connector/edr/store/receiver/EndpointDataReferenceStoreReceiverTest.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAccessTokenService.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAuthorizationService.java
  spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/store/AccessTokenDataTestBase.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/SignalingEndToEndTransferTest.java
Labels: enhancement

#3782 feat: implement automatic hashicorp token renewal
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpCertificateResolver.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultClient.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultClientConfig.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultClientFallbackFactory.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultExtension.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultHealthCheck.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultHealthExtension.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultSettings.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultTokenRenewTask.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/model/CreateEntryResponsePayload.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/model/EntryMetadata.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/model/GetEntryResponsePayload.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/model/HealthResponse.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/model/HealthResponsePayload.java
  extensions/common/vault/vault-hashicorp/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpCertificateResolverTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultClientFallbackFactoryTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultClientIntegrationTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultClientTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultExtensionTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultHealthCheckTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultIntegrationTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultSettingsTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultTokenRenewTaskTest.java
  extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/util/X509CertificateTestUtil.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/health/HealthCheckResult.java
Labels: enhancement

#4009 refactor: inline `DataRequest` value object into `TransferProcess`
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/transferprocess/InMemoryTransferProcessStore.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferCoreExtension.java
  core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImplTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplIntegrationTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/provision/DeprovisionResponsesHandlerTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/provision/ProvisionResponsesHandlerTest.java
  core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImplTest.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/api/controller/DspTransferProcessApiControllerTest.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/from/JsonObjectFromTransferProcessTransformerTest.java
  extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
  extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/transform/JsonObjectFromTransferProcessTransformerTest.java
  extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProviderResourceDefinitionGeneratorTest.java
  extensions/control-plane/store/sql/transfer-process-store-sql/README.md
  extensions/control-plane/store/sql/transfer-process-store-sql/docs/schema.sql
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/BaseSqlDialectStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/TransferProcessStoreStatements.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/DataRequestMapping.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/TransferProcessMapping.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/transferprocess/PostgresTransferProcessStoreTest.java
  extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java
  extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullDataPlaneProxyResolver.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowControllerTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowControllerTest.java
  extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullDataPlaneProxyResolverTest.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/dynamic/TestFunctions.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/DataRequest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java
  spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/transfer/spi/types/DataRequestTest.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TestFunctions.java
  spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TransferProcessStoreTestBase.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
  system-tests/protocol-test/src/test/java/org/eclipse/edc/test/e2e/protocol/DspTransferApiEndToEndTest.java
Labels: refactoring, breaking-change

#4025 feat: SQL implementation of the EDR index store
  extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlEndToEndInstance.java
  extensions/common/store/sql/edr-index-sql/build.gradle.kts
  extensions/common/store/sql/edr-index-sql/docs/schema.sql
  extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/SqlEndpointDataReferenceEntryIndex.java
  extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/SqlEndpointDataReferenceEntryIndexExtension.java
  extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/schema/BaseSqlDialectStatements.java
  extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/schema/EndpointDataReferenceEntryStatements.java
  extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/schema/postgres/EndpointDataReferenceEntryMapping.java
  extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/schema/postgres/PostgresDialectStatements.java
  extensions/common/store/sql/edr-index-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/store/sql/edr-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/edr/SqlEndpointDataReferenceEntryIndexExtensionTest.java
  extensions/common/store/sql/edr-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/edr/SqlEndpointDataReferenceEntryIndexTest.java
  settings.gradle.kts
  spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/store/EndpointDataReferenceEntryIndex.java
  spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/TestFunctions.java
  spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/store/EndpointDataReferenceEntryIndexTestBase.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/PostgresSignalingRuntimes.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/SignalingEndToEndTransferTest.java
Labels: enhancement

#4036 chore: Participant self method as protected
  extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java
Labels: enhancement

#4040 feat: Remove Junit dependency and move test to proper module
  core/common/util/src/test/java/org/eclipse/edc/util/reflection/PathItemTest.java
  spi/common/core-spi/build.gradle.kts
Labels: refactoring

#4039 chore: fix NPE when dataplane is null on data plane signaling client
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClient.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTest.java
Labels: bug

#4044 feat: introduces properties provider for DataFlowStartMessage
  extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneSignalingExtension.java
  extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/DataPlaneSignalingFlowController.java
  extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowPropertiesProvider.java
Labels: enhancement

#4049 refactor: log `JtiValidationRule` warning only once at creation time
  extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/rules/JtiValidationRule.java
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java
Labels: refactoring

#4048 feat(dsp): cache dspace jsonld context document
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
  extensions/common/json-ld/src/main/resources/document/dspace.jsonld
Labels: enhancement, dataspace-protocol

#4055 fix: convert RSA private key to JWK
  core/common/lib/crypto-common-lib/src/main/java/org/eclipse/edc/security/token/jwt/CryptoConverter.java
  core/common/lib/crypto-common-lib/src/test/java/org/eclipse/edc/security/token/jwt/CryptoConverterTest.java
Labels: bug

#4059 build: add workflow_dispatch for publish autodoc and openapi ui
  .github/workflows/publish-autodoc.yml
  .github/workflows/publish-openapi-ui.yml
  DEPENDENCIES
Labels: build

#4056 feat(policy): handle 'remedy' attribute in Prohibition
  core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/odrl/from/JsonObjectFromPolicyTransformer.java
  core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/odrl/to/JsonObjectToProhibitionTransformer.java
  core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/odrl/from/JsonObjectFromPolicyTransformerTest.java
  core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/odrl/to/JsonObjectToProhibitionTransformerTest.java
  spi/common/policy-model/src/main/java/org/eclipse/edc/policy/model/Prohibition.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractAgreementApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractDefinitionApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/InMemoryRuntime.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PostgresRuntime.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/Runtimes.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
Labels: enhancement, api, dataspace-protocol

#4063 chore: issue SEVERE message when no DID value provided
  DEPENDENCIES
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java
  extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java
Labels: enhancement
