Repository eclipse-edc/Connector, pull requests merged in 2024-11, with the labels that each got.

#4579 feat: allow bi-directional data transfers
  core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/flow/TransferTypeParserImpl.java
  core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/flow/TransferTypeParserImplTest.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/PublicEndpointGeneratorServiceImpl.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/PublicEndpointGeneratorServiceImplTest.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  docs/developer/decision-records/2024-10-24-bidirectional-data-transfers/README.md
  docs/developer/decision-records/README.md
  extensions/data-plane/data-plane-iam/src/main/java/org/eclipse/edc/connector/dataplane/iam/service/DataPlaneAuthorizationServiceImpl.java
  extensions/data-plane/data-plane-integration-tests/src/test/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpIntegrationTests.java
  extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlanePublicApiV2Extension.java
  extensions/data-plane/data-plane-self-registration/src/main/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtension.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowStartMessageTransformer.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowStartMessageTransformer.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowStartMessageTransformerTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowStartMessageTransformerTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowStartMessage.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/TransferType.java
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstance.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/PublicEndpointGeneratorService.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSignalingApiEndToEndTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/participant/DataPlaneParticipant.java
Labels: enhancement

#4593 refactor: remove unnecessary sort in DependencyGraph
  core/common/boot/src/main/java/org/eclipse/edc/boot/BootServicesExtension.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/DependencyGraph.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/DependencyGraphTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/ExtensionLoaderTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/InjectorImplTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/TestFunctions.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/lifecycle/ExtensionLifecycleManagerTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/runtime/BaseRuntimeTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/BaseExtension.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/CoreExtension.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java
  core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/ContractCoreExtension.java
  core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/ContractNegotiationCommandExtension.java
  core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/TransferCoreExtension.java
  core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/TransferProcessCommandExtension.java
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
  extensions/common/metrics/micrometer-core/src/main/java/org/eclipse/edc/metrics/micrometer/MicrometerExtension.java
Labels: refactoring

#4602 fix: removes double forNamespace call
  data-protocols/dsp/dsp-negotiation/lib/dsp-negotiation-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformer.java
  data-protocols/dsp/dsp-negotiation/lib/dsp-negotiation-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformerTest.java
Labels: bug

#4604 refactor: cleanup 0.6.x deprecations
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceIntegrationTest.java
  extensions/common/auth/auth-basic/README.md
  extensions/common/auth/auth-basic/build.gradle.kts
  extensions/common/auth/auth-basic/src/main/java/org/eclipse/edc/api/auth/basic/BasicAuthenticationExtension.java
  extensions/common/auth/auth-basic/src/main/java/org/eclipse/edc/api/auth/basic/BasicAuthenticationService.java
  extensions/common/auth/auth-basic/src/main/java/org/eclipse/edc/api/auth/basic/ConfigCredentials.java
  extensions/common/auth/auth-basic/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/auth/auth-basic/src/test/java/org/eclipse/edc/api/auth/basic/BasicAuthenticationExtensionTest.java
  extensions/common/auth/auth-basic/src/test/java/org/eclipse/edc/api/auth/basic/BasicAuthenticationServiceTest.java
  extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifier.java
  extensions/common/crypto/ldp-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/linkeddata/LdpVerifier.java
  extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImpl.java
  extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/DidCredentialServiceUrlResolver.java
  extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustService.java
  extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java
  extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiV2.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactory.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactoryTest.java
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java
  extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/connector/dataplane/kafka/pipeline/KafkaDataSinkFactory.java
  extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/connector/dataplane/kafka/pipeline/KafkaDataSourceFactory.java
  extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/connector/dataplane/kafka/pipeline/KafkaDataSinkFactoryTest.java
  extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/connector/dataplane/kafka/pipeline/KafkaDataSourceFactoryTest.java
  settings.gradle.kts
  spi/common/boot-spi/src/main/java/org/eclipse/edc/spi/result/Result.java
  spi/common/boot-spi/src/test/java/org/eclipse/edc/spi/result/ResultTest.java
  spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/ApiContext.java
  spi/control-plane/policy-spi/src/main/java/org/eclipse/edc/connector/controlplane/policy/spi/PolicyDefinition.java
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/DataPlaneSelectorService.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSinkFactory.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSourceFactory.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java
Labels: refactoring, breaking-change

#4600 refactor: save one iteration of the extension list in DependencyGraph
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/DependencyGraph.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ProviderMethodScanner.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ProviderMethodScannerTest.java
Labels: refactoring

#4611 docs: decision record about configuration injection
  docs/developer/decision-records/2024-11-06-configuration-injection/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#4588 fix: sub-catalogs serialization
  data-protocols/dsp/dsp-catalog/lib/dsp-catalog-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogTransformer.java
  data-protocols/dsp/dsp-catalog/lib/dsp-catalog-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/v2024/from/JsonObjectFromCatalogV2024Transformer.java
  data-protocols/dsp/dsp-catalog/lib/dsp-catalog-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogTransformerTest.java
  data-protocols/dsp/dsp-catalog/lib/dsp-catalog-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/v2024/from/JsonObjectFromCatalogV2024TransformerTest.java
  spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java
Labels: bug, breaking-change

#4617 feat: implement Configuration Injection
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/DependencyGraph.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPoint.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionContainer.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionPoint.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionPointScanner.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectorImpl.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ServiceInjectionPoint.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ValueInjectionPoint.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/ExtensionLoaderTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/InjectorImplTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/TestFunctions.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPointTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/InjectionPointDefaultServiceSupplierTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ServiceInjectionPointTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ValueInjectionPointTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/ConfigurationObject.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/ExtensionWithConfigObject.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/ExtensionWithConfigValue.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/RequiredDependentExtension.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java
  extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote-client/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/client/StsRemoteClientConfigurationExtension.java
  extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote-client/src/test/java/org/eclipse/edc/iam/identitytrust/sts/remote/client/StsRemoteClientConfigurationExtensionTest.java
Labels: enhancement, core feature

#4620 feat: improve handling of default values for ValueInjectionPoints
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/DependencyGraph.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPoint.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionPoint.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionPointDefaultServiceSupplier.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ServiceInjectionPoint.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ValueInjectionPoint.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/lifecycle/ExtensionLifecycleManager.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/lifecycle/ServiceProvider.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPointTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/InjectionPointDefaultServiceSupplierTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ValueInjectionPointTest.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/lifecycle/ServiceProviderTest.java
  core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java
  core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/DependencyInjectionExtension.java
  spi/common/boot-spi/src/main/java/org/eclipse/edc/spi/system/ValueProvider.java
Labels: enhancement

#4621 feat: adds flag to enable validation on create/update policy definitions
  core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/validation/PolicyValidator.java
  core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplValidationTest.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/policydefinition/PolicyDefinitionServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/policydefinition/PolicyDefinitionServiceImplTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ManagementEndToEndExtension.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
Labels: enhancement

#4623 fix: package declaration of JtiValidationStore
  extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/SqlJtiValidationStore.java
  extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/SqlJtiValidationStoreExtension.java
  extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/schema/BaseSqlDialectStatements.java
  extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/schema/JtiValidationStoreStatements.java
  extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/schema/postgres/PostgresDialectStatements.java
  extensions/common/store/sql/jti-validation-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/store/sql/jti-validation-store-sql/src/test/java/org/eclipse/edc/jtivalidation/store/sql/SqlJtiValidationStoreExtensionTest.java
  extensions/common/store/sql/jti-validation-store-sql/src/test/java/org/eclipse/edc/jtivalidation/store/sql/SqlJtiValidationStoreTest.java
Labels: bug

#4629 refactor: set INFO as default log level, downgraded some log calls
  core/common/boot/src/main/java/org/eclipse/edc/boot/config/ConfigurationLoader.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/ExtensionLoader.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/lifecycle/ExtensionLifecycleManager.java
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/ExtensionLoaderTest.java
  core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EmbeddedRuntime.java
  extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyRestService.java
  extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyService.java
  extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/WebServiceConfigurerImpl.java
  extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/health/HashicorpVaultHealthExtension.java
  extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/controlplane/provision/http/HttpProvisionerExtension.java
  extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSource.java
  extensions/data-plane/data-plane-iam/src/main/java/org/eclipse/edc/connector/dataplane/iam/service/DefaultDataPlaneAccessTokenServiceImpl.java
  extensions/data-plane/data-plane-self-registration/src/main/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtension.java
  spi/common/boot-spi/src/main/java/org/eclipse/edc/spi/monitor/ConsoleMonitor.java
Labels: refactoring

#4627 fix: add capability to encode `kid` header in request to Oauth2 server
  extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtension.java
  extensions/data-plane/data-plane-http-oauth2-core/src/main/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2CredentialsRequestFactory.java
  spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2AssertionDecorator.java
  spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2DataAddressSchema.java
  spi/common/oauth2-spi/src/test/java/org/eclipse/edc/iam/oauth2/spi/Oauth2AssertionDecoratorTest.java
Labels: bug

#4612 feat: restart interrupted data flows
  core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EmbeddedRuntime.java
  core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/CriterionOperatorRegistryImpl.java
  core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/LessThanOperatorPredicate.java
  core/common/lib/query-lib/src/test/java/org/eclipse/edc/query/LessThanOperatorPredicateTest.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/AbstractStateEntityManager.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtension.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtensionTest.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImplTest.java
  extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslator.java
  extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslatorTest.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlDataPlaneStatements.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/postgres/DataFlowMapping.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/CriterionOperatorRegistry.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/manager/DataPlaneManager.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/TransferService.java
  spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/testfixtures/store/DataPlaneStoreTestBase.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
Labels: enhancement, dpf

#4646 fix: not required properties in DcpDefaultServicesExtension
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/DcpDefaultServicesExtension.java
  extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/DcpDefaultServicesExtensionTest.java
Labels: bug

#4647 fix: Fatal error while resume PULL transfer from provider
  extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java
  spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcessTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndTestBase.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPushEndToEndTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
Labels: bug
