Repository eclipse-edc/Connector, pull requests merged in 2025-02, with the labels that each got.

#4780 feat: adds support for dcp v1.0 in default credential service client
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClient.java
  extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java
  extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClientTest.java
Labels: enhancement, breaking-change

#4786 chore: improve SerDes of CredentialStatus
  spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialStatus.java
  spi/common/verifiable-credentials-spi/src/test/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialStatusSerDesTest.java
Labels: bug

#4796 feat: add `toBuilder()` methods
  spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialSubject.java
  spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/VerifiableCredential.java
Labels: enhancement

#4801 refactor: delete EDR receiver extensions
  core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/TransferCoreExtension.java
  core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/edr/EndpointDataReferenceReceiverRegistryImpl.java
  core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/edr/EndpointDataReferenceReceiverRegistryImplTest.java
  extensions/README.md
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/README.md
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/build.gradle.kts
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/java/org/eclipse/edc/connector/controlplane/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiver.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/java/org/eclipse/edc/connector/controlplane/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiverExtension.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/controlplane/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiverTest.java
  extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/controlplane/receiver/http/dynamic/TestFunctions.java
  extensions/control-plane/transfer/transfer-pull-http-receiver/build.gradle.kts
  extensions/control-plane/transfer/transfer-pull-http-receiver/src/main/java/org/eclipse/edc/connector/controlplane/receiver/http/HttpEndpointDataReferenceReceiver.java
  extensions/control-plane/transfer/transfer-pull-http-receiver/src/main/java/org/eclipse/edc/connector/controlplane/receiver/http/HttpEndpointDataReferenceReceiverExtension.java
  extensions/control-plane/transfer/transfer-pull-http-receiver/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/transfer/transfer-pull-http-receiver/src/test/java/org/eclipse/edc/connector/controlplane/receiver/http/HttpEndpointDataReferenceReceiverTest.java
  settings.gradle.kts
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/edr/EndpointDataReferenceReceiverRegistry.java
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
Labels: refactoring

#4800 docs: decision record about toBuilder and copy
  docs/developer/decision-records/2025-02-06-object_mutability_and_copying/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#4799 docs: provide DR for RetryProcess refactor
  docs/developer/decision-records/2025-02-05-state-machine-retry-processor-refactor/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#4802 docs: add decision record for HashiCorp vault authentication refactoring
  docs/developer/decision-records/2025-02-06-hashicorp-vault-authentication-refactor/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#4805 docs: DR for http-proxy deprecation
  docs/developer/decision-records/2025-02-07-http-proxy-data-plane-deprecation/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#4808 feat: map TERMINATING_REQUESTED status to TERMINATED on DSP get transfer process call
  data-protocols/dsp/dsp-transfer-process/lib/dsp-transfer-process-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/type/v2024/from/JsonObjectFromTransferProcessV2024Transformer.java
  data-protocols/dsp/dsp-transfer-process/lib/dsp-transfer-process-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/v2024/from/JsonObjectFromTransferProcessV2024TransformerTest.java
Labels: enhancement

#4787 refactor: introduce RetryProcessor
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/AsyncStatusResultRetryProcess.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/CompletableFutureRetryProcess.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessConfiguration.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessFactory.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/RetryProcess.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcess.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/EntityStateException.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/FutureResultRetryProcess.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/FutureRetryProcess.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/Process.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/ProcessContext.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/ResultRetryProcess.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/RetryProcessor.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/UnrecoverableEntityStateException.java
  core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/FutureResultRetryProcessTest.java
  core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/FutureRetryProcessTest.java
  core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/ResultRetryProcessTest.java
  core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/RetryProcessorTest.java
  core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImplTest.java
Labels: refactoring

#4814 feat: implement JsonArrayTranslator
  core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/JsonArrayTranslator.java
  core/common/lib/sql-lib/src/test/java/org/eclipse/edc/sql/translation/JsonArrayTranslatorTest.java
Labels: enhancement

#4816 refactor: move data flow suspension call in transfer process manager
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImplTest.java
  core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImplTest.java
  data-protocols/dsp/dsp-transfer-process/lib/dsp-transfer-process-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/type/v2024/from/JsonObjectFromTransferProcessV2024Transformer.java
  data-protocols/dsp/dsp-transfer-process/lib/dsp-transfer-process-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/v2024/from/JsonObjectFromTransferProcessV2024TransformerTest.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcessStates.java
Labels: refactoring

#4817 refactor: replace all the RetryProcess usages with RetryProcessor
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessConfiguration.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessFactory.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/FutureResultRetryProcess.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/FutureRetryProcess.java
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/Process.java
  core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/FutureResultRetryProcessTest.java
  core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/FutureRetryProcessTest.java
  core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/negotiation/AbstractContractNegotiationManager.java
  core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
  core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ProviderContractNegotiationManagerImpl.java
  core/control-plane/control-plane-contract/src/test/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
  core/control-plane/control-plane-contract/src/test/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java
Labels: refactoring

#4820 chore: add column name to JsonArrayTranslator
  core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/JsonArrayTranslator.java
  core/common/lib/sql-lib/src/test/java/org/eclipse/edc/sql/translation/JsonArrayTranslatorTest.java
Labels: enhancement

#4819 refactor: extract api-lib to avoid extensions depending on api-core
  core/common/lib/api-lib/build.gradle.kts
  core/common/lib/api-lib/src/main/java/org/eclipse/edc/api/model/ApiCoreSchema.java
  core/common/lib/api-lib/src/main/java/org/eclipse/edc/api/model/IdResponse.java
  core/common/lib/api-lib/src/main/java/org/eclipse/edc/api/transformer/JsonObjectFromCallbackAddressTransformer.java
  core/common/lib/api-lib/src/main/java/org/eclipse/edc/api/transformer/JsonObjectFromIdResponseTransformer.java
  core/common/lib/api-lib/src/main/java/org/eclipse/edc/api/transformer/JsonObjectToCallbackAddressTransformer.java
  core/common/lib/api-lib/src/main/java/org/eclipse/edc/api/validation/DataAddressValidator.java
  core/common/lib/api-lib/src/test/java/org/eclipse/edc/api/model/ApiCoreSchemaTest.java
  core/common/lib/api-lib/src/test/java/org/eclipse/edc/api/transformer/JsonObjectFromCallbackAddressTransformerTest.java
  core/common/lib/api-lib/src/test/java/org/eclipse/edc/api/transformer/JsonObjectFromIdResponseTransformerTest.java
  core/common/lib/api-lib/src/test/java/org/eclipse/edc/api/transformer/JsonObjectToCallbackAddressTransformerTest.java
  core/common/lib/api-lib/src/test/java/org/eclipse/edc/api/validation/DataAddressValidatorTest.java
  dist/bom/controlplane-base-bom/build.gradle.kts
  dist/bom/dataplane-base-bom/build.gradle.kts
  dist/bom/sts-feature-bom/build.gradle.kts
  extensions/common/api/api-core/build.gradle.kts
  extensions/common/api/control-api-configuration/build.gradle.kts
  extensions/common/api/management-api-configuration/build.gradle.kts
  extensions/common/api/version-api/build.gradle.kts
  extensions/control-plane/api/control-plane-api-client/build.gradle.kts
  extensions/control-plane/api/management-api/asset-api/build.gradle.kts
  extensions/control-plane/api/management-api/catalog-api/build.gradle.kts
  extensions/control-plane/api/management-api/contract-agreement-api/build.gradle.kts
  extensions/control-plane/api/management-api/contract-definition-api/build.gradle.kts
  extensions/control-plane/api/management-api/contract-negotiation-api/build.gradle.kts
  extensions/control-plane/api/management-api/edr-cache-api/build.gradle.kts
  extensions/control-plane/api/management-api/policy-definition-api/build.gradle.kts
  extensions/control-plane/api/management-api/protocol-version-api/build.gradle.kts
  extensions/control-plane/api/management-api/secrets-api/build.gradle.kts
  extensions/control-plane/api/management-api/transfer-process-api/build.gradle.kts
  extensions/control-plane/provision/provision-http/build.gradle.kts
  extensions/data-plane-selector/data-plane-selector-api/build.gradle.kts
  extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorServiceTest.java
  extensions/data-plane-selector/data-plane-selector-control-api/build.gradle.kts
  extensions/data-plane/data-plane-integration-tests/src/test/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpIntegrationTests.java
  settings.gradle.kts
  system-tests/e2e-dataplane-tests/runtimes/data-plane/build.gradle.kts
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/AbstractDataPlaneTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/ClusteredDataPlaneEndToEndTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlanePublicApiEndToEndTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSelectorEndToEndTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSignalingApiEndToEndTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataplaneSelectorControlApiEndToEndTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DummyControlPlane.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/participant/DataPlaneParticipant.java
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/e2e-transfer-test/data-plane/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java
  system-tests/management-api/management-api-test-runner/build.gradle.kts
  system-tests/version-api/version-api-test-runner/build.gradle.kts
Labels: refactoring

#4823 refactor: deprecate data-plane-public-api-v2 and proxy feature
  core/common/lib/transform-lib/src/test/java/org/eclipse/edc/transform/transformer/edc/to/JsonObjectToDataPlaneInstanceTransformerTest.java
  core/control-plane/control-plane-aggregate-services/build.gradle.kts
  extensions/control-plane/transfer/transfer-data-plane-signaling/build.gradle.kts
  extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImplSourceTest.java
  extensions/data-plane/data-plane-integration-tests/src/test/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpIntegrationTests.java
  extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlanePublicApiV2Extension.java
  extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/ContainerRequestContextApi.java
  extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/ContainerRequestContextApiImpl.java
  extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/DataFlowRequestSupplier.java
  extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlanePublicApiV2.java
  extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlanePublicApiV2Controller.java
  extensions/data-plane/data-plane-public-api-v2/src/main/resources/public-api-version.json
  settings.gradle.kts
  spi/control-plane/transfer-data-plane-spi/build.gradle.kts
  spi/control-plane/transfer-data-plane-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/spi/TransferDataPlaneConstants.java
  spi/control-plane/transfer-data-plane-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/spi/package-info.java
  spi/control-plane/transfer-data-plane-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/spi/security/DataEncrypter.java
  spi/control-plane/transfer-data-plane-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/spi/token/ConsumerPullTokenExpirationDateFunction.java
  spi/data-plane/data-plane-http-spi/src/main/java/org/eclipse/edc/connector/dataplane/http/spi/HttpDataAddress.java
Labels: refactoring

#4784 fix: Add missing audience validation when accessing management api with oauth
  extensions/common/auth/auth-delegated/src/main/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtension.java
  extensions/common/auth/auth-delegated/src/test/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtensionTest.java
Labels: enhancement, api

#4829 feat: filter state by string
  core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/EntityStateFieldTranslator.java
  core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/FieldTranslator.java
  core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/JsonArrayTranslator.java
  core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/JsonFieldTranslator.java
  core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/PlainColumnFieldTranslator.java
  core/common/lib/sql-lib/src/test/java/org/eclipse/edc/sql/translation/EntityStateFieldTranslatorTest.java
  core/common/lib/store-lib/src/main/java/org/eclipse/edc/store/AndOperatorCriteriaToPredicate.java
  core/common/lib/store-lib/src/main/java/org/eclipse/edc/store/InMemoryStatefulEntityStore.java
  core/common/lib/store-lib/src/main/java/org/eclipse/edc/store/ReflectionBasedQueryResolver.java
  core/common/lib/store-lib/src/main/java/org/eclipse/edc/store/StatefulEntityCriteriaToPredicate.java
  core/common/lib/store-lib/src/test/java/org/eclipse/edc/store/ReflectionBasedQueryResolverTest.java
  core/common/lib/store-lib/src/test/java/org/eclipse/edc/store/StatefulEntityCriteriaToPredicateTest.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/controlplane/defaults/storage/contractnegotiation/InMemoryContractNegotiationStore.java
  core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/controlplane/defaults/storage/transferprocess/InMemoryTransferProcessStore.java
  core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/InMemoryDataPlaneInstanceStore.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/store/InMemoryDataPlaneStore.java
  core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/store/sql/InMemoryPolicyMonitorStore.java
  extensions/common/sql/sql-lease/src/main/java/org/eclipse/edc/sql/lease/StatefulEntityMapping.java
  extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/postgres/ContractNegotiationMapping.java
  extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/transferprocess/store/schema/postgres/TransferProcessMapping.java
  extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/schema/DataPlaneInstanceMapping.java
  extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/postgres/DataFlowMapping.java
  extensions/policy-monitor/store/sql/policy-monitor-store-sql/src/main/java/org/eclipse/edc/connector/policy/monitor/store/sql/schema/PolicyMonitorMapping.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/entity/StateResolver.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/CriteriaToPredicate.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/QueryResolver.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/DataPlaneSelectorApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ManagementEndToEndExtension.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
Labels: enhancement

#4833 refactor: incorrect paramaters order in dataplane logs regarding DataFlow Id
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImplTest.java
Labels: refactoring

#4831 build(test): use testcontainers for postgresql tests
  .github/workflows/verify.yaml
  extensions/common/sql/sql-test-fixtures/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlEndToEndExtension.java
  extensions/common/sql/sql-test-fixtures/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlEndToEndInstance.java
  extensions/common/sql/sql-test-fixtures/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlLocalInstance.java
  extensions/common/sql/sql-test-fixtures/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlStoreSetupExtension.java
  extensions/common/store/sql/edr-index-sql/src/test/java/org/eclipse/edc/edr/store/index/sql/SqlEndpointDataReferenceEntryIndexTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/ClusteredDataPlaneEndToEndTest.java
  system-tests/e2e-transfer-test/runner/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Runtimes.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPushEndToEndTest.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AuthConfigurationApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractAgreementApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractDefinitionApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/DataPlaneSelectorApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ManagementEndToEndExtension.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ManagementEndToEndTestContext.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/SerdeEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
  system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/StsApiEndToEndTest.java
Labels: refactoring, flaky test

#4818 fix: support VP without VCs in IdentityAndTrustService
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/DcpDefaultServicesExtension.java
  extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/VerifiableCredentialValidationServiceImpl.java
  extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/VerifiableCredentialValidationServiceImplTest.java
Labels: bug

#4845 refactor: remove data-plane-public-v2 deprecated module from dataplane-base-bom
  dist/bom/dataplane-base-bom/build.gradle.kts
  resources/openapi/sts-accounts-api.version
  resources/openapi/sts-api.version
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlanePublicApiEndToEndTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSignalingApiEndToEndTest.java
  system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/participant/DataPlaneParticipant.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/HttpProxyDataPlaneExtension.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
Labels: refactoring, breaking-change

#4848 build: add missing control-plane-api and policy-monitor modules to boms
  dist/bom/controlplane-base-bom/build.gradle.kts
  dist/bom/controlplane-feature-sql-bom/build.gradle.kts
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ManagementEndToEndExtension.java
Labels: enhancement
