Repository eclipse-edc/Connector, pull requests merged in 2025-04, with the labels that each got.

#4899 feat: introduce request presentation with definition
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClient.java
  extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClientTest.java
  extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java
  spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/iam/identitytrust/spi/CredentialServiceClient.java
  spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/presentationdefinition/Field.java
  spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/presentationdefinition/Format.java
  spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/presentationdefinition/InputDescriptor.java
  spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/presentationdefinition/PresentationDefinition.java
Labels: enhancement

#4903 feat: improve StateMachineManager exception catching and shutdown mechanism
  core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/StateMachineManager.java
  core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/StateMachineManagerTest.java
Labels: enhancement, refactoring

#4902 feat: catch shutdown exceptions
  core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java
  core/common/boot/src/test/java/org/eclipse/edc/boot/system/runtime/BaseRuntimeTest.java
Labels: enhancement

#4908 feat: allow multiple validators per type
  core/common/runtime-core/src/main/java/org/eclipse/edc/runtime/core/validator/JsonObjectValidatorRegistryImpl.java
  core/common/runtime-core/src/test/java/org/eclipse/edc/runtime/core/validator/JsonObjectValidatorRegistryImplTest.java
  spi/common/validator-spi/src/main/java/org/eclipse/edc/validator/spi/JsonObjectValidatorRegistry.java
Labels: enhancement, breaking-change

#4917 chore: cleanup core dependencies
  core/common/connector-core/build.gradle.kts
  core/common/lib/crypto-common-lib/build.gradle.kts
  core/common/lib/keys-lib/build.gradle.kts
  core/common/lib/validator-lib/build.gradle.kts
Labels: refactoring

#4914 feat: add retry mechanism on dataflow completion
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/EmbeddedTransferProcessHttpClient.java
  extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/TransferProcessHttpClient.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/port/TransferProcessApiClient.java
Labels: bug

#4928 feat: implement missing <=, >, >= operators
  core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/CriterionOperatorRegistryImpl.java
  core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/EqualOperatorPredicate.java
  core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/LessThanOperatorPredicate.java
  core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/NumberStringOperatorPredicate.java
  core/common/lib/query-lib/src/test/java/org/eclipse/edc/query/LessThanOperatorPredicateTest.java
  core/common/lib/query-lib/src/test/java/org/eclipse/edc/query/NumberStringOperatorPredicateTest.java
  core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslator.java
  core/common/lib/sql-lib/src/test/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslatorTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/CriterionOperatorRegistry.java
Labels: enhancement

#4937 build(test): drop and create database on e2e
  extensions/common/sql/sql-test-fixtures/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlEndToEndExtension.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
Labels: refactoring, flaky test

#4941 refactor: move DSP base webhook and port mapping to separate module
  data-protocols/dsp/build.gradle.kts
  data-protocols/dsp/dsp-2025/build.gradle.kts
  data-protocols/dsp/dsp-2025/dsp-http-api-configuration-2025/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/v2025/DspApiConfigurationV2025Extension.java
  data-protocols/dsp/dsp-http-api-base-configuration/build.gradle.kts
  data-protocols/dsp/dsp-http-api-base-configuration/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiBaseConfigurationExtension.java
  data-protocols/dsp/dsp-http-api-base-configuration/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  data-protocols/dsp/dsp-http-api-base-configuration/src/test/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiBaseConfigurationExtensionTest.java
  data-protocols/dsp/dsp-http-api-configuration/build.gradle.kts
  data-protocols/dsp/dsp-http-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtension.java
  data-protocols/dsp/dsp-http-api-configuration/src/test/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtensionTest.java
  data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/http/spi/api/DspBaseWebhookAddress.java
  settings.gradle.kts
  system-tests/protocol-2025-test/src/test/java/org/eclipse/edc/test/e2e/protocol/v2025/Dsp2025Runtime.java
  system-tests/protocol-test/src/test/java/org/eclipse/edc/test/e2e/protocol/DspRuntime.java
Labels: refactoring, dataspace-protocol

#4951 feat: add retry mechanism to consumer provision
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java
Labels: enhancement

#4953 feat: Implement extension for priming the EDC under test
  settings.gradle.kts
  system-tests/protocol-tck/tck-extension/build.gradle.kts
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/controller/ContractNegotiationRequest.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/controller/TckControllerExtension.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/controller/TckWebhookController.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/data/DataAssembly.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/ContractNegotiationGuard.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/ContractNegotiationTriggerRegistry.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/ContractNegotiationTriggerSubscriber.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/DelayedActionGuard.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/TckGuardExtension.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/Trigger.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/identity/NoopIdentityService.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/identity/TckIdentityExtension.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/recorder/StepRecorder.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/setup/TckSetupExtension.java
  system-tests/protocol-tck/tck-extension/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  system-tests/protocol-tck/tck-extension/src/test/java/org/eclipse/edc/tck/dsp/recorder/StepRecorderTest.java
Labels: enhancement

#4956 fix: permit json to boolean transformation
  core/common/lib/transform-lib/build.gradle.kts
  core/common/lib/transform-lib/src/main/java/org/eclipse/edc/transform/transformer/edc/to/JsonValueToGenericTypeTransformer.java
  core/common/lib/transform-lib/src/test/java/org/eclipse/edc/transform/transformer/edc/to/JsonValueToGenericTypeTransformerTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java
Labels: bug
