Repository eclipse-edc/Connector, pull requests merged in 2025-03, with the labels that each got.

#4854 fix: adds IssuerKeyIdValidationRule to SI token validation
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java
  extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/validation/SelfIssueIdTokenValidationAction.java
  extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/validation/SelfIssueIdTokenValidationActionComponentTest.java
Labels: bug

#4847 docs: add DR for moving provisioning phase in the data-plane
  docs/developer/decision-records/2025-02-27-move-provisioning-phase-data-plane/README.md
  docs/developer/decision-records/README.md
Labels: documentation, stale

#4851 feat: switch JTI validation to black-listing
  extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/rules/JtiValidationRule.java
  extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/rules/JtiValidationRuleTest.java
Labels: enhancement

#4858 refactor: cleanup test dependencies
  core/common/boot/build.gradle.kts
  core/common/connector-core/build.gradle.kts
  core/common/junit/build.gradle.kts
  core/common/lib/http-lib/build.gradle.kts
  data-protocols/dsp/dsp-catalog/lib/dsp-catalog-http-api-lib/build.gradle.kts
  data-protocols/dsp/dsp-http-spi/build.gradle.kts
  data-protocols/dsp/dsp-negotiation/lib/dsp-negotiation-http-api-lib/build.gradle.kts
  data-protocols/dsp/dsp-transfer-process/lib/dsp-transfer-process-http-api-lib/build.gradle.kts
  extensions/common/http/jersey-core/build.gradle.kts
  extensions/common/sql/sql-bootstrapper/build.gradle.kts
  extensions/common/sql/sql-lease/build.gradle.kts
  extensions/common/sql/sql-test-fixtures/build.gradle.kts
  extensions/control-plane/api/management-api/management-api-test-fixtures/build.gradle.kts
  extensions/control-plane/store/sql/asset-index-sql/build.gradle.kts
  extensions/control-plane/store/sql/contract-definition-store-sql/build.gradle.kts
  extensions/control-plane/store/sql/contract-negotiation-store-sql/build.gradle.kts
  extensions/control-plane/store/sql/transfer-process-store-sql/build.gradle.kts
  extensions/data-plane/data-plane-integration-tests/build.gradle.kts
  gradle/libs.versions.toml
  spi/common/core-spi/build.gradle.kts
  spi/common/edr-store-spi/build.gradle.kts
  spi/common/jwt-spi/build.gradle.kts
  spi/control-plane/asset-spi/build.gradle.kts
  spi/control-plane/contract-spi/build.gradle.kts
  spi/control-plane/policy-spi/build.gradle.kts
  spi/control-plane/transfer-spi/build.gradle.kts
  spi/data-plane-selector/data-plane-selector-spi/build.gradle.kts
  spi/data-plane/data-plane-http-spi/build.gradle.kts
  spi/data-plane/data-plane-spi/build.gradle.kts
  spi/policy-monitor/policy-monitor-spi/build.gradle.kts
  system-tests/bom-tests/build.gradle.kts
  system-tests/dsp-compatibility-tests/compatibility-test-runner/build.gradle.kts
  system-tests/e2e-dataplane-tests/tests/build.gradle.kts
  system-tests/e2e-transfer-test/runner/build.gradle.kts
  system-tests/management-api/management-api-test-runner/build.gradle.kts
  system-tests/telemetry/telemetry-test-runner/build.gradle.kts
  system-tests/version-api/version-api-test-runner/build.gradle.kts
  tests/junit-base/build.gradle.kts
  tests/junit-base/src/main/java/org/eclipse/edc/junit/testfixtures/TestUtils.java
Labels: refactoring

#4870 chore: amend config change on wellknown path
  data-protocols/dsp/dsp-http-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtension.java
  data-protocols/dsp/dsp-http-api-configuration/src/test/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtensionTest.java
  data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/DspHttpCoreExtension.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
Labels: bug

#4869 docs: DR for prioritized transfer services
  docs/developer/decision-records/2025-03-14-prioritized-transfer-services/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#4875 feat: add provisioning phase for consumer on data plane
  core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/flow/DataFlowManagerImpl.java
  core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImpl.java
  core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/flow/DataFlowManagerImplTest.java
  core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImplIntegrationTest.java
  core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImplTest.java
  core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorService.java
  core/data-plane-selector/data-plane-selector-core/src/test/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorServiceTest.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultServicesExtension.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtension.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/provision/ResourceDefinitionGeneratorManagerImpl.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/provision/ResourceDefinitionGeneratorManagerImplTest.java
  extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowController.java
  extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java
  extensions/data-plane-selector/data-plane-selector-client/src/main/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorService.java
  extensions/data-plane/data-plane-self-registration/src/main/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtension.java
  extensions/data-plane/data-plane-self-registration/src/test/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtensionTest.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClient.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/EmbeddedDataPlaneClient.java
  extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/EmbeddedDataPlaneClientTest.java
  spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowProvisionMessage.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/flow/DataFlowController.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/flow/DataFlowManager.java
  spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/DataPlaneSelectorService.java
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/client/DataPlaneClient.java
  spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstance.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlowStates.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/manager/DataPlaneManager.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/provision/ProvisionResourceDefinition.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/provision/ResourceDefinitionGenerator.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/provision/ResourceDefinitionGeneratorManager.java
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/ProvisioningTransferEndToEndTest.java
Labels: refactoring

#4876 feat: prioritized transfer services
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/registry/TransferServiceRegistryImpl.java
  core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/registry/TransferServiceSelectionStrategy.java
  core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/registry/TransferServiceRegistryImplTest.java
  spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/registry/TransferServiceRegistry.java
Labels: enhancement

#4878 fix: fix delete asset prevention logic based on contract negotiation
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/asset/AssetServiceImpl.java
  core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/asset/AssetServiceImplTest.java
Labels: bug

#4882 feat: boostrap dsp protocol 2025
  data-protocols/dsp/dsp-2025/build.gradle.kts
  data-protocols/dsp/dsp-2025/dsp-http-api-configuration-2025/build.gradle.kts
  data-protocols/dsp/dsp-2025/dsp-http-api-configuration-2025/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/v2025/DspApiConfigurationV2025Extension.java
  data-protocols/dsp/dsp-2025/dsp-http-api-configuration-2025/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/build.gradle.kts
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/dsp-catalog-http-api-2025/build.gradle.kts
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/dsp-catalog-http-api-2025/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/v2025/DspCatalogApi2025Extension.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/dsp-catalog-http-api-2025/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/v2025/controller/DspCatalogApiController20251.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/dsp-catalog-http-api-2025/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/dsp-catalog-http-api-2025/src/test/java/org/eclipse/edc/protocol/dsp/catalog/http/api/v2025/DspCatalogApi2025ExtensionTest.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/dsp-catalog-http-api-2025/src/test/java/org/eclipse/edc/protocol/dsp/catalog/http/api/v2025/controller/DspCatalogApiControllerV20251Test.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/dsp-catalog-transform-2025/build.gradle.kts
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/dsp-catalog-transform-2025/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/v2025/DspCatalogTransformV2025Extension.java
  data-protocols/dsp/dsp-catalog/dsp-catalog-2025/dsp-catalog-transform-2025/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/http/spi/types/HttpMessageProtocol.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/build.gradle.kts
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/dsp-negotiation-http-api-2025/build.gradle.kts
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/dsp-negotiation-http-api-2025/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/http/api/v2025/DspNegotiationApi2025Extension.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/dsp-negotiation-http-api-2025/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/http/api/v2025/controller/DspNegotiationApiController20251.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/dsp-negotiation-http-api-2025/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/dsp-negotiation-http-api-2025/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/http/api/v2025/DspNegotiationApi2025ExtensionTest.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/dsp-negotiation-http-api-2025/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/http/api/v2025/controller/DspNegotiationApiControllerV20251Test.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/dsp-negotiation-transform-2025/build.gradle.kts
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/dsp-negotiation-transform-2025/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/v2025/DspNegotiationTransformV2025Extension.java
  data-protocols/dsp/dsp-negotiation/dsp-negotiation-2025/dsp-negotiation-transform-2025/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/spi/type/DspConstants.java
  data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/spi/version/DspVersions.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/build.gradle.kts
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/dsp-transfer-process-http-api-2025/build.gradle.kts
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/dsp-transfer-process-http-api-2025/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/http/api/v2025/DspTransferProcessApi2025Extension.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/dsp-transfer-process-http-api-2025/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/http/api/v2025/controller/DspTransferProcessApiController20251.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/dsp-transfer-process-http-api-2025/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/dsp-transfer-process-http-api-2025/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/http/api/v2025/DspTransferProcessApiExtension2025Test.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/dsp-transfer-process-http-api-2025/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/http/api/v2025/controller/DspTransferProcessApiControllerV20251Test.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/dsp-transfer-process-transform-2025/build.gradle.kts
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/dsp-transfer-process-transform-2025/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/v2025/DspTransferProcessTransformV2025Extension.java
  data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-2025/dsp-transfer-process-transform-2025/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
  extensions/common/json-ld/src/main/resources/document/dspace-edc-context-v1.jsonld
  extensions/common/json-ld/src/main/resources/document/dspace-v2025-1-odrl.jsonld
  extensions/common/json-ld/src/main/resources/document/dspace-v2025-1.jsonld
  extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java
  settings.gradle.kts
  spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/Namespaces.java
  system-tests/e2e-transfer-test/control-plane/build.gradle.kts
  system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
  system-tests/management-api/management-api-test-runner/build.gradle.kts
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/DspSerdeEndToEndTest.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/DspTestFunctions.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TestFunctions.java
  system-tests/management-api/management-api-test-runtime/build.gradle.kts
  system-tests/protocol-2025-test/build.gradle.kts
  system-tests/protocol-2025-test/src/test/java/org/eclipse/edc/test/e2e/protocol/v2025/DspCatalogApi2025EndToEndTest.java
  system-tests/protocol-2025-test/src/test/java/org/eclipse/edc/test/e2e/protocol/v2025/DspNegotiationApi2025EndToEndTest.java
  system-tests/protocol-2025-test/src/test/java/org/eclipse/edc/test/e2e/protocol/v2025/DspTransferApi2025EndToEndTest.java
  system-tests/protocol-2025-test/src/test/java/org/eclipse/edc/test/e2e/protocol/v2025/ProtocolVersionContextProvider.java
Labels: enhancement, dataspace-protocol

#4894 chore: fix dsp negotiation 2025 path
  settings.gradle.kts
Labels: bug

#4877 docs: DR for retry processor on dataflow completion
  docs/developer/decision-records/2025-03-17-retry-processor-on-dataflow-completion/README.md
Labels: documentation
