Repository eclipse-edc/Connector, pull requests merged in 2025-08, with the labels that each got.

#5174 fix: DSP TCK runtime
  system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/java/org/eclipse/edc/tck/dsp/PostgresEdcCompatibilityDockerTest.java
  system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/identity/TckIdentityExtension.java
Labels: bug

#5180 build(deps): bump gradlew to 9.0
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
  system-tests/version-api/version-api-test-runner/build.gradle.kts
Labels: dependencies

#5184 refactor: removes protocol version management api and cleanup
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java
  core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/protocol/VersionServiceImpl.java
  data-protocols/dsp/dsp-core/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/DspHttpCoreExtension.java
  data-protocols/dsp/dsp-version/build.gradle.kts
  data-protocols/dsp/dsp-version/dsp-version-http-dispatcher/build.gradle.kts
  data-protocols/dsp/dsp-version/dsp-version-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/version/http/dispatcher/DspVersionHttpDispatcherExtension.java
  data-protocols/dsp/dsp-version/dsp-version-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/version/http/dispatcher/VersionApiPaths.java
  data-protocols/dsp/dsp-version/dsp-version-http-dispatcher/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/common/api/management-api-configuration/src/main/resources/management-api-version.json
  extensions/control-plane/api/management-api/build.gradle.kts
  extensions/control-plane/api/management-api/protocol-version-api/build.gradle.kts
  extensions/control-plane/api/management-api/protocol-version-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/ProtocolVersionApiExtension.java
  extensions/control-plane/api/management-api/protocol-version-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/transform/JsonObjectToProtocolVersionRequestTransformer.java
  extensions/control-plane/api/management-api/protocol-version-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/v4alpha/ProtocolVersionApiV4AlphaController.java
  extensions/control-plane/api/management-api/protocol-version-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/v4alpha/ProtocolVersionApiV4alpha.java
  extensions/control-plane/api/management-api/protocol-version-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/validation/ProtocolVersionRequestValidator.java
  extensions/control-plane/api/management-api/protocol-version-api/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/control-plane/api/management-api/protocol-version-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/ProtocolVersionApiExtensionTest.java
  extensions/control-plane/api/management-api/protocol-version-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/ProtocolVersionApiTest.java
  extensions/control-plane/api/management-api/protocol-version-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/transform/JsonObjectToProtocolVersionRequestTransformerTest.java
  extensions/control-plane/api/management-api/protocol-version-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/v4alpha/ProtocolVersionV4AlphaApiControllerTest.java
  extensions/control-plane/api/management-api/protocol-version-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/validation/ProtocolVersionRequestValidatorTest.java
  settings.gradle.kts
  spi/common/policy/request-policy-context-spi/src/main/java/org/eclipse/edc/policy/context/request/spi/RequestVersionPolicyContext.java
  spi/control-plane/control-plane-spi/build.gradle.kts
  spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/controlplane/services/spi/protocol/VersionService.java
  spi/control-plane/protocol-version-spi/build.gradle.kts
  spi/control-plane/protocol-version-spi/src/main/java/org/eclipse/edc/connector/controlplane/protocolversion/spi/ProtocolVersionRequest.java
  spi/control-plane/protocol-version-spi/src/main/java/org/eclipse/edc/connector/controlplane/protocolversion/spi/ProtocolVersionRequestMessage.java
  system-tests/dcp-tck-tests/presentation/src/test/java/org/eclipse/edc/test/e2e/tck/presentation/DefaultScopeFunctionExtension.java
  system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ProtocolVersionApiEndToEndTest.java
Labels: refactoring

#5193 docs: DR about introducing a participant context
  docs/developer/decision-records/2025-08-26-participant-context/README.md
  docs/developer/decision-records/README.md
Labels: documentation, enhancement
